### ISSUE TITLE
能否增加一键配置符文功能

### ISSUE THREAD

**Issue by duzhor** [Zzaphkiel/Seraphine#10]
很高兴找到了我期望的用pyqt5实现。
我自己也写了一点点，但是不太会gui，对我来说这个项目就缺个一键配置符文功能，希望能一起维护。

**Comment by Zzaphkiel** [comment]
感谢建议。

推荐符文的数据感觉可以从 op.gg 搞过来，配置符文不知有没有提供的 api，等我闲下来可以研究一下 😘

**Comment by Zzaphkiel** [comment]
好的，感谢 🥰

**Comment by Hpero4** [comment]
> 很高兴找到了我期望的用pyqt5实现。 我自己也写了一点点，但是不太会gui，这个项目对我来说就缺个一键配置符文功能，希望能一起维护。

欢迎加入!

对于数据网站我有一点点自己的想法

目前游戏内的一键符文的数据源似乎也是101, 但它缺乏基于不同段位的筛选功能; 

此外, 内置的装备推荐缺乏指向性, 数据网站中会有明确的装备选用率和出装顺序, 而游戏内置的装备推荐系统则会将所有推荐的装备均以高亮显示.

有其他好的想法也可以随时提出来一起讨论下~ 

如果能将这两点考虑在设计中, 我相信会非常nice, 期待你的pr!

**Comment by Hpero4** [comment]
@duzhor 请问该Issue提到的相关功能开发进展还顺利吗? 我有意向着手去做关于数据网站接入的工作, 如有进展请在该Issue中同步, 感谢! 😉

**Comment by Hpero4** [comment]
@duzhor 我想下怎么做会好点, 我打算在锁定英雄之后切换到一个新的页面, 用于展示英雄信息, 通过支持 **通过段位进行筛选** , 信息包括

- 核心装备选择(出装顺序)
- 装备选用率
- 技能加点路线
- 符文选择
- 优劣势对抗 等

相当于把数据网站接入到Seraphine中, 自动查询; 接口可以在设置中选择, opgg或101或其他您能够支持的API

**Comment by Swaynani** [comment]
作者牛逼

**Comment by cake79** [comment]
大家牛逼

**Comment by HyhBlazing** [comment]
我还在尝试做的时候，找接口找到作者，好厉害
![1111111](https://github.com/Zzaphkiel/Seraphine/assets/40458321/7a788c68-1383-4c21-a8d7-d1f9a3f9b975)

**Comment by Ninohana** [comment]
# 符文装备数据接口

https://github.com/Ninohana/data-long

可参考或直接用作后端

**Comment by z1298808165** [comment]
@Zzaphkiel 大佬，请问现在符文、装备的功能排期的怎么样啦，大概什么时候可以上线呢

**Comment by Zzaphkiel** [comment]
> @Zzaphkiel 大佬，请问现在符文、装备的功能排期的怎么样啦，大概什么时候可以上线呢

@z1298808165 目前主要任务是修 BUG。~关于符文配置已经新建文件夹了~

**Comment by z1298808165** [comment]
> > @Zzaphkiel 大佬，请问现在符文、装备的功能排期的怎么样啦，大概什么时候可以上线呢
> 
> @z1298808165 目前主要任务是修 BUG。~关于符文配置已经新建文件夹了~

好的，期待可以尽早见面 😊

**Comment by z1298808165** [comment]
> # 符文装备数据接口
> https://github.com/Ninohana/data-long
> 
> 可参考或直接用作后端

不知大佬能否直接PR一个🥰

**Comment by Ninohana** [comment]
> > # 符文装备数据接口
> > https://github.com/Ninohana/data-long
> > 可参考或直接用作后端
> 
> 不知大佬能否直接PR一个🥰

这只是一个后端项目

我是菜鸡，不擅长GUI相关，考虑到界面、动效、风格统一以及交互，更适合让已有构思的大佬主导，正如我一开始所说，我是一个菜鸟。

**Comment by Xarotta** [comment]
顺便添加下野怪/大乱斗血包计时

**Comment by Zzaphkiel** [comment]
> 顺便添加下野怪/大乱斗血包计时

@Xarotta 游戏内功能都**不能做 / 不打算**做。

**Comment by holwell** [comment]
> > 顺便添加下野怪/大乱斗血包计时
> 
> @Xarotta 游戏内功能都**不能做 / 不打算**做。

作者大佬，感觉要从0新增一个一键配置符文会比较费时，又得考虑数据接口又得考虑ui设计，在那之前，能否简单的基于所前所选英雄做一个opgg的网址快捷方式，会简单很多，按钮显示在对局信息页面。
opgg链接类似这样：` https://www.op.gg/champions/leona/build/support ` 替换其中的英雄id即可，简单又实用。

**Comment by Zzaphkiel** [comment]
@holwell fork 了自己改一下吧，我个人不想做 “暂时凑活着用” 的功能

**Comment by molover02** [comment]
https://github.com/ping11700/LOLKit
发现这个项目 有自动配置符文, 装备. 101, opgg都有.
看大佬能不能pr一下

**Comment by Zzaphkiel** [comment]
仓库代码已实现该功能

**Comment by z1298808165** [comment]
> 仓库代码已实现该功能

大佬，一键符文已经实现了，推荐出装还远吗😄，后面会做吗

**Comment by Zzaphkiel** [comment]
> 大佬，一键符文已经实现了，推荐出装还远吗😄，后面会做吗

@z1298808165 release 页面有惊喜😄

**Comment by z1298808165** [comment]
> > 大佬，一键符文已经实现了，推荐出装还远吗😄，后面会做吗
> 
> @z1298808165 release 页面有惊喜😄

看到啦，可能没表达清楚😄，我意思是推荐出装应用到游戏内，现在可以做到嘛还没有时间去看😊

**Comment by Zzaphkiel** [comment]
@z1298808165 暂无开发计划

**Comment by z1298808165** [comment]
> @z1298808165 暂无开发计划

好嘞

**Comment by molover02** [comment]
> > > 大佬，一键符文已经实现了，推荐出装还远吗😄，后面会做吗
> > 
> > 
> > @z1298808165 release 页面有惊喜😄
> 
> 看到啦，可能没表达清楚😄，我意思是推荐出装应用到游戏内，现在可以做到嘛还没有时间去看😊

https://github.com/ping11700/LOLKit 这位大佬早就实现了, 希望pr一下
