### ISSUE TITLE
安全系统或数据被篡改16-0

### ISSUE THREAD

**Issue by a906400242** [Zzaphkiel/Seraphine#104]
有把战绩太差 可能被举报多了 然后被系统检测出来了 封号1小时
大家用的时候还是小心一点吧 : (

**Comment by Hpero4** [comment]
感谢反馈! 

这个问题似乎确实存在...
后续我们将会密切关注, 如果担心封号的小伙伴还请暂时不要在开启状态下进入对局(BP完就退掉)

![IICU5{ WP(`7NVZH N5PQKI](https://github.com/Zzaphkiel/Seraphine/assets/40506420/e4db2104-8f6a-469f-b499-ebd322280b72)

**Comment by Zzaphkiel** [comment]
我倒是没遇到过这个问题呢，去[封号查询系统](https://lol.qq.com/act/a20151118fh/)看一下封禁理由呢？

**Comment by ASTPoseidon** [comment]
![Screenshot_2023-10-19-08-36-32-160_com.tencent.mobileqq.png](https://github.com/Zzaphkiel/Seraphine/assets/71622612/74581d32-9aaf-4d64-b704-dec460ea5df4)


同问题

**Comment by Hpero4** [comment]
> 感谢反馈!
> 
> 这个问题似乎确实存在... 后续我们将会密切关注, 如果担心封号的小伙伴还请暂时不要在开启状态下进入对局(BP完就退掉)
> 
> @a906400242 请问您遇到的 "安全系统或数据被篡改16-0" 是在游戏过程中弹出的提示吗?
> 
> ![IICU5{ WP(`7NVZH N5PQKI](https://user-images.githubusercontent.com/40506420/275332107-e4db2104-8f6a-469f-b499-ebd322280b72.png)

后续没有再遇到过, 怀疑与 #96 中所用到的全局钩子有关, 后续会重点测试, 如果证实是该功能导致将不会在正式版中上线该功能

**Comment by a906400242** [comment]
> > 感谢反馈!
> > 这个问题似乎确实存在... 后续我们将会密切关注, 如果担心封号的小伙伴还请暂时不要在开启状态下进入对局(BP完就退掉)
> > @a906400242 请问您遇到的 "安全系统或数据被篡改16-0" 是在游戏过程中弹出的提示吗?
> > ![IICU5{ WP(`7NVZH N5PQKI](https://user-images.githubusercontent.com/40506420/275332107-e4db2104-8f6a-469f-b499-ebd322280b72.png)
> 
> 后续没有再遇到过, 怀疑与 #96 中所用到的全局钩子有关, 后续会重点测试, 如果证实是该功能导致将不会在正式版中上线该功能

打完游戏后在客户端页面停留了一会 有个好友跟我发了一条消息后我就突然被提示账号异常 然后重登才发现被封禁 具体的封号代码信息是我在微信的查询系统里面看到的

**Comment by L-Sun** [comment]
这个可能是马服特色，我之前什么都没有开，打完一把大乱斗，客户端直接提示账号异常，也是按这个理由给我封了1小时
