### ISSUE TITLE
打包后的程序无法运行

### ISSUE THREAD

**Issue by RicharYe** [Zzaphkiel/Seraphine#106]
![9VB36G5J18VGG`X@}_MU @H](https://github.com/Zzaphkiel/Seraphine/assets/129949451/bd71b5d6-0d4b-4466-938f-5bf7d9c35fab)

![H($M6%_GA 8R{I~3AMV4J%3](https://github.com/Zzaphkiel/Seraphine/assets/129949451/1d60ebd6-1f54-4d1f-9917-20530185246f)

百度也没找到解决办法，小白一个，求解答，Thanks♪(･ω･)ﾉ

**Comment by RicharYe** [comment]
运行的是自己打包后的Seraphine.exe

**Comment by RicharYe** [comment]
![A5RA @XDQRAGWEK9T7M@ 7W](https://github.com/Zzaphkiel/Seraphine/assets/129949451/4311a122-0e7d-4c67-acf5-f8c60ffcce57)

![1P~WGOI8SFGW7 KMU(_GT(G](https://github.com/Zzaphkiel/Seraphine/assets/129949451/5fe7ae8d-bf51-45ef-b1c7-a469b55deb86)
改成了py3.8   并且换了pyinstall的版本也不行 ，          ε=(´ο｀*)))唉

**Comment by Zzaphkiel** [comment]
直接在环境里运行 `main.py` 能用不 😭？

**Comment by RicharYe** [comment]
直接在环境里运行可以运行，始终无法打包（难过）
![image](https://github.com/Zzaphkiel/Seraphine/assets/129949451/ae8c6861-ce99-4307-ac4e-f90027a1148c)

**Comment by Zzaphkiel** [comment]
用其他的方式打包试试呢？比如 nuitka 之类的？

**Comment by RicharYe** [comment]
OK 弄好了 打包出来了，不过感觉根目录文件跟你打包出来的少很多文件，但是能用目前也没发现有报错。
