### ISSUE TITLE
[feature]建议增加显示挂机率的功能。

### ISSUE THREAD

**Issue by CoREse** [Zzaphkiel/Seraphine#107]
感觉挂机率是个很重要的指标，可以剔除某些喜欢挂机的人，如果看到某个人挂机率比较高，这把就可以退了。

**Comment by Hpero4** [comment]
感谢反馈！

逃跑的信息不知道有没有包含在历史战绩中,
并且对局信息获取时, 只会拿最近11场的游戏对局, 最多也只能判断近期有没有挂机

该功能有一定价值, 后续我们会结合实际场景决定是否实现

**Comment by CoREse** [comment]
> 感谢反馈！
> 
> 逃跑的信息不知道有没有包含在历史战绩中, 并且对局信息获取时, 只会拿最近11场的游戏对局, 最多也只能判断近期有没有挂机
> 
> 该功能有一定价值, 后续我们会结合实际场景决定是否实现

好滴谢谢。冲！

**Comment by civiliann** [comment]
看看能不能去078悠米那些收费软件解析一下总胜率，车队标记功能之类的哈哈

**Comment by Hpero4** [comment]
@civiliann 

感谢反馈.

此类功能需要搭建服务器作为后端支持才能够实现, 目前暂无计划

**Comment by Zzaphkiel** [comment]
考虑到实现效果与意义，因为有不得不需要挂机的情况（如大乱斗遇胜率队需三分钟重开），故决定暂不实现该功能。
