### ISSUE TITLE
希望增加对局评分

### ISSUE THREAD

**Issue by ilpoint** [Zzaphkiel/Seraphine#108]
希望增加对局评分，SVP MVP等标签。方便复盘是哪个老弟游戏不出力
类似wegame\opgg这样

![微信图片编辑_20231019223833](https://github.com/Zzaphkiel/Seraphine/assets/76519346/bbf4e370-aa2c-4a0b-a4d8-82f215f6178c)

![屏幕截图 2023-10-19 223550](https://github.com/Zzaphkiel/Seraphine/assets/76519346/13f1b31d-3f8a-45f4-9acc-c3548f75c8b7)

**Comment by Zzaphkiel** [comment]
感谢反馈！

作为一个游戏玩家，就我个人的各程序使用情况来说，感觉评分能提供的信息意义不大。对局的 KDA、伤害以及经济足矣用于判断玩家的表现。并且就计算方法的不同，如何提供一个较为准确的评分值也是一个比较困难的问题（比如我自认为 WeGame 评分就做的不够好），所以暂时是没有做评分功能的计划的，还请谅解~

**Comment by Hpero4** [comment]
感谢反馈! 

我跟 @Zzaphkiel 有同样的看法, WeGame的评分系统其实非常复杂, 对于不同模式下的不同英雄处于不同位置时的不同数值都有不同的权重, 并且综合体验下来跟K/D/A没有什么本质上的差异.

个人认为该功能的实用性并不高;

其次关于SVP和MVP的特殊显示, 我们会酌情考虑添加(但希望不大x)
