### ISSUE TITLE
关于软件图标和启动界面logo的问题

### ISSUE THREAD

**Issue by LeopoldChou** [Zzaphkiel/Seraphine#110]
首先，感谢开源并维护这么好用的软件！
我注意到，软件的图标，还有启动时显示的 logo，包括 GitHub 的 readme 文档中的萨勒芬妮《魔力满满》表情图片都不完整，可以看到四周的粉色外发光是被生硬截断的（在深色模式下较为明显）。
我不知道这是你们有意为之，还是没注意到，所以我在这里提供一下客户端提取的这个表情的原文件（还有一个不带边缘外发光的 vfx 中提取的文件），如果有需要可以使用。
![4142_Faerie_Court_2__Seraphine_Inventory ACCESSORIES_13_6](https://github.com/Zzaphkiel/Seraphine/assets/68420848/79990fce-f1f9-4d58-8777-a13189d09deb)
![4142_Faerie_Court_2__Seraphine_vfx](https://github.com/Zzaphkiel/Seraphine/assets/68420848/5077fef9-ee10-4745-adc5-58e22ebe87b9)

**Comment by LeopoldChou** [comment]
好的，稍后我发起一个PR，使用有外发光的版本替换 logo.png
需不需要生成一个 logo.ico 把应用图标也替换了呢？

**Comment by Zzaphkiel** [comment]
已通过 #111 解决该问题
