### ISSUE TITLE
[Future]期望能出个“战犯”评定功能

### ISSUE THREAD

**Issue by swRains** [Zzaphkiel/Seraphine#115]
类似于该项目：
https://gitee.com/zaranengap/lolmvp
https://www.bilibili.com/video/BV12W4y1o7Xv/

能够选定哪几局历史战绩来评估朋友间的开黑“战犯”和“内鬼”，或者上等马之类的，感觉会很有趣

**Comment by Zzaphkiel** [comment]
感谢反馈~

同 #108，暂不考虑加入“评价”相关功能，还请谅解~
