### ISSUE TITLE
希望能够仿照 WeGame 目前的战绩结果页面显示相关数据

### ISSUE THREAD

**Issue by mzji** [Zzaphkiel/Seraphine#117]
如题，感觉 WeGame 能拿到的数据 LCU API 也可以拿到？

**Comment by Zzaphkiel** [comment]
感谢反馈~请问您是有什么内容希望加入到当前的战绩搜索界面里呢？

**Comment by mzji** [comment]
![图片](https://github.com/Zzaphkiel/Seraphine/assets/23279426/38a53335-303c-4833-8531-ed97c4eaca88)
主要是想获取红圈框起来的这个部分

**Comment by mzji** [comment]
![图片](https://github.com/Zzaphkiel/Seraphine/assets/23279426/ea7019c0-c0d8-4136-bb12-38a95413d72c)
补充下面的部分

**Comment by Zzaphkiel** [comment]
考虑到重新画界面与图表的难度，目前没有实现该功能的计划，还请谅解~
