### ISSUE TITLE
一些使用建议

### ISSUE THREAD

**Issue by garyvalue** [Zzaphkiel/Seraphine#12]
很棒的工具
使用过程中有些建议：
1.数据的预加载。连接到游戏之后，预加载历史战绩；进入对局之后，预加载队友的历史战绩；
目前使用看来，数据加载上有些迟缓和卡顿。
2.对局结束后，战绩有时候会未及时更新
3.对局结束后，对局信息希望能延缓关闭，直至下一局游戏或关闭
4.历史战绩中，界面UI的色块不是很能区分，具体可参考wegame历史战绩
5.进入历史战绩，战绩可显示最新的一场对局，目前是空白的
6.对局信息中，对局局数未能铺满整个界面时，可由上往下铺满，目前是由下往上
7.目前切换召唤师战绩会有显卡顿

**Comment by Zzaphkiel** [comment]
感谢您详细的建议。


> 1. 数据的预加载。连接到游戏之后，预加载历史战绩；进入对局之后，预加载队友的历史战绩；

目前历史战绩的加载都是进入到战绩页面之后才会进行的，（在用户点击该界面之前）提前加载战绩感觉确实是一个很好的改进思路，之后应该会逐步实现

> 2. 对局结束后，战绩有时候会未及时更新

战绩的来源是 LCU API，对局结束后战绩未及时更新是因为本身 API 返回的信息是没有更新的，属于英雄联盟服务端的问题（就像客户端在对局结束后，上一局游戏也暂时不会显示在生涯战绩里一样）

> 3. 对局结束后，对局信息希望能延缓关闭，直至下一局游戏或关闭

感觉保留对局信息的必要性不是很大，因为在战绩里也可以查到上一把的战绩（可以讨论）。把对局信息保留在回到小队组队状态之前如何？

> 4. 历史战绩中，界面UI的色块不是很能区分，具体可参考wegame历史战绩

后续将会尝试调整一下颜色，让它们更重一些，到时候再看看是不是好点了

> 5. 进入历史战绩，战绩可显示最新的一场对局，目前是空白的

当初写这块代码的时候没想到这一点，感觉意义不是特别大，如果需要的话后续可以加上

> 6. 对局信息中，对局局数未能铺满整个界面时，可由上往下铺满，目前是由下往上

应该是 BUG，后续逐步修复

> 7. 目前切换召唤师战绩会有显卡顿

没太看懂是怎么切换？（我感觉打包好的 `exe` 文件的性能不如直接运行 `main.py` 好，这相关的问题可能我无能为力）

**Comment by garyvalue** [comment]
> 战绩的来源是 LCU API，对局结束后战绩未及时更新是因为本身 API 返回的信息是没有更新的，属于英雄联盟服务端的问题（就像客户端在对局结束后，上一局游戏也暂时不会显示在生涯战绩里一样）
说起来今天下午大概6点至8点时，战绩无法更新，重启软件也没有效果，但是无法复现

> 感觉保留对局信息的必要性不是很大，因为在战绩里也可以查到上一把的战绩（可以讨论）。把对局信息保留在回到小队组队状态之前如何？
是的，保留在回到小队组队状态即可；进入游戏后貌似也看不到对局信息了

> 没太看懂是怎么切换？（我感觉打包好的 exe 文件的性能不如直接运行 main.py 好，这相关的问题可能我无能为力）
目前使用来看，查看召唤师生涯就会卡顿  如图 https://img.941258.xyz/a/2023/08/27/64ea54a31b8cd.gif
用户不一定有python环境0.0

**Comment by Zzaphkiel** [comment]
感谢反馈。
> ... 战绩无法更新，重启软件也没有效果 ... 进入游戏后貌似也看不到对局信息了 ...

程序获得的的数据来源均为英雄联盟提供的接口，战绩无法更新是接口的问题~

> ... 查看召唤师生涯就会卡顿 ...

目前针对这个卡顿可能暂时无能为力了~

**Comment by garyvalue** [comment]
> 牛马/上等马/下等马

计算得分,添加大神和牛马称谓
最近三把(KDA+输赢)的平均值
KDA->(击杀1.2+助攻0.8)/(死亡*1.2)
输赢->赢+1 输-1

**Comment by Zzaphkiel** [comment]
[lol-helper](https://github.com/4379711/lol-helper) 已经有类似功能，并且该功能涉及到游戏内喊话（参考 #4 ），这里就不实现了

**Comment by garyvalue** [comment]
根据chatgpt的建议进行英雄选择
![182t52ikytsbadskau0gat5z7.png](https://img.941258.xyz/a/2023/09/03/64f3edff1b27a.png)

**Comment by Zzaphkiel** [comment]
> 根据chatgpt的建议进行英雄选择

目前不会实现相关功能。

**Comment by Zzaphkiel** [comment]
1. 本页中第 3、4、5、6 条问题已解决；
2. 第 2 条为 LCU API 问题，不在程序的解决范围之内
3. 第 1、7 条由于个人精力与能力原因暂时无能为力，不过我添加了一个加载界面，来让用户觉得没有那么 “卡” 了

还是感谢反馈，后续有建议可以单开 issue 😘，这个就先关掉了
