### ISSUE TITLE
对局信息布局中显示其位置的建议

### ISSUE THREAD

**Issue by RicharYe** [Zzaphkiel/Seraphine#120]
不知道能不能获取到位置信息，可以的话我觉得可以吧近期对局那边的名字向上移一些然后下面加上位置信息如（上单、中单、射手等）

**Comment by Hpero4** [comment]
@RicharYe 

感谢反馈!

首先, 位置信息是可以获取到的, 如下图中, role应该与BP时所标注的位置一致的, 但lane偶尔会不准确.
![image](https://github.com/Zzaphkiel/Seraphine/assets/40506420/0c912c91-4ae6-4801-a25b-6208dab3c866)

其次, 在生涯页的近期对局标签上添加所走的位置我个人觉得有一定必要, 该信息有一定的参考价值, 但缺乏概览的途径, 只有一局一局点进去看战绩详情才能够获取到.

最后, 关于前端的展示方式我个人更倾向于通过小图标展示在每一局的这个位置
![image](https://github.com/Zzaphkiel/Seraphine/assets/40506420/5e20c5fe-2257-4536-a3b6-e87daff67153)

该功能我们后续会酌情考虑添加, 感谢您的建议!

**Comment by Hpero4** [comment]
理论上该信息只存在于部分对局中（如排位）, 添加图标显示会破坏整体UI设计的一致性

展现形式可能需要再斟酌一下

**Comment by RicharYe** [comment]
我觉得可以不用添加图标，单单只是增加文字标注，排位和匹配分开做两个，排位的文字展示形式可以修改下，
![image](https://github.com/Zzaphkiel/Seraphine/assets/129949451/a9a58dc7-d8e9-4a98-b9bb-74da23565b07)
大致这样  通过不同字号的小和调整字号的方式来获得布局空间， 我认为对战信息这边的布局空间还是挺大的，应该可以塞下

**Comment by Hpero4** [comment]
![image](https://github.com/Zzaphkiel/Seraphine/assets/40506420/86ac1bee-3c2e-452f-b0e4-bb5597c99c9c)

我觉得可以这样改, 先听听 @Zzaphkiel 的意见

**Comment by Zzaphkiel** [comment]
@Hpero4 这个位置的信息需要请求那个对局详细信息的接口吗？如果需要的话在个人生涯界面里每一栏都加入这个信息是不是需要多访问多次接口，影响一些性能呢？

**Comment by Hpero4** [comment]
@Zzaphkiel 我昨天看了下, 目前生涯的加载逻辑也是会请求每一局的对局详情的

**Comment by RicharYe** [comment]
啊，我说的对局界面不是生涯战绩的，是对战时的那个 w(ﾟДﾟ)w
不过生涯战绩这个加的也很不错，赞

**Comment by Hpero4** [comment]
@RicharYe 类似功能我们有在策划当中, 将在近日上线.

功能概述: 对局信息页, bp阶段随楼层排序, 进入游戏后按照上野中辅下顺序排序（仅排位）

**Comment by Zzaphkiel** [comment]
已实现该特性
