### ISSUE TITLE
跨区查询战绩

### ISSUE THREAD

**Issue by wind307** [Zzaphkiel/Seraphine#121]
战绩查询功能貌似不能跨区呢，可不可以增加这个功能，名字一样的按大区列出来

**Comment by Hpero4** [comment]
感谢反馈,

Seraphine基于LCU API实现, 后者并没有提供跨大区查询的接口, 因此该功能暂不考虑实现

**Comment by XJingxian** [comment]
功能锁定游戏设置让你游戏设置不会因为切换账号而改变 我点击了开 如何恢复重新设置呢？因为我每一次都是之前最开始那种设置 每次需要重新调整 意思就是进一次游戏需要改一次 都是设置的最原先的第一次设置过的。 游戏里设置再次更改过后在点击功能开启 还是一次设置过得设置  把软件删了 重新安装还是之前最原始设置过的设置  说的有点复杂绕口 不知道能否解决呢

**Comment by Zzaphkiel** [comment]
@XJingxian 新问题请新开 issue 哦~

可以参考 [这个视频](https://www.bilibili.com/video/BV1s84y1x7ub) 手动设置一下文件的读写属性来恢复正常，程序也是通过这种方式来实现锁定设置的~

**Comment by Hpero4** [comment]
@XJingxian 感谢反馈! 

新问题请新开 issue 哦~

您需要先关闭"锁定游戏设置"选项后, 再修改游戏设置才会保留到下一局游戏中, 否则会被还原.

如果您设置完成后想要保证当前设定不被修改, 可以再次开启"锁定游戏设置"功能.

---

关于重新安装软件后, 选项卡的初始状态的确存在一些歧义;
如: 您曾经开启过该功能, 重新安装后开关显示是关, 届时在游戏中修改设置是不会被保存的

这个问题在下个版本会得到解决 #123
