### ISSUE TITLE
在战绩查询界面左边战绩一览中提示当前选中对局的建议

### ISSUE THREAD

**Issue by Lllouiskoo** [Zzaphkiel/Seraphine#124]
战绩查询页面选中某一局比赛，显示对局表示信息的时候，希望能在左边战绩一览那边加个**选中框**，那样能看得出来正在看的是那一局对局

**Comment by Hpero4** [comment]
@Lllouiskoo 后续考虑通过加粗当前选中对局的边框的方式呈现

**Comment by Zzaphkiel** [comment]
感觉加深颜色也可以？

**Comment by Hpero4** [comment]
@Zzaphkiel 加深颜色和鼠标悬停时的表现方式相同, 如果用一个更深的颜色来表示选中, 我有些担心会不会令同个页面看上去颜色层次过多了  _(:з」∠)_

**Comment by Zzaphkiel** [comment]
具体的表现形式改一下样式表就可以，我给它实现出来然后再对比一下哪个效果好~

**Comment by Zzaphkiel** [comment]
已实现该功能
