### ISSUE TITLE
[BUG] 若在BP进行到一半才打开软件, 进入游戏后仍会有部分队友的头像不是英雄头像

### ISSUE THREAD

**Issue by Hpero4** [Zzaphkiel/Seraphine#129]
若在BP进行到一半才打开软件, 进入游戏后仍会有部分队友的头像不是英雄头像

![image](https://github.com/Zzaphkiel/Seraphine/assets/40506420/94fe7c5d-a83a-4ed3-ac42-4ce39cd7a302)

Seraphine Ver: v0.9.0-dev
发布版本是否存在该问题: 是

- 现象: 
  - 在bp进行中打开软件, 所有在软件打开前已经完成选用的玩家会显示为召唤师头像
- 预期:
  - 只要召唤师选用了英雄, 就应显示为英雄头像, 无论软件打开的时机
- FYI:
  - 当前英雄头像更新逻辑: https://github.com/Zzaphkiel/Seraphine/blob/4666e1283b897d0a324a2ed40832b82ee07e51dc/app/view/main_window.py#L807-L817

**Comment by Hpero4** [comment]
经查, 该BUG是进入游戏后更新排序时导致

**Comment by Zzaphkiel** [comment]
已修复该问题
