### ISSUE TITLE
一点点小建议

### ISSUE THREAD

**Issue by LiuliGejin** [Zzaphkiel/Seraphine#13]
非常感谢作者提供的软件，速度相当快且进入对局自动查询，用的很舒服

提供一点点小建议
1、对局信息内的展示UI，看的有点不清楚，是否可以优化一下
2、是否可以新增开黑展示，只要查询上局和本局都在一起，就判定为开黑，虽然不准确，但是效率高，应该也不需要大的性能和api之类的。开黑的玩家ID用同一颜色标记，有两队玩家就是两种颜色
3、对局信息内，友方、敌方战绩是否能展示在一个页面内，这样看起来更加方便
4、看到本软件是有返回键的，但是在左上角，第一次用真没发现，电脑的窗口UI一般都在右上角的

最后再次感谢作者，用的真的很舒服🙏

**Comment by Zzaphkiel** [comment]
感谢您的支持与建议。

> 1、对局信息内的展示UI，看的有点不清楚，是否可以优化一下
> 3、对局信息内，友方、敌方战绩是否能展示在一个页面内，这样看起来更加方便

这两点是可以理解为一起的嘛？在当初写代码的时候本意是想把双方的都展示在一个界面里的，但是苦于 UI 设计能力有限，最终还是模仿了 [Frank](https://github.com/Java-S12138/frank) 的展示方式，把双方的信息分别放在两个界面中。不知道有没有好一点的，可以一页放 10 个召唤师信息的 UI 设计方案（可以讨论）？如果没有的话可能要暂时维持现状了

> 2、是否可以新增开黑展示，只要查询上局和本局都在一起，就判定为开黑，虽然不准确，但是效率高，应该也不需要大的性能和api之类的。开黑的玩家ID用同一颜色标记，有两队玩家就是两种颜色

之前是想要加入这个功能的，但是经过自己的使用发现，在看玩家信息的时候，通过观察是不是一起胜负，基本上也可以比较准确地判断是不是开黑的了。不过相比于观察胜负，通过您提供的这种方式确实可以有一个更好的判断，也更直观，后续可以实现这个功能，但可能优先度不会很高~

> 4、看到本软件是有返回键的，但是在左上角，第一次用真没发现，电脑的窗口UI一般都在右上角的

UI 窗口基本上遵循了 Fluent design 的理念，如果您是 Win 11 系统，您的设置页面的返回键也是在左上角的~

**Comment by RicharYe** [comment]
同，想要查询开黑的功能，刚组成的队还是挺多的，这个功能真的很需要！w(ﾟДﾟ)w

**Comment by Zzaphkiel** [comment]
> 同，想要查询开黑的功能，刚组成的队还是挺多的，这个功能真的很需要！w(ﾟДﾟ)w

刚组成的队伍可能没有可以判断的方法（目前我还不知道），实现的功能应该还是根据分析上一局的队友是否重复来判断的

**Comment by RicharYe** [comment]
以前用的是LOLcha网页的，不知道他们怎么实现的，可惜现在这个网站被干掉了，已经停了。  seraphine 很好用 蟹蟹作者\(^o^)/

**Comment by Jolkssn** [comment]
正巧这位的建议和我的想法也基本一致。
关于第一条，对局信息里的KDA数据有时会因长度超过显示区域宽度而导致显示不完全
关于第二条，检测开黑个人认为可以通过比较玩家是否连续三局在一起来判断，偶尔也会有碰巧连续两局都匹配在一队的玩家，而连续三局都在一起的概率就小多了；判断完成后可以通过用同一颜色显示ID、border边框的方式来表现
关于第三条，个人也感觉把双方信息放在同一页会更便于查看，可以上面显示五个己方信息，下面显示五个对方信息，若高度不够可以加个滚动条

**Comment by Zzaphkiel** [comment]
@Jolkssn 
1. 感谢反馈，后续会修复。
1. 我依旧认为只根据上一局的队友判断会比较好，这样刚刚组队两局的玩家也可以被正确地判断为组队。比起误判，我感觉漏判是更不好的。更何况这个功能对原来写好的代码不是很友好，可能写起来比较麻烦
1. 我有一些自己的 “强迫症”，感觉在这个界面中加一个滚动条会非常的不美观，也便捷不到哪里去。还是保留原样吧 😥

**Comment by ThudrK** [comment]
生涯页面打完不会自动刷新，需要点头像刷新，希望可以改成每打完一把自动刷新。另外点X就关闭程序了，能否增加一个点X是缩小程序到右下角选项？其他功能界面都很好，谢谢。

**Comment by Zzaphkiel** [comment]
> 生涯页面打完不会自动刷新，需要点头像刷新，希望可以改成每打完一把自动刷新。另外点X就关闭程序了，能否增加一个点X是缩小程序到右下角选项？其他功能界面都很好，谢谢。

@ThudrK 新功能建议新开 issue 讨论哦，请移步 #23

**Comment by Zzaphkiel** [comment]
已实现 (#26)
