### ISSUE TITLE
[BUG] 查询战绩时, 如果翻到最后一页, 会将所有剩余战绩挤到一页中

### ISSUE THREAD

**Issue by Hpero4** [Zzaphkiel/Seraphine#133]
![image](https://github.com/Zzaphkiel/Seraphine/assets/40506420/306d5d7b-5504-41e5-889a-9cafe07c5fba)

预期行为: 最后的一局独占一页

Seraphine Ver: v0.9.0-dev
release版本是否存在该问题: 否

**Comment by Zzaphkiel** [comment]
已修复该问题
