### ISSUE TITLE
[BUG] 在"匹配确认"状态下打开软件, 会一直卡在匹配确认而不会进入对局信息页获取队友信息

### ISSUE THREAD

**Issue by Hpero4** [Zzaphkiel/Seraphine#134]
![image](https://github.com/Zzaphkiel/Seraphine/assets/40506420/3d738acb-37a2-494b-bb21-ef89ed35814c)

Ver: 0.9.0-dev
release 是否存在问题: 未测试

**Comment by Zzaphkiel** [comment]
目前无法复现该问题，有遇到类似问题的朋友可以在该页下留言以提供更多信息~
