### ISSUE TITLE
seraphine后台运行时会造成游戏掉帧

### ISSUE THREAD

**Issue by chichenghao123** [Zzaphkiel/Seraphine#137]

**Comment by Hpero4** [comment]
@chichenghao123 

感谢反馈!

我们正在排查该问题, 若与您遇到的问题与 #127 相同, 后续可以移步 #127 提供更多的信息以帮助我们定位问题.

**Comment by Zzaphkiel** [comment]
目前库中代码已修复该问题，打包版本随下个 release 发布

**Comment by Zzaphkiel** [comment]
目前库中代码已修复该问题，打包版本随下个 release 发布
