### ISSUE TITLE
选择英雄阶段抛出异常

### ISSUE THREAD

**Issue by LeopoldChou** [Zzaphkiel/Seraphine#139]
打开软件之后什么也没干，就挂在后台，英雄选择阶段突然弹出来
![11699244763_ pic](https://github.com/Zzaphkiel/Seraphine/assets/68420848/cf7c3b98-6726-4d1d-877c-63059e755bd7)
Traceback (most recent call last):
  File "qfluentwidgets\components\widgets\tool_tip.py", line 306, in showToolTip
  File "qfluentwidgets\components\widgets\tool_tip.py", line 124, in adjustPos
  File "qfluentwidgets\components\widgets\tool_tip.py", line 134, in position
AttributeError: 'NoneType' object has no attribute 'availableGeometry'

**Comment by Zzaphkiel** [comment]
感谢反馈~

请问该问题还有再次发生吗？有没有什么操作顺序可以让它大概率发生呢？

**Comment by arrrrre** [comment]
![IMG_20231112_101316](https://github.com/Zzaphkiel/Seraphine/assets/111839450/384465ab-f85e-4295-9399-e3f686247b07)

**Comment by arrrrre** [comment]
![IMG_20231112_101316](https://github.com/Zzaphkiel/Seraphine/assets/111839450/a4f77cfa-d650-4686-871b-5c4b504555d2)

**Comment by arrrrre** [comment]
![IMG_20231112_101316](https://github.com/Zzaphkiel/Seraphine/assets/111839450/d66551cd-9f6d-4368-b150-e67cd2504698)

**Comment by arrrrre** [comment]
我的也是这样  一般是选完英雄进游戏就会这样  我的是直接卡死

**Comment by Zzaphkiel** [comment]
@arrrrre 抱歉回复较慢，感谢您的反馈，您的问题应该同 #145 一样，是由 “在游戏进行时最小化 Seraphine 窗口” 功能所引起的，您可以在设置页面中暂时关闭该功能 🥲

**Comment by LeopoldChou** [comment]
近期正常使用过程中未出现该错误，暂不清楚如何触发
如果有具体复现步骤我会再次 comment
