### ISSUE TITLE
设置被锁定了 更改不了

### ISSUE THREAD

**Issue by jediguo** [Zzaphkiel/Seraphine#141]
有个锁定设置的 我开了以后 本地无法更改设置了 会一直恢复到我第一次锁定设置时候的设置。不知道是否描述清楚， 就是锁定了一次设置，然后我后面想更改 无法更改了 删除软件也不管用 >。<

**Comment by Zzaphkiel** [comment]
关掉锁定设置的选项之后可以改游戏设置吗？

**Comment by jediguo** [comment]
> 关掉锁定设置的选项之后可以改游戏设置吗？

不行。。。 实在不行 只能重新安装客户端了

**Comment by Zzaphkiel** [comment]
请问您使用的 Seraphine 版本是多少呢？我在 v0.9.0 无法复现您的问题：在关闭 “锁定游戏设置” 选项之后，游戏内的设置是可以被正确保存的

**Comment by Zzaphkiel** [comment]
若问题仍存在，可参考[这个视频](https://www.bilibili.com/video/BV1s84y1x7ub)手动修复一下~
