### ISSUE TITLE
希望标注一下，哪个是隐藏战绩的。

### ISSUE THREAD

**Issue by cw-taotao** [Zzaphkiel/Seraphine#143]
在头像或名字增加个图标，标注一下，哪些瓜皮是隐藏的，哈哈

**Comment by Hpero4** [comment]
@cw-taotao 

感谢反馈！

目前LCU API没有提供相关接口, 故无法获取玩家是否隐藏了战绩的信息

**Comment by Zzaphkiel** [comment]
@Hpero4 其实好像还真有（

`connector` 类下的 `getSummonerByName()` 方法返回的数据中的 `privacy` 字段若为 `"PUBLIC"`，则是公开的；若为 `"PRIVATE"`，则是隐藏的。在软件中的具体表现形式可以再讨论一下~

**Comment by Hpero4** [comment]
#156

**Comment by Zzaphkiel** [comment]
已实现该功能
