### ISSUE TITLE
对局信息界面中，如果玩家 ID 换行，则点击后提示召唤师未找到的问题

### ISSUE THREAD

**Issue by qq891534** [Zzaphkiel/Seraphine#144]
点击对局信息，如果玩家ID过长分行，点击该玩家信息会提示召唤师未找到
![111](https://github.com/Zzaphkiel/Seraphine/assets/74325172/23f4afb2-e59d-43d1-89e0-72de6017b19c)
![222](https://github.com/Zzaphkiel/Seraphine/assets/74325172/ec899c4c-a0db-402a-a7f0-7dd0dc94683c)

**Comment by Zzaphkiel** [comment]
感谢反馈~

目前已定位该问题，将随下个发布版本解决 😘

**Comment by Zzaphkiel** [comment]
目前仓库中代码已修复该问题，打包版本将随下版本上线
