### ISSUE TITLE
在游戏进行时最小化 Seraphine 窗口功能导致报错

### ISSUE THREAD

**Issue by gologule** [Zzaphkiel/Seraphine#145]

**Comment by Zzaphkiel** [comment]
感谢反馈~

1. 请问在设置中关闭检查更新功能后依旧会出现该问题吗？
1. 该问题的出现概率高吗？该概率会随着程序的打开时间改变而改变吗？或者会随着您所处的情况改变而改变吗？

我们可能需要一些更多您提供的信息与测试，因为目前我这里无法复现您的问题 🥹

**Comment by gologule** [comment]
Traceback (most recent call last):
File "appNo/listener.py", line 121, in run
File "app\view\main_window.py", line 287, in gameStartMinimize
AttributeError: 'NoneType' object has no attribute 'title

这次是挂着没有操作，一段时间后点击界面突然未响应卡死报错

**Comment by gologule** [comment]
并且关闭后重启软件报错了2次，第三次恢复正常

**Comment by Zzaphkiel** [comment]
请问您挂着软件的时候，游戏处于什么样的状态呢？

**Comment by gologule** [comment]
一直挂在单双排房间中，刚刚点击了一下游戏内界面，软件又报错未响应了

**Comment by gologule** [comment]
现在一直在持续报错，只要目前我的客户端处于这个界面就一直持续报错中，关闭重启软件后点击游戏界面到前台后又会再次报错

**Comment by gologule** [comment]
目前这个可以百分百复现。只要重新打开软件然后将最小化的游戏点开软件就会直接报错，游戏内界面一直处于单双排的房间中。

**Comment by Zzaphkiel** [comment]
感谢您的反馈，我已经复现了您出现的问题。

该问题可能是由 “在游戏进行时最小化 Seraphine 窗口” 功能所引起的，您可以在设置页面中暂时关闭该功能，应该就不会报错了。针对该功能的修复将会随下个版本上线~

**Comment by Zzaphkiel** [comment]
仓库代码已解决该问题，打包版本随下个 release 上线。
