### ISSUE TITLE
[BUG] 查看某单场战绩信息时程序有概率卡死

### ISSUE THREAD

**Issue by gologule** [Zzaphkiel/Seraphine#146]

**Comment by Hpero4** [comment]
感谢反馈！

请问您说点击关闭是指将软件退出吗？之后的操作是重新启动软件之后进行的吗？

目前软件中没有提供主动取消加载的选项

**Comment by gologule** [comment]
是右上角会跳出的绿色提示加载中的那个条幅，有个X的关闭，客户端处于大厅中，目前使用的是最新版本。这个情况比较常见，一般出现于对局结束后。此时软件会一直在右下角存留但是无法关闭也无法呼出界面
![Uploading 微信截图_20231114155249.png…]()

**Comment by gologule** [comment]
![11111](https://github.com/Zzaphkiel/Seraphine/assets/84001104/723a22b7-20ac-4574-8431-0bb40e484b2e)

**Comment by Hpero4** [comment]
@gologule 

您好, 麻烦确认下“在游戏进行时最小化 Seraphine 窗口”是否开启？ 关闭该选项后是否仍存在相同问题？

**Comment by gologule** [comment]
这个选项我是关闭的，一直有这个问题

**Comment by Hpero4** [comment]
@gologule 

您好, 请问游戏客户端是否开启了低性能优化（在游戏时关闭客户端）选项？

在战绩查询时, 大多数时候都会一直转圈吗？

您在哪一个大区进行游戏呢？

**Comment by gologule** [comment]
在战争学院，没有开启低性能优化，一般这个问题都出现在一把游戏刚刚结束后，目前很少在其他时间转圈

**Comment by Hpero4** [comment]
@gologule 

请问是进行完一盘游戏, 客户端回到了大厅后, 立刻进行战绩查询是吗?

**Comment by gologule** [comment]
不用回到大厅，结算界面出来后操作查询之类的就有概率出现这个问题，只要开始转圈了软件就会卡

**Comment by Hpero4** [comment]
目前无法复现该问题，有遇到类似问题的朋友可以在该页下留言以提供更多信息~
