### ISSUE TITLE
[BUG] 软件内点击立即更新跳转的是source的下载链接

### ISSUE THREAD

**Issue by Hpero4** [Zzaphkiel/Seraphine#148]
你好，我不清楚是否是我的设置没有搞明白，每次跳转更新网页都会给我自动下载这个源代码版本。我也只是出于好奇，既然有肯定就能用，想看看其他人有没有人了解的，没想到惊动了开发者啊！！！受宠若惊！！！

_Originally posted by @yuzhenyu1 in https://github.com/Zzaphkiel/Seraphine/issues/147#issuecomment-1809926708_
            

描述: 当新版本发布后, 点击立即更新下载的是source文件而非release压缩包
预期行为: 下载编译后的release版本
ver: v0.9.2-release

**Comment by Zzaphkiel** [comment]
已修复该问题

**Comment by yuzhenyu1** [comment]
更新的包好像又是源代码



&nbsp;


20213638余振宇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月14日(星期二) 晚上7:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zzaphkiel/Seraphine] [BUG] 软件内点击立即更新跳转的是source的下载链接 (Issue #148)





 
Closed #148 as completed.

**Comment by Zzaphkiel** [comment]
@yuzhenyu1 该问题在 0.10.0 版本修复，之前版本该问题一直存在（发布界面已经注明不要通过自带下载按钮更新了）。

**Comment by yuzhenyu1** [comment]
今天傍晚我点击网页内的资产第一个进行下载，还是



下载出来这个，是我哪里没搞明白吗？&nbsp;


20213638余振宇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月12日(星期五) 凌晨1:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zzaphkiel/Seraphine] [BUG] 软件内点击立即更新跳转的是source的下载链接 (Issue #148)





 
@yuzhenyu1 该问题在 0.10.0 版本修复，之前版本该问题一直存在（发布界面已经注明不要通过自带下载按钮更新了）。

**Comment by yuzhenyu1** [comment]
是我太蠢了，不好意思，对不起，打扰了，抱歉！
&nbsp;


20213638余振宇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月12日(星期五) 凌晨1:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zzaphkiel/Seraphine] [BUG] 软件内点击立即更新跳转的是source的下载链接 (Issue #148)





 
@yuzhenyu1 该问题在 0.10.0 版本修复，之前版本该问题一直存在（发布界面已经注明不要通过自带下载按钮更新了）。

**Comment by yuzhenyu1** [comment]
疑问：不晓得为什么被封了，我一共使用过两个WeGame之外的辅助软件。一是r3nzskin，一个就是seraphine。换肤的我已经两天没用了，删掉之后用WeGame深度修复了一次。seraphine还在用，但是封号时没用。我很疑惑。
