### ISSUE TITLE
两个账号都封号了

### ISSUE THREAD

**Issue by awvw12415savdR** [Zzaphkiel/Seraphine#153]
### 问题描述

显示客户端修改文件，只用过这个软件

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.9.1

### 出现率（若有）

未进行具体的重复测试

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Hpero4** [comment]
@awvw12415savdR 

感谢反馈! 

请问有没有到[封号查询系统](https://lol.qq.com/act/a20151118fh/)看一下封禁理由呢？

请问是否打开了"锁定游戏设置"选项?
![image](https://github.com/Zzaphkiel/Seraphine/assets/40506420/8dc303ca-20a2-418b-8e84-4882546c76ad)

**Comment by awvw12415savdR** [comment]
之前打开过 不知道关了没 原因是修改客户端游戏文件&nbsp;


526215252
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月18日(星期六) 晚上9:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zzaphkiel/Seraphine] 两个账号都封号了 (Issue #153)





 
@awvw12415savdR
 
感谢反馈!
 
请问有没有到封号查询系统看一下封禁理由呢？
 
请问是否打开了"锁定游戏设置"选项?

**Comment by awvw12415savdR** [comment]
解封后没开软件还是被封，没用其他插件，不懂

**Comment by Hpero4** [comment]
@awvw12415savdR 

感谢回复

根据您的描述以及此前的用户反馈, 本次封号大概率与Seraphine没有直接关联

并且由于您的多个账号在同一台机器上遭到了多次封禁, 建议排查系统环境, 必要时重装系统以避免短期连续封禁导致的处罚升级

同时, 您也可以尝试与腾讯客服沟通获取进一步的封号原因.

**Comment by awvw12415savdR** [comment]
客服只会说官话，我也开过罗技ghub右键连点，不知道有没有关联

**Comment by Hpero4** [comment]
@awvw12415savdR 

从目前的经验来看, hook层的按键捕获、模拟是有可能会导致账号被警告的, 但暂未收到因此封禁的反馈. 并且目前Seraphine没有加入相关功能.

驱动层的实现暂不清楚是否会导致封号.

**Comment by awvw12415savdR** [comment]
好的谢谢，反正我退游了
