### ISSUE TITLE
[BUG] 如果服务器需要排队, 程序会因为超出最大重试次数而引发异常

### ISSUE THREAD

**Issue by Hpero4** [Zzaphkiel/Seraphine#157]
### 问题描述

![image](https://github.com/Zzaphkiel/Seraphine/assets/40506420/5acf9720-f8eb-4b8d-8bdc-07b90350f4bd)

今晚决赛打完, 很多服务器要排队.
LCU客户端在排队过程中, 是不会响应API请求的.

### 系统信息

Windows 11

### 运行方式

在 Python 环境中直接运行源代码

### 软件版本

0.9.2

### 出现率（若有）

未进行具体的重复测试

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
[v0.10.0](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.10.0) 已解决该问题
