### ISSUE TITLE
可能导致游戏崩溃[BUG] 

### ISSUE THREAD

**Issue by qq891534** [Zzaphkiel/Seraphine#158]
### 问题描述

 英雄选择界面，点击软件生涯刷新功能或者对局信息有概率导致游戏崩溃，直接闪退，没用任何提示。以至于每次重新登录都无法更换召唤师技能与符文。

注：发生过多次该问题，之前版本也有。并且都是在英雄选择界面
![QQ图片20231121195507](https://github.com/Zzaphkiel/Seraphine/assets/74325172/ea486641-612b-4dc5-a142-1b94cb4793e0)

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.9.2

### 客户端状态（若有）

选择英雄

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

非常低的概率会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢反馈，我们将持续关注并尝试修复您遇到的问题 😘

**Comment by Zzaphkiel** [comment]
目前仓库版本已通过限制 LCU API 并发数修复该问题。
