### ISSUE TITLE
[BUG] 更换拳头ID之后无法搜索战绩 

### ISSUE THREAD

**Issue by Swaynani** [Zzaphkiel/Seraphine#159]
### 问题描述

11月21日拳头可以通过变更拳头ID来改变游戏内的ID,改了之后导致助手显示的还是之前的ID,所以找不到数据.但是我搜索新的ID还是找不到,不知道这个问题能不能解决.
![QQ截图20231121203401](https://github.com/Zzaphkiel/Seraphine/assets/57582753/8dc75974-3def-4a22-a3a4-c1bbe0d089df)
![QQ截图20231121203446](https://github.com/Zzaphkiel/Seraphine/assets/57582753/a6036ae3-0e38-49fb-a51b-8ef4fd1f453a)
![QQ截图20231121203857](https://github.com/Zzaphkiel/Seraphine/assets/57582753/e14c6dfb-0460-4b80-b81d-7a6dd984506f)
![QQ截图20231121203944](https://github.com/Zzaphkiel/Seraphine/assets/57582753/2938d3c5-7069-416e-bf51-c325a8833db7)

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.9.2

### 客户端状态（若有）

在线

### 您进行游戏的服务器（若有）

台服

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Swaynani** [comment]
> @Swaynani
> 
> 您好，
> 
> 感谢反馈！
> 
> 您的问题我们已收到，后续会进行排查~
> 
> 请问您提到的“拳头ID”有更详细的描述吗？是LCU客户端的新API吗？
应该不是新的api 
这个是官方的说明 麻烦大佬看一下
https://support-leagueoflegends.riotgames.com/hc/zh-tw/articles/20616577122707-%E5%8F%AC%E5%96%9A%E5%B8%AB%E5%90%8D%E7%A8%B1%E6%94%B9%E7%82%BARiot-ID%E9%81%8E%E6%B8%A1%E6%9C%9F%E5%B8%B8%E8%A6%8B%E5%95%8F%E7%AD%94

**Comment by Swaynani** [comment]
> @Swaynani
> 
> 您好，感谢您的回复~
> 
> 很遗憾，这个以及结果除了大陆(腾讯)以外的所有服务器，我目前并没有账号客户端能够进行测试;
> 
> 我似乎注意到Riot ID源自于传统的召唤师名称引入了“标语”的概念，它基于您所驻留的服务器；
> 
> 您应该可以在类似的此处 ↓ 找到完整的防暴 ID ![图像](https://user-images.githubusercontent.com/40506420/284615806-1ec2739d-c9e6-4f83-8b2e-2d850280983e.png)
> 
> 您可以尝试使用它进行搜索

好的 感谢!

**Comment by Hpero4** [comment]
@Swaynani 

hi！请问上述举措能帮助您正常查询到召唤师吗？

如果有效的话, 我们或许可以就此进行一些优化以使Seraphine适应大陆以外的服务器.

期待你的回复.

**Comment by Swaynani** [comment]
> @Swaynani
> 
> hi！请问上述步骤能帮助您正常查询到召唤师吗？
> 
> 如果有效的话，我们或许可以进行一些优化以使Seraphine适应大陆以外的服务器。
> 
> 期待你的回复。
![QQ截图20231122165530](https://github.com/Zzaphkiel/Seraphine/assets/57582753/98881129-afe4-453e-b314-a03000120052)
zhegefangf
![QQ截图20231122165601](https://github.com/Zzaphkiel/Seraphine/assets/57582753/164a91ff-6f58-4e7d-904e-77afe251d0e4)
这个方法keyic可以查到 但是在界面点击其他人的id就查询不到了

**Comment by Hpero4** [comment]
后续将会在台服进行测试, 以尝试适配更多的客户端

**Comment by Swaynani** [comment]
> 后续将在台服进行测试，以尝试装备更多的客户端

感谢!

**Comment by Hpero4** [comment]
@Swaynani 

Hi, 

在目前代码中, 我们添加了对与大陆以外服务器的支持并进行了简单测试, 
但由于不同服务器间的api返回存在一些差异, 并且外服的使用者相对较少, 预计需要进行更长时间的测试以保证程序稳定.

因此, 我在Fork仓库中发布了beta版本, 希望您能够参加测试并及时反馈问题;
这并不复杂, 您只需要使用beta版本的程序即可, 除此之外没有任何差异

您可以在此处下载beta版本: https://github.com/Hpero4/Seraphine/releases/tag/v0.9.3-beta

期待您的加入! 😉

**Comment by Swaynani** [comment]
非常感谢!发现问题我会第一时间反馈!
&nbsp;


难受
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月24日(星期五) 凌晨1:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zzaphkiel/Seraphine] [BUG] 更换拳头ID之后无法搜索战绩  (Issue #159)





 
@Swaynani
 
Hi,
 
在目前代码中, 我们添加了对与大陆以外服务器的支持并进行了简单测试,
 但由于不同服务器间的api返回存在一些差异, 并且外服的使用者相对较少, 预计需要进行更长时间的测试以保证程序稳定.
 
因此, 我在Fork仓库中发布了beta版本, 希望您能够参加测试并及时反馈问题;
 这并不复杂, 您只需要使用beta版本的程序即可, 除此之外没有任何差异
 
您可以在此处下载beta版本: https://github.com/Hpero4/Seraphine/releases/tag/v0.9.3-beta
 
期待您的加入! 😉
