### ISSUE TITLE
[BUG] 排位战绩过滤功能在对手页面未按预期生效

### ISSUE THREAD

**Issue by Hpero4** [Zzaphkiel/Seraphine#161]
### 问题描述

启用 排位过滤 功能后, 对局信息页应只显示排位战绩. 
![image](https://github.com/Zzaphkiel/Seraphine/assets/40506420/e3bec447-c7a5-40a3-9371-e36039009a2a)

但实际只在队友页起效果, 对手页没有过滤(仍显示了其他战绩)
相关代码:
![image](https://github.com/Zzaphkiel/Seraphine/assets/40506420/31c9157f-8ec0-4f3b-8b81-a826fcb36d08)

并且, 该问题可能导致本不应加载"对局信息"的模式进行数据加载.
相关代码:
![image](https://github.com/Zzaphkiel/Seraphine/assets/40506420/a881a1fb-6da1-4d18-aa58-bfd3435b9a8a)

### 系统信息

Windows 11

### 运行方式

在 Python 环境中直接运行源代码

### 软件版本

0.9.2

### 客户端状态（若有）

游戏中

### 复现方法（若有）

1. 启用 "排位过滤" 功能
2. 进行灵活组排对局

### 您进行游戏的服务器（若有）

N/A

### 出现率（若有）

未测试

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Hpero4** [comment]
故障发生于 灵活组排,

后续大乱斗时观察queueId值未见异常

**Comment by Zzaphkiel** [comment]
#369 已修复该问题
