### ISSUE TITLE
[Enhancement] 使用 teamParticipantId 字段来判断组队玩家

### ISSUE THREAD

**Issue by gitcss-pace** [Zzaphkiel/Seraphine#162]
### 功能描述

https://github.com/BruceQiu1996/NPhoenix/blob/master/LeagueOfLegendsBoxer/ViewModels/MainWindowViewModel.cs
https://github.com/BruceQiu1996/NPhoenix/raw/master/Screenshots/bothsideinfo.png

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by Hpero4** [comment]
@gitcss-pace 

谢谢建议

经过查阅代码, 您提到的NPhoenix是使用'teamParticipantId'字段进行的"开黑"判定, 从目前测试的数据来看, 该字段无法准确的描述玩家的预组队情况, 这可能是游戏更新所导致的; 

后续我们将继续留意该字段.

**Comment by Hpero4** [comment]
@gitcss-pace 

目前的判断逻辑是通过历史战绩实现的. 在设置页面中提供了阈值设置, 一般建议取值为2

**Comment by Hpero4** [comment]
@gitcss-pace 

Hi 

似乎是此前测试方法的问题, 该参数确实有效, 后续将会基于该参数改进"开黑"判断.

感谢!

**Comment by RicharYe** [comment]
(●'◡'●) 太好了，现在的阈值判断从某些方面来说确实不太准确

**Comment by Zzaphkiel** [comment]
[v0.10.0](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.10.0)已上线该功能。
