### ISSUE TITLE
添加黑名单功能

### ISSUE THREAD

**Issue by imzhanxiaosheng** [Zzaphkiel/Seraphine#163]
### 功能描述

是否考虑做一个黑名单功能，数据库可以用本地的Excel表替（毕竟拉黑的用户量应该不会太大，且大多数用户不会装、配置数据库）。
对局开始从Excel中查询是否有玩家在黑名单中，对局结束可以添加玩家信息到黑名单，包括对局时间、kda，使用的英雄。

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈，考虑到实现效果和使用场景，暂时没有相关功能的开发计划，还请谅解。

（P.S. 和 #63 重复了）

**Comment by liuxinghhbyf** [comment]
建议做一个
