### ISSUE TITLE
[Enhancement] 关于软件内显示成就点数大区内排名的建议

### ISSUE THREAD

**Issue by P0tP0t** [Zzaphkiel/Seraphine#165]
### 功能描述

尊敬的开发组你们好！首先感谢你们开发此软件方便广大LOL玩家！
我有一个需求，想在软件内增加一项功能：以每个大区为独立单位的玩家成就点数的排行榜。成就点数是每位玩家名片中都会展示的数据，请看图片。
这是官方都尚未开发的领域，也没有得到官方的重视，但成就是每位玩家每天都会看得到摸得着的玩法，我个人觉得成就点数排行榜是一项急需开发的功能。
希望能回复我，十分感谢！
![示例2](https://github.com/Zzaphkiel/Seraphine/assets/152532234/4c9834e1-2006-4e13-bd04-61b152a3af8f)
![示例一](https://github.com/Zzaphkiel/Seraphine/assets/152532234/337cd3af-b02a-4e71-9302-24b338e079ba)
![最后](https://github.com/Zzaphkiel/Seraphine/assets/152532234/1e98ac92-79d7-4860-a4ea-6dbc4f301ffa)

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您对 Seraphine 的支持！

关于您所提到的功能建议，由于我们作为非盈利开源项目，没有自己的服务器支持，所以可能无法实现**程序内获取其他用户的成就点数并显示排名**的功能，还请谅解 😭
