### ISSUE TITLE
当前对局在一个页面显示所有召唤师信息[Enhancement] 

### ISSUE THREAD

**Issue by Ice-small** [Zzaphkiel/Seraphine#166]
### 功能描述

首先感谢该项目的作者及社区贡献者，ui各方面用着很舒服

【建议】：
我不确定是否有配置可以更改成这样，个人在设置里没找到相关配置

1：我希望可以像078那样直接在一个页面显示所有召唤师，而不是分成两栏(**很需要**)。
目前需要点击队友和敌方来切换召唤师战绩信息，无法做到一页直接对比，固然分栏放一起会导致整体字体变小，但是我觉得这样更靠谱，尤其对于有两个屏幕的用户，比如我就会直接把战绩放在副屏上，在游戏中也可以不切屏观看两边召唤师自身能力

2：如果可以将召唤师卡片做成可拖动，这样可以方便用户直接将各路对应上进行对比，如果可以加入自动识别更好(感觉排位的话应该有提供召唤师走哪路的字段，匹配的话可以按英雄本身属性去大致分一下(匹配加这功能可能是个体力活))(**非必要**)

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈！

1. 关于将所有召唤师显示在同一屏幕内，之前已经有过相关的讨论 (见 #41)，涉及到实现难度以及效果，暂时没有大幅度修改目前的界面设计的计划。
2. 最新版本中已经支持按照楼层 / 游戏角色位置排序的功能，卡片的拖动可能暂时也不会实现 🥺。
