### ISSUE TITLE
[Enhancement] 关于黑名单

### ISSUE THREAD

**Issue by liuxinghhbyf** [Zzaphkiel/Seraphine#167]
### 功能描述

我仍然希望添加一个黑名单功能，在对局开始检索队友以及对手是否存在黑名单中的人，存在即以系统消息提示黑名单中的人及拉黑原因。这样很方便进行游戏

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈。

关于黑名单功能之前已经讨论过多次，我们暂时没有实现该功能的计划，望谅解。
