### ISSUE TITLE
一个小建议，CPU占用太高，麻烦优化下。

### ISSUE THREAD

**Issue by kugookill** [Zzaphkiel/Seraphine#17]
谢谢

**Comment by Zzaphkiel** [comment]
性能优化无能为力，我也不想 CPU 占用高~

如果可以的话就要用的时候打开，不用就关掉

**Comment by toprak** [comment]
@Zzaphkiel can't you try optimizing a little bit? it is really good app thanks for it but it sucks my cpu up :D

**Comment by Hpero4** [comment]
@toprak 

Thanks for your feedback! 

We're always working on making things better, but we haven't really dug into the CPU usage part yet. If you find a feature that's eating up your CPU, do let us know in the Issues. We'll take a look at what's going on. Really appreciate your help! 😉
