### ISSUE TITLE
[BUG] 高概率触发软件BUG，无法正常使用

### ISSUE THREAD

**Issue by qq891534** [Zzaphkiel/Seraphine#170]
### 问题描述

BUG，偶尔无法正常使用，重启游戏or辅助软件均未恢复正常，右下角托盘双击无法弹出，邮件也无反应，只能在任务管理器中进行强制关闭

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.92

### 客户端状态（若有）

选择英雄

### 复现方法（若有）

有可能在英雄选择时，单击某个召唤师信息后在加载过程中，再点击查询其他召唤师信息会触发
![111](https://github.com/Zzaphkiel/Seraphine/assets/74325172/fd20f349-7495-4a40-8983-7e2822b52719)
![222](https://github.com/Zzaphkiel/Seraphine/assets/74325172/bf2b88da-8a79-44ba-95e8-2e6b44bc3eed)
![333](https://github.com/Zzaphkiel/Seraphine/assets/74325172/4c31fbca-60f7-4472-b39a-f711581d734b)

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

差不多一半的情况会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by qq891534** [comment]
![444](https://github.com/Zzaphkiel/Seraphine/assets/74325172/65124e9c-5fe9-4b3b-ba50-1aeb1c62df05)

**Comment by qq891534** [comment]
![11111](https://github.com/Zzaphkiel/Seraphine/assets/74325172/8fd7849e-b5b0-4304-9135-66ba876bafef)

**Comment by Zzaphkiel** [comment]
感谢您的反馈。

请问您的问题是集中在某些时间段发生的吗？我们怀疑服务器卡顿会是该问题发生的必要条件 🥲

**Comment by qq891534** [comment]
感谢答复!
具体时段这个没注意，目前还是又出现了这种情况，但游戏内可以正常查询生涯。
明天白天我再留意一下
![111111](https://github.com/Zzaphkiel/Seraphine/assets/74325172/1099b484-f2a3-4f56-a76a-3e863f2208cb)

**Comment by qq891534** [comment]
Seraphine一般在游戏客户端启动前开启，或者是在英雄选择界面打开

**Comment by qq891534** [comment]
游戏启动前打开的Seraphine，还是会出现问题
![123](https://github.com/Zzaphkiel/Seraphine/assets/74325172/b4e87b26-d805-4f29-9525-988fd24d9768)

**Comment by qq891534** [comment]
已发现问题所在，在设置中“显示对局数量”设置为较大数值则会出现该问题。
这边设置成200则必定会出现该问题，调回50则恢复正常。
![222](https://github.com/Zzaphkiel/Seraphine/assets/74325172/30dc70d9-0fc5-4866-b60f-06e7aedbe15e)

**Comment by Hpero4** [comment]
@qq891534 

收到了您的反馈, 后续我们会据此优化使用体验.

感谢！

**Comment by Zzaphkiel** [comment]
目前仓库版本已修复该问题
