### ISSUE TITLE
[Enhancement] 英雄联盟ID系统即将更新为“ID+数字”形式

### ISSUE THREAD

**Issue by cherish725** [Zzaphkiel/Seraphine#171]
### 功能描述

新的英雄联盟ID系统，将由ID+数字的形式，希望seraphine也能及时更新。感谢作者的付出！

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈。

我们会在全部服务器上线该新特性后逐步完成更新跟进，还请耐心等待。

**Comment by Zzaphkiel** [comment]
已完成相关功能性更新，目前在使用新 id 系统的大区也可以正常使用 Seraphine 了（仅仓库版本代码）

打包版本随 id 系统大范围更新后发布~
