### ISSUE TITLE
[BUG] Windows 下在命令行或者“运行”对话框输入完整 exe 文件路径启动会导致启动失败

### ISSUE THREAD

**Issue by mzji** [Zzaphkiel/Seraphine#172]
### 问题描述

无限加载，关闭窗体时会报异常：
![图片](https://github.com/Zzaphkiel/Seraphine/assets/23279426/a9f879b1-b313-46a9-8dac-d701890087aa)

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

v0.9.2 （历史版本也都存在此问题）

### 复现方法（若有）

通过在命令行或者“运行”对话框输入完整 exe 路径的方式启动 Seraphine （如： `E:\Tools\Seraphine\Seraphine.exe` ）

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈。

先 `cd` 到 `Seraphine.exe` 所在的目录试试呢？

**Comment by mzji** [comment]
> 感谢您的反馈。
> 
> 先 `cd` 到 `Seraphine.exe` 所在的目录试试呢？

试了没问题，但是一般来说当前工作目录就是 exe 所在目录啊，这个可以稍微调整一下不用依赖环境变量

**Comment by Zzaphkiel** [comment]
[v0.10.0](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.10.0)已解决该问题。
