### ISSUE TITLE
[BUG] getLolProcessId 函数报错问题

### ISSUE THREAD

**Issue by D0cC-umz** [Zzaphkiel/Seraphine#174]
### 问题描述

启动lol之后，程序就会报错
![1](https://github.com/Zzaphkiel/Seraphine/assets/58365654/5348e98f-b3e9-4b21-8b54-2c5ad7cf2b11)

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

v0.9.2

### 客户端状态（若有）

正常

### 您进行游戏的服务器（若有）

弗雷尔卓德

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Hpero4** [comment]
@D0cC-umz 您好！

请问遇到了什么错误？软件是否有报错？当时进行了什么操作？

我们需要更多的信息以解决您遇到的问题.

**Comment by D0cC-umz** [comment]
![1](https://github.com/Zzaphkiel/Seraphine/assets/58365654/c7635678-162d-4325-92eb-2bc5f4768f09)
可以正常使用

**Comment by Zzaphkiel** [comment]
方便运行一下仓库版本的代码看一下错误信息嘛？按理说应该不会报错的 😭

**Comment by Lyle-LHY** [comment]
![屏幕截图 2023-12-28 175305](https://github.com/Zzaphkiel/Seraphine/assets/87654037/835c2f0c-f61f-4870-85cb-c58f81a93fb1)

**Comment by Zzaphkiel** [comment]
@D0cC-umz @Lyle-LHY 仓库中代码已经尝试修复该问题，`git pull` 之后再运行一下试试吧~

**Comment by Lyle-LHY** [comment]
代码可以了

**Comment by D0cC-umz** [comment]
可以了。感谢🥰
