### ISSUE TITLE
[Enhancement] 希望新增自动ban人功能，真的很需要这个。

### ISSUE THREAD

**Issue by windherd** [Zzaphkiel/Seraphine#175]
### 功能描述

自动接受对局（已有功能）+**自动ban人** 增加尿尿时间，小膀胱者的福音~

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的建议，很抱歉回复较慢~

关于您提到的自动 ban 人，我们将逐步实现该功能，还请耐心等待 ~

**Comment by Zzaphkiel** [comment]
#241 已实现该功能。
