### ISSUE TITLE
[BUG] 由于客户端 ID 系统更新导致的各种问题

### ISSUE THREAD

**Issue by asdasdaisd** [Zzaphkiel/Seraphine#176]
### 问题描述

点击对局没有反应 观战显示找不到该玩家

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.9.2

### 客户端状态（若有）

大厅

### 您进行游戏的服务器（若有）

男爵领域

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Hpero4** [comment]
@asdasdaisd 您好！

你的反馈已经收到,

想确认下, 目前男爵领域是否已经实装了riot id的更新？（名字后面有#号和一串数字或字母）

**Comment by BiggestDM** [comment]
12月19日皮尔特沃夫服务器更新后也有同样的问题，除了历史战绩显示正常外其余功能基本全部失效

**Comment by Zzaphkiel** [comment]
目前仓库版本已修复该问题（测试大区：皮尔特沃夫）：

1. 对局信息界面已经可以正常显示，点击召唤师名后会跳转到正确的生涯界面以及战绩查询界面。
2. 搜索功能可以正常使用，但需要通过 `召唤师名#五位数字 id` 进行搜索。
3. 观战功能可以正常使用，输入的召唤师名同上。

欢迎在使用新 id 系统的大区的玩家使用仓库版本代码进行测试，打包版本待 id 系统大范围更新后发布~
