### ISSUE TITLE
[Enhancement] 新增修复客户度无限转圈以及缩成一块 BUG 功能

### ISSUE THREAD

**Issue by RicharYe** [Zzaphkiel/Seraphine#177]
### 功能描述

https://github.com/LeagueTavern/fix-lcu-window  按照作者视频，这个可以解决游戏界面异常、游戏结算卡转圈，希望能增加这个功能 w(ﾟДﾟ)w

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by RicharYe** [comment]
今天实测确实可以解决这些问题，客户端缺一块，加载卡转圈都能解决。

**Comment by Zzaphkiel** [comment]
感谢您的反馈

1. 目前仓库版本已经实现无线转圈问题的修复功能。
2. 这个客户端缩成一小块的问题我个人没有遇到过，修复这一问题的功能是很迫切需要的嘛 🥺？

**Comment by mzji** [comment]
> 感谢您的反馈
> 
>     1. 目前仓库版本已经实现无线转圈问题的修复功能。
> 
>     2. 这个客户端缩成一小块的问题我个人没有遇到过，修复这一问题的功能是很迫切需要的嘛 🥺？

这问题时常都能碰到，建议整合起来，会非常方便

**Comment by RicharYe** [comment]
╭(°A°`)╮ 客户端缺块我遇到的少，打一天的话可能只会碰到一两次，但是游戏结束卡加载转圈是真的恶心，不知道为什么，可能是运气差吧，我碰到的概率特别大，三把左右基本上肯定会给我搞一次，有时候运气不好打完一把就来一次，好在从b站发现了这个项目，不然每次打完都重进也太麻烦了，很喜欢本软件，所以希望能加上这些修复的功能

**Comment by Zzaphkiel** [comment]
仓库版本已实现修复客户端大小 BUG 的功能，但由于该功能调用了 Win API `SetWindowPos`，需要通过管理员身份启动 Seraphine 才能正常启用。
