### ISSUE TITLE
新增排位+-分

### ISSUE THREAD

**Issue by psp41206** [Zzaphkiel/Seraphine#178]
### 功能描述

希望能够新增排位的加分以及扣分的资讯

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈，很抱歉回复较慢。

经过我们的讨论，由于 LCU API 没有相关记录的查询接口，详细准确的记录玩家排位分数的变化是一件困难且繁琐的事情（只能通过记录当前玩家的分数变化来实现，但玩家可能并不会随时都开着 Seraphine，且 LCU API 的数据更新存在延迟，无法准确的记录是哪一场对局导致了哪一次的分数变化）。同时，保存和展示该变化趋势也比较困难。因此我们暂不实现该功能，请您谅解 😥
