### ISSUE TITLE
关于在对局信息界面显示排位场次与胜率的建议

### ISSUE THREAD

**Issue by MyBlueDream** [Zzaphkiel/Seraphine#18]
通过在段位下方加入排位场次与胜率数据，能更好的分辨那队友技术，方便打野决定帮助哪一条路。经常遇到隐藏战绩，又打得菜的。

**Comment by Zzaphkiel** [comment]
如果调用客户端提供的查段位的接口查自己的段位，可以查到胜场以及负场；而如果要查别人的段位，是只能看到胜场看不到负场的（你使用程序查看他人的生涯界面，也不会显示它排位赛的负场以及胜率）。所以想显示出其他人的排位胜率目前是不可能的😥

**Comment by RicharYe** [comment]
对局能通过绿色和红色来区分胜负，请问通过这个来计算胜率，这一点可以实现吗，不需要总的胜率计算，就计算设置的默认对局数量的胜率。
