### ISSUE TITLE
[BUG] 封号问题相关

### ISSUE THREAD

**Issue by tsui0101** [Zzaphkiel/Seraphine#180]
### 问题描述

最近国服使用后过几小时就会封号一天 查了结果说 安全系统或数据被篡改 我第三个号这样

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.7.0

### 复现方法（若有）

没

### 出现率（若有）

未进行具体的重复测试

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈。

关于您提到的封号问题之前已有过讨论（见 #104、#153），目前针对这一问题还有没一个很好的解释，建议您更新到新的版本（马上会有一个新版本）或者考虑酌情使用 Seraphine 😥
