### ISSUE TITLE
[Question] 双击打开后显示“程序出现异常”

### ISSUE THREAD

**Issue by tanshaobing** [Zzaphkiel/Seraphine#181]
### 问题描述

![微信截图_20231231234511](https://github.com/Zzaphkiel/Seraphine/assets/76858800/4c206a03-55b0-4b33-a9da-522004427ecf)
路径应该没有问题，我放在桌面，没有中文也会出现这个问题，管理员身份运行也不可以。大佬  这是什么情况呀

### 我已经查看了之前（包括已经关闭）的 issue，但这并不能解决我的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢反馈，可以参考一下 #51 哦~
