### ISSUE TITLE
大乱斗闪退问题[BUG] 

### ISSUE THREAD

**Issue by Fan-Bu-THU** [Zzaphkiel/Seraphine#182]
### 问题描述

开着软件突然闪退，只在大乱斗模式出现过，或者频繁点击接受之后没有进入游戏，但是立刻秒匹配上，出现过一次闪退，但是重进之后直接进入BP阶段。以上只出现过在大乱斗。

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

v0.9.2

### 客户端状态（若有）

BP阶段或匹配等待接受阶段

### 复现方法（若有）

因为反复闪退导致系统提示15分钟进游戏，所以大乱斗没再开过

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

未进行具体的重复测试

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Hpero4** [comment]
@Fan-Bu-THU 

你好 感谢反馈. 

请问是lcu客户端闪退还是Seraphine闪退？

**Comment by Zzaphkiel** [comment]
疑似由于 LCU API 并发数量过大导致（已有诸多同原因的反馈），试一下[新版本](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.10.0)吧~
