### ISSUE TITLE
[BUG] tasklist 返回非零值报错

### ISSUE THREAD

**Issue by mhk7789** [Zzaphkiel/Seraphine#183]
### 问题描述

软件无法打开

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.9.2

### 客户端状态（若有）

正常开启，没进队列

### 复现方法（若有）

![1704188626141](https://github.com/Zzaphkiel/Seraphine/assets/155435178/edd715ae-9bb8-470c-8d23-f3415761fd4d)
程序打开提示“程序出现异常”相关代码无法复制，搜索之前的issue，排查发现
C:\Windows\System32\tasklist.exe运行正常，没有找到其它相关的issue，杀软防火墙等已关闭

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by tanshaobing** [comment]
我也出现了这样的情况

**Comment by Zzaphkiel** [comment]
@mhk7789 @tanshaobing 感谢反馈

打开客户端后，在终端运行
```
tasklist /FI "imagename eq LeagueClientUx.exe" /NH
```
试试看呢？

**Comment by tanshaobing** [comment]
![微信截图_20240102233803](https://github.com/Zzaphkiel/Seraphine/assets/76858800/0bc82e85-c505-4c55-84f2-2d22957ea635)
还是没有反应呢，双击打开也是同样报错。是我操作的有问题吗

**Comment by mhk7789** [comment]
> @mhk7789 @tanshaobing 感谢反馈
> 
> 打开客户端后，在终端运行
> 
> ```
> tasklist /FI "imagename eq LeagueClientUx.exe" /NH
> ```
> 
> 试试看呢？

感谢，已解决，是系统环境变量path少了C:\windows\system32\

**Comment by tanshaobing** [comment]
@mhk7789 老哥，你是怎么解决的，可以教教我吗

**Comment by Zzaphkiel** [comment]
@tanshaobing 如果方便的话可以提供一下您的报错截图嘛？

**Comment by tanshaobing** [comment]
@Zzaphkiel 和楼上大哥的情况一模一样
![微信截图_20240104201104](https://github.com/Zzaphkiel/Seraphine/assets/76858800/c200fb18-2400-476d-8ba3-afd16c272c54)

**Comment by Zzaphkiel** [comment]
@tanshaobing 方便运行仓库代码进行一下测试吗？我们这边无法复现您的问题，只能尝试修复一下看看效果 🥺

**Comment by tanshaobing** [comment]
@Zzaphkiel 不好意思哈，我不太懂编程这些，不会使用仓库代码运行软件

**Comment by Zzaphkiel** [comment]
@tanshaobing 等我们发布下个版本试一下吧 ~

**Comment by tanshaobing** [comment]
@Zzaphkiel 好的 期待谢谢

**Comment by Zzaphkiel** [comment]
@tanshaobing 尝试一下[新版本](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.10.0)，若仍存在问题请另开 issue 讨论~
