### ISSUE TITLE
[BUG] 程序出现异常😥

### ISSUE THREAD

**Issue by Viper373** [Zzaphkiel/Seraphine#184]
### 问题描述

程序出现异常😥
Traceback(most recent call last):
 File "app\lol\listener.py", line 38, in run
 File "app\lol\listener.py", line 15, in getLolProcessPid
ValueError: invalid literal for int() with base 10: b'code'

在尝试多次后，仍然每次都出现该错误，并且程序会无响应，同时，“确认并复制到剪贴板”按钮失效。
可能出现的问题方向：
①电脑从win10升级到win11
②语言设置中开启了Beta选项：Unicode提供全球语言支持（该选项开启后会使压缩包。例如zip rar 7z等解压后出现乱码），后续我关闭了该选项并重启电脑，仍然没有解决
还请作者大大帮忙解决，万分感谢！

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.9.2

### 客户端状态（若有）

房间内

### 复现方法（若有）

![屏幕截图 2024-01-03 205247](https://github.com/Zzaphkiel/Seraphine/assets/77206948/63b9b0f7-297e-4643-af26-2ed75eb3223b)

### 您进行游戏的服务器（若有）

黑色玫瑰

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈，仓库代码已经在 [`ad92f89`](https://github.com/Zzaphkiel/Seraphine/commit/ad92f893f159c1941bdea985d4f4ca0e589fde74) 中解决该问题（见 #174），下个发布的打包版本中也将修复该问题。

**Comment by Viper373** [comment]
感谢作者的回复，由于本人较懒（也已经很久没有动过terminal了哈哈哈），期待作者的下一个发布版本🥰
