### ISSUE TITLE
[Enhancement] 我感觉可以出一个黑名单功能

### ISSUE THREAD

**Issue by 00xiaoyang00** [Zzaphkiel/Seraphine#185]
### 功能描述

我感觉可以出一个黑名单功能，对局结束后拉黑队友或者对手并写下原因记录日期，下次又遇到了可以弹出提醒。
感觉蛮有意思的~

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈，关于黑名单功能之前已有讨论（见 #63、#163、#167），考虑到功能效果与使用场景，我们还是决定暂时不实现该功能，请您谅解 😘
