### ISSUE TITLE
[BUG] 进BP客户端就失效了。

### ISSUE THREAD

**Issue by chasiopen** [Zzaphkiel/Seraphine#186]
### 问题描述

大区影流
大厅界面一切正常，战绩也能查看。
但是一进排位BP，客户端直接卡死，什么也点不了。

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.9.2

### 客户端状态（若有）

英雄选择-蓝色方

### 您进行游戏的服务器（若有）

影流

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢反馈

1. 您指的是游戏客户端卡死了还是 Seraphine 卡死了？
2. 影流大区更新新的 ID 系统了吗？

**Comment by chasiopen** [comment]
1.是seraphine卡死
2.影流是前两天刚更新，目前还没有开启新ID，官方的说法是已经做好了准备。

具体说明如下：
1.启动游戏客户端后，刚打开seraphine，可以正常访问个人的对局，也可以查询其他玩家的对局（只是因为之前的更新对局记录只有更新后的）
2.排位匹配时可以看到软件标题显示匹配中
3.进入BP后，显示英雄选择-蓝色方/红色方，此时seraphine端彻底卡死。（之前可以直接看到队友的对局记录，现在则是无限加载，此时查看自己的信息也会卡住，seraphine客户端直接卡死，但不会影响lol游戏。）
此时如果在任务栏里右击退出软件，软件窗口会关闭，但是任务管理器当中依然有seraphine的进程，只有将此进程完全结束才能重新打开seraphine，然后就是依然卡死。

**Comment by chasiopen** [comment]
https://lol.qq.com/news/detail.shtml?docid=4651132936640476868

就是在这个更新之后，软件失效。

**Comment by chasiopen** [comment]
我尝试了客户端中【打开低配机器-总是关闭客户端】，【关闭低配机器-不关闭客户端】都会出现此问题。

**Comment by Hpero4** [comment]
@chasiopen 

你好

根据提供的信息, 影流大区应该已经实装riot id, 但未做显示.

Seraphine失效也是因此导致, 下一个发布版本会适配国服的riot id改动.

此外, 你可以通过以下举措确认当前所在大区有无实装riot id：
1. 商城无法购物、充值
2. 关闭新用户注册、转区
3. WeGame无法查询战绩

**Comment by chasiopen** [comment]
影流大区确实有这些举措，那就等软件更新了！
希望作者加速更新，感谢！

**Comment by Zzaphkiel** [comment]
[新版本](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.10.0)已发布，若仍存在该问题请另开 issue 进行反馈~
