### ISSUE TITLE
[Question] 提示链接不到github

### ISSUE THREAD

**Issue by Moonz13a** [Zzaphkiel/Seraphine#187]
### 问题描述

提示链接不到github

### 我已经查看了之前（包括已经关闭）的 issue，但这并不能解决我的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈

在打开自动更新选项时，软件开启的时候会访问 GitHub 来检查更新，这一过程可能受网络环境影响。您可以在设置中关闭自动检查更新功能 ~

**Comment by Porco97** [comment]
> 感谢您的反馈
> 
> 在打开自动更新选项时，软件开启的时候会访问 GitHub 来检查更新，这一过程可能受网络环境影响。您可以在设置中关闭自动检查更新功能 ~

我的网络一点问题没有，正常翻墙，包括uwp格式都可以正常翻，但每次打开必提示无法连接github
