### ISSUE TITLE
[Enhancement] 为什么不更新打包好的，打包好的BUG很多 很卡 而且进游戏不会自动加载战绩等等

### ISSUE THREAD

**Issue by Moonz13a** [Zzaphkiel/Seraphine#188]
### 功能描述

 为什么不更新打包好的，打包好的BUG很多 很卡 而且进游戏不会自动加载战绩等等

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by Zzaphkiel** [comment]
我们目前仅有两位开发者在业余时间维护项目，也是最近才抽出时间完成了针对客户端新 ID 系统相关代码的更新，这些新更新会在之后打包发布，也希望大家可以多一些体谅 😥

1. 关于您提到的 “BUG 很多，很卡”，可以具体描述一下吗？我们迄今为止的代码没有相关的更新，就算发布新的打包版本可能也不会解决您的问题。
2. 您提到的进游戏战绩不会自动加载可能是客户端 API 请求响应过慢导致的。虽然并发访问 API 可以加速这一过程，但有概率导致客户端直接闪退，目前仓库代码已经将并发数将 3 改为改为 2 了，我们认为加载的慢也比让客户端直接闪退好。

**Comment by Moonz13a** [comment]
软件很卡 加载不出来 不是加载慢 而且有时候自动接受对局也会失效 搜索其他人战绩也查不出来在转圈

**Comment by Hpero4** [comment]
@Moonz13a 

你好 请问你进行游戏的大区是？

**Comment by Moonz13a** [comment]
扭曲丛林

**Comment by Moonz13a** [comment]
可能我刚开电脑第一局可以加载队友战绩 然后进入游戏加载界面的时候点敌方 然后不会加载 然后后面再进行第二局 第三局 就队友也不会加载  敌方也不会加载

**Comment by Hpero4** [comment]
@Moonz13a 

你好 

可以参考一下 #186 看下是否是同样情况

**Comment by xiaolu88** [comment]
免费的，凑合用用就别挑挑拣拣的，B站上有几个更着更着就收费了

**Comment by xiaolu88** [comment]
现在每天晚上，电一也各种加载错误，盲猜是国服数据本身的问题

**Comment by Hpero4** [comment]
@xiaolu88 

你好 

感谢反馈, 请问电1近期是否有进行“跨区匹配前置准备”的停机维护？

如有, 异常大概率是因此导致.

如未进行过相关维护, 请提供更多信息以便我们更好的排查问题

谢谢！

**Comment by Zzaphkiel** [comment]
已发布新版，若问题仍存在请另开 issue 进行反馈
