### ISSUE TITLE
[Enhancement] 希望添加新功能上等马下等马一键查询发送，以及战绩查询在不登陆游戏的时候无法查询

### ISSUE THREAD

**Issue by ssincxv** [Zzaphkiel/Seraphine#189]
### 功能描述

如题

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈

1. 关于类似 “上等马” 等评级 / 评分以及一键喊话功能，之前已有过多次讨论 (见 #4、#12、#108、#115 等)，我们暂时不会实现该功能
2. 战绩查询功能基于 LCU API 提供，在没有登录 LOL 客户端时是没有办法调用这些 API 的，当然也没有办法查战绩了~
