### ISSUE TITLE
请问使用的打包命令是什么

### ISSUE THREAD

**Issue by leoFitz1024** [Zzaphkiel/Seraphine#19]
我这边给程序添加了一键喊话的功能，集成了lol-helper的部分功能，主要是你的软件有UI，切比较好看，所以想增强下功能，
准备打包测试好后发起合并请求。
不确定你那边用的打包工具是什么，可以在readme中说明下打包命令吗，也有利于后续更多人加入贡献

**Comment by Zzaphkiel** [comment]
感谢反馈！

1. 打包我使用的 `pyinstaller`，打包出 `exe` 后只保留 `app` 文件夹内所有资源文件与配置文件即可。我写了一个脚本，晚一些 push 上来。
1. 提出 PR 不用打包的，直接 PR 就好。
1. 目前非基于 LCU API （比如调用 Windows API）的功能 PR 可能暂时不会接受（如 #4），还请谅解 😥

**Comment by leoFitz1024** [comment]
打包是为了完整测试，哈哈。
这边一键喊话是模拟按键输入实现的，没有使用windows api
