### ISSUE TITLE
对局面板页面可以改下吗？每次看对局数据都很费劲[Enhancement] 

### ISSUE THREAD

**Issue by yingzishishen** [Zzaphkiel/Seraphine#191]
### 功能描述

![2](https://github.com/Zzaphkiel/Seraphine/assets/155925990/20855131-aa97-4612-8234-256c2538037c)
图片左边是另一个软件，就是这种对局面板能否把英雄头像放在战绩上面呢？这样一目了然不用去对照他们的ID就能看到每个人的数据情况。进游戏后显示敌方战绩建议都在一个面板方便查看，另一个软件就是在下方会显示敌方战绩，不然在游戏里想切屏看一眼战绩还要点击敌方和友方。软件很好用，希望能改进下，谢谢啦

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈。

关于对局信息界面布局，之前已有过多次讨论（见 #13、#25、#41），考虑到实现耗费的精力与效果，目前我们不会对该界面的布局做大幅度修改。

1. 目前该界面的召唤师显示的位置是按照**楼层顺序**或**游戏角色位置顺序**排列的，并且左边从上至下的顺序与右边从左至右的顺序是一样的。
2. 将双方放在一页的代价是每个召唤师的战绩数量无法展示这么多，页面总大小固定的情况下，什么样的布局都会有一定取舍的。

**Comment by yingzishishen** [comment]
双方战绩放到一个页面很好用啊，可以滚动看战绩，不用显示全部啊？你看另一个软件战绩的右边有那个滚动条的。一般看战绩都显示最近的五六局就差不多的，想看更多的战绩也可以滚动，或者点击ID进去查看想想的记录。只是建议下，改不了也没关系
