### ISSUE TITLE
[Enhancement] 集成 Loader 的部分功能

### ISSUE THREAD

**Issue by liu1999888** [Zzaphkiel/Seraphine#192]
### 功能描述

我在这个网站上搜到一款插件型工具，我觉得有些功能可以做到这个软件里，这可能会涉及到版权问题？不过都是免费使用的。
我觉得有用的功能有：
解锁好友生涯，偷好友的云顶偷分阵容非常有用，使用效果就是锁了和没锁一样可以直接客户端右键进入好友生涯，直接进入观战
乱斗锁英雄，显示乱斗模式英雄的增强削弱百分比的buff
一件秒退重登
其他的感觉锦上添花不实用
怕出现意想不到的bug我并没有与本软件共同使用过，我的想法是合并到一起使用会更加方便，因为第一个战绩查询用的就是这个，这个界面是太舒服了，用习惯了
那个插件型的工具叫Loader，机翻汉语叫企鹅装载机
偷个懒。我并没有看过已经关闭的问题，但是我勾了是

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈，关于您提到的 Loader，请问其有 GitHub 仓库吗？

**Comment by Zzaphkiel** [comment]
没看到有关 “解锁好友生涯” 等功能呀？有相关资料嘛？

**Comment by liu1999888** [comment]
https://wwof.lanzoul.com/ixMcG17194ad
这个是懒人包下载地址，别人打包好了框架和5个常用插件，类似与谷歌浏览器的篡改猴，给个通用框架，需要什么功能下载安装什么，插件都是全世界大佬自制的
https://github.com/LightningSw/TeamInsightX
这个是我认为的那个解锁好友生涯的插件，我看描述是这样的
https://discord.com/channels/1069483280438673418/1077886267464892468
这个是我下载插件的地方，很多小功能，不过全是外语，我是需要开浏览器翻译插件的

**Comment by liu1999888** [comment]
哦，还有主题，不过这上面的主题我觉得好丑，试用一个还增加了bgm，延长了登陆客户端的时间，我就没开过主题了，不过非常简单，不用像github上那些单独的主题一样麻烦，还要改文件，想恢复还要用wegame修复客户端，这里的主题和插件一样用，勾上就生效，不勾就不生效，重登就行，确实做的非常方便
https://discord.com/channels/1069483280438673418/1077886317364523072
这是我下载主题的地方，也有些奇奇怪怪的主题看介绍蛮有意思的，但是我嫌麻烦就没下，这些主题基本都会带好友列表那个位置透明，这个功能我感觉非常不错，不过我没有找到单独的插件
希望对作者能带来帮助，感谢作者提供好用又免费的软件

**Comment by Zzaphkiel** [comment]
@gitcss-pace @liu1999888 看了一下相关代码，它们所提供的功能实现方式与 Seraphine 不同（我们只调用 API 而不使用 hook），故我们暂时不会集成它们的相关功能 🥲

（好消息是它们应该与 Seraphine 没啥冲突，双开应该是可以的）

**Comment by liu1999888** [comment]
明白了，一直怕出现奇奇怪怪的的bug就不敢一起使用，现在不慌了
