### ISSUE TITLE
[BUG] 不关闭软件关闭电脑时 cmd.exe 报错

### ISSUE THREAD

**Issue by happyLiu97** [Zzaphkiel/Seraphine#193]
### 问题描述

Seraphine如果不关闭会导致导致关机的时候 弹出cmd.exe 应用程序错误 应用程序无法正常启动（0xc0000142）

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

v0.9.2

### 复现方法（若有）

只需要打开seraphine 软件关机就可以复现

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢反馈，抱歉回复较慢 😥

请问问题仍存在嘛？我在从 v0.9.2 至今的任何版本都无法复现您所提到的报错问题
