### ISSUE TITLE
[BUG] 开启软件导致客户端闪退

### ISSUE THREAD

**Issue by JackeyLov5** [Zzaphkiel/Seraphine#194]
### 问题描述

闪退 

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

v0.9.2

### 复现方法（若有）

最近开着seraphine 然后用wegame启动游戏。进入英雄选择界面会出现闪退问题，就点击接受然后客户端就会闪退，重新连接是直接进入bp，但是不能更换召唤师技能和符文随机情况，不开启seraphine 直接wegame启动就不会出现，或者不开启wegame也不会出现 希望大佬能解决一下 谢谢

### 出现率（若有）

每次这么做大部分时候会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Hpero4** [comment]
@JackeyLov5 

感谢反馈

该问题已经修复, 将在下版本中实装

**Comment by qq891534** [comment]
![22](https://github.com/Zzaphkiel/Seraphine/assets/74325172/4652ff8c-0492-4f7e-9e8f-147a83334023)
使用仓库代码运行seraphine也会偶尔出现该问题，并且都是在英雄选择阶段，不知是什么原因

**Comment by qq891534** [comment]
> @JackeyLov5
> 
> 感谢反馈
> 
> 该问题已经修复, 将在下版本中实装

**Comment by qq891534** [comment]
> @JackeyLov5
> 
> 感谢反馈
> 
> 该问题已经修复, 将在下版本中实装

以上

**Comment by Hpero4** [comment]
@qq891534 

你好, 感谢反馈, 

lcu闪退一般是由于请求量过大导致, 在 b835a01731042c1cca0ddc65675cce8010c138f1 中我们也修复了可能诱发问题的bug, 可以拉取最新代码再试试.

**Comment by dblqp** [comment]
这个闪退即使你不用这个软件，有时也会出现，应该是客户端bug
