### ISSUE TITLE
请问一下，什么时候可以打包新版本呢？[Question] 

### ISSUE THREAD

**Issue by SUZHIWAI** [Zzaphkiel/Seraphine#195]
### 问题描述

请问一下，什么时候可以打包新版本呢？没有打包怎样使用呢。

### 我已经查看了之前（包括已经关闭）的 issue，但这并不能解决我的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈。

1. 打包版本基本上是随缘发布的，若有影响使用的大 BUG 则会立即更新。
1. 仓库中的代码可以参考 readme 中的描述搭一下环境，下载代码后在环境中直接用 Python 运行~
