### ISSUE TITLE
[BUG]Seraphine程序中召唤师角色名称显示存在BUG

### ISSUE THREAD

**Issue by qq891534** [Zzaphkiel/Seraphine#196]
### 问题描述

0.10.0版本和0.92在战绩信息中对比显示如图，名称最后会出现框框[]
![123](https://github.com/Zzaphkiel/Seraphine/assets/74325172/cf97cd10-28d6-43dc-a634-192b08fbf6e8)
![1234](https://github.com/Zzaphkiel/Seraphine/assets/74325172/2ce0b51d-cd82-40ca-8501-eadcf07dde5f)

### 系统信息

Windows 11

### 运行方式

在 Python 环境中直接运行源代码

### 软件版本

0.9.2 and 0.10

### 客户端状态（若有）

房间中

### 复现方法（若有）

一直存在

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by qq891534** [comment]
![222222](https://github.com/Zzaphkiel/Seraphine/assets/74325172/b589a74b-e5f8-49c8-91b2-af6a16cacee4)

**Comment by Zzaphkiel** [comment]
感谢您的反馈，我们在 v0.10.0 中增加了对 **隐藏战绩的召唤师** 的提示（似乎您也隐藏了😋），它们的名字后面会被标注一个 emoji “🫣”，这个 emoji 似乎由于**字体**的原因无法显示，您可以尝试自行下载安装一下 “Segoe UI” 字体来解决这个问题
