### ISSUE TITLE
[BUG] 客户端api请求失败

### ISSUE THREAD

**Issue by chasiopen** [Zzaphkiel/Seraphine#197]
### 问题描述

可以正常查战绩，但是无法连接客户端。
最重要的对局信息无法出现。
直接上log了。

[Seraphine_2024-01-11_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/13902489/Seraphine_2024-01-11_ERROR.log)

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.10.0

### 您进行游戏的服务器（若有）

影流

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by 576255750** [comment]
我也是，显示api连接错误

**Comment by singleqaq** [comment]
好像之前的都可以但就是0.10.0一直打不开显示api连不上

**Comment by Zzaphkiel** [comment]
@chasiopen 感谢您的反馈

1. API 报错是尝试获取 **破损的秒表** （id：2424）以及 **探索者的护臂**（id：3191） 装备图标导致的。正常情况下 Seraphine 可以通过调用 LCU API 来获取这些图标资源，但是现在好像会出一些问题？应该与刚刚完成的英雄联盟 14.1 版本更新有关。这个报错应该不会影响到正常的使用吧？有强迫症同学的可以尝试自行下载缺少的图标资源，放在 `app/resource/game/item icons` 目录下，命名为 `{item_id}.png` ，如 `2424.png`（但我强烈建议不这么做）。
2. 经过测试，在影流大区（还未更新 ID 系统）和皮尔特沃夫大区（已更新 ID 系统）都无法复现您提到的 “对局信息界面加载不出来” 的情况，应该是当前服务器问题 🥲

@576255750 @singleqaq

若您提到的 “API 连接错误” 指的不是图标获取时的错误，请详细描述一下您遇到的问题（以及所在大区），并提供一下日志文件 🥺

**Comment by chasiopen** [comment]
1.报错的问题我了解了，就是无法获取itemicon的问题
2.主界面依然和#198一样，一直在转，无法看到个人信息以及生涯等界面。同时进入排位之后也无法看到队友的信息。
3.查询战绩输入id可以查询。
以下是截图，大区影流。
![image](https://github.com/Zzaphkiel/Seraphine/assets/35827956/4f97652f-aae7-4082-970d-cca991d0739f)

**Comment by singleqaq** [comment]
而且查的战绩截止在10号看不到1月11 的战绩，（艾欧尼亚）

**Comment by Zzaphkiel** [comment]
@chasiopen @singleqaq 英雄联盟服务器原因，与 Seraphine 本身以及其更新无关

**Comment by Zzaphkiel** [comment]
v0.10.1 暂时修复装备图标报错问题，可以前往 [这里](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.10.1) 进行下载。
