### ISSUE TITLE
更新后打不开且所有功能都用不了

### ISSUE THREAD

**Issue by singleqaq** [Zzaphkiel/Seraphine#198]
### 问题描述

![2024-01-11 (1)](https://github.com/Zzaphkiel/Seraphine/assets/148246534/245f6329-cd73-4602-9f41-8cabb46b474e)

说是客户端信息请求失败

### 我已经查看了之前（包括已经关闭）的 issue，但这并不能解决我的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢反馈，请问 0.9,2 存在这问题吗？

**Comment by Zzaphkiel** [comment]
感谢您的反馈。

经过测试发现 0.9.2 同样存在该问题（在清空本地游戏资源文件夹后），该问题由英雄联盟版本更新的导致。请尝试通过 https://github.com/Zzaphkiel/Seraphine/issues/197#issuecomment-1887011854 来解决您的问题。

**Comment by singleqaq** [comment]
0.9.2好用的
&nbsp;


Y
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月11日(星期四) 晚上8:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zzaphkiel/Seraphine] 更新后打不开且所有功能都用不了 (Issue #198)





 
感谢反馈，请问 0.9,2 存在这问题吗？

**Comment by Zzaphkiel** [comment]
在**清空本地游戏资源文件夹**后 0.9.2 同样存在该问题，报错**并不是由于 Seraphine 更新版本**导致的。您可以选择

1. 参考 https://github.com/Zzaphkiel/Seraphine/issues/197#issuecomment-1887011854 尝试解决您的问题。
2. 暂时使用 0.9.2 版本

**Comment by Zzaphkiel** [comment]
v0.10.1 已暂时修复该问题，您可以前往 [这里](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.10.1) 进行下载。
