### ISSUE TITLE
[Question] Tasklist.exe不可用

### ISSUE THREAD

**Issue by tanshaobing** [Zzaphkiel/Seraphine#199]
### 问题描述

双击打开应用程序直接显示【tasklist.exe】不可用，请问我可以怎样解决他呢
![Uploading 批注 2024-01-11 232621.png…]()

### 我已经查看了之前（包括已经关闭）的 issue，但这并不能解决我的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
> 同上，wmi正在运行，自动，打开软件报错为 tasklist.exe不可用

@tanshaobing @Sprite0821 下版本预计实现手动连接功能，不依赖 tasklist 来判断游戏是否启动，（虽然会牺牲一点方便）

**Comment by Zzaphkiel** [comment]
[`b04c1aa`](https://github.com/Zzaphkiel/Seraphine/commit/b04c1aaaaab52e242ef279499b02c983c5dfefaf) 已实现该功能，对于 Tasklist 不可用的用户，现在可以通过手动点击连接按钮进行与客户端的连接。

该特性将随下个打包版本上线
