### ISSUE TITLE
有强制观战的功能吗

### ISSUE THREAD

**Issue by YXCQU** [Zzaphkiel/Seraphine#2]
之前看别人做过这个功能（付费的好像），可以输入ID 就可以观战了，现在游戏的观战功能一直不可用

**Comment by Zzaphkiel** [comment]
没了解过这个，有什么资料可以看一下的嘛？

**Comment by Zzaphkiel** [comment]
查了一圈，好像 LCU API 没有提供相关功能？Riot API 则需要申请 key。有什么已知的实现了这个功能的程序嘛？

**Comment by YXCQU** [comment]
https://tik.doii.cc/  这个对战助手收费的，注册后可以免费体验几天，有观战功能

**Comment by Zzaphkiel** [comment]
已实现同大区观战功能，跨大区的观战要使用 Riot API，暂时不会实现~
