### ISSUE TITLE
报错Unhandled exception in script

### ISSUE THREAD

**Issue by RicharYe** [Zzaphkiel/Seraphine#20]
![$ _ATM6GK W 95MG COC{S0](https://github.com/Zzaphkiel/Seraphine/assets/129949451/3c9acbf9-456f-4c86-a9a7-ce83bf030ef5)

无法打开客户端，然后设置为打开软件后自动启动客户端就出现该报错。

**Comment by Zzaphkiel** [comment]
感谢反馈，现已修复此问题
