### ISSUE TITLE
[BUG] 关于11日客户端更新后seraphine 部分功能出现问题汇总

### ISSUE THREAD

**Issue by inthis9** [Zzaphkiel/Seraphine#200]
### 问题描述

1：查询好友战绩提示：API getltemlcon: KeyError(3191)
![微信图片_20240111233054](https://github.com/Zzaphkiel/Seraphine/assets/156336462/7a26ebb9-8b5a-4e47-809f-b66316de9856)

2:   部分好友战绩查询 与 wegama查询有出入，页面只显示部分,（见附图）
![微信图片_20240111233231](https://github.com/Zzaphkiel/Seraphine/assets/156336462/825ebcd7-e80e-4c3b-bb9e-7b4e702a9cf4)

![微信图片_20240111233541](https://github.com/Zzaphkiel/Seraphine/assets/156336462/2ee5c3ab-7aa0-496c-8395-5322ee7f271e)

3：战绩查询提示：API getltemlcon: KeyError(2424)
![微信图片_20240111233541-怕【】】as](https://github.com/Zzaphkiel/Seraphine/assets/156336462/df53616e-2c58-47a8-8727-ea3e40aeba38)

![image](https://github.com/Zzaphkiel/Seraphine/assets/156336462/96cb0c1d-c0bc-4a2c-aec0-cd567d817bd4)

4：对局信息功能无法使用

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.10.0

### 客户端状态（若有）

大厅待机 未排队

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈，关于您提到的问题之前（就在今天）已有诸多讨论，并已得出结论。

1. 报错原因见 #197，解决方法见 https://github.com/Zzaphkiel/Seraphine/issues/197#issuecomment-1887011854 。
2. 英雄联盟客户端接口工作不正常，属英雄联盟服务器问题，与 Seraphine 以及其版本更新无关 （见 #197）。
3. 同 1。
4. 同 2。

**Comment by Zzaphkiel** [comment]
v0.10.1 暂时修复装备图标问题，可以前往 [这里](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.10.1) 进行下载 ~
