### ISSUE TITLE
(#197)更新之后可以打包一下吗？[Question] 

### ISSUE THREAD

**Issue by SUZHIWAI** [Zzaphkiel/Seraphine#201]
### 问题描述

找不到装备图标时使用默认装备图标 (#197)；这个可以打包一下吗？现在用不了Seraphine

### 我已经查看了之前（包括已经关闭）的 issue，但这并不能解决我的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈，现已发布 v.0.10.1，请前往 [这里](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.10.1) 进行下载。
