### ISSUE TITLE
[BUG] 艾欧尼亚大区查战绩接口失效

### ISSUE THREAD

**Issue by BelugaCc** [Zzaphkiel/Seraphine#203]
### 问题描述

<img width="416" alt="图片1" src="https://github.com/Zzaphkiel/Seraphine/assets/156444922/504a9115-a20b-4a69-836c-e0cbf8678eb6">

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.10.1

### 客户端状态（若有）

等待界面，游戏界面都会存在

### 复现方法（若有）

下载打开之后就一直这样

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by BelugaCc** [comment]
无法查看任何对局信息，个人信息

**Comment by Zzaphkiel** [comment]
感谢反馈，正如报错内容所说，Seraphine 使用的查战绩接口暂时无法使用，为艾欧尼亚大区服务器原因所致。

**Comment by kissgo** [comment]
> 感谢反馈，正如报错内容所说，Seraphine 使用的查战绩接口暂时无法使用，为艾欧尼亚大区服务器原因所致。

你好，电信三区诺克萨斯也出现相同的情况

**Comment by xiaolu88** [comment]
![{8AF94482-EA4A-4897-A612-365EDD24598E}](https://github.com/Zzaphkiel/Seraphine/assets/98731439/90f59dc3-1584-45b1-9880-36fa4820e1b2)
是不是这个啊

**Comment by Zzaphkiel** [comment]
@xiaolu88 是

**Comment by Opmilk** [comment]
电一服务器问题，客户端生涯页面的战绩也看不了

**Comment by xiaolu88** [comment]
wegame也看不到战绩，而且匹配系统也乱了，白金黑铁乱匹

**Comment by xiaomingzzzzz** [comment]
现在还是经常发生这件事 请问依然是服务器原因吗

**Comment by Zzaphkiel** [comment]
> 现在还是经常发生这件事 请问依然是服务器原因吗

@xiaomingzzzzz 应该是，因为至少网二没这个问题

**Comment by qaz62362870** [comment]
一样的问题，现在大乱斗都看不到了
