### ISSUE TITLE
[BUG] __onGoingSwap 函数报错

### ISSUE THREAD

**Issue by singleqaq** [Zzaphkiel/Seraphine#204]
### 问题描述

Traceback (most recent call last):
  File "app\view\main_window.py", line 925, in __onGoingSwap
KeyError: 'summoners'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\view\main_window.py", line 936, in __onGoingSwap
UnboundLocalError: local variable 'tmp' referenced before assignment

![2024-01-12](https://github.com/Zzaphkiel/Seraphine/assets/148246534/2553469a-96b5-4fe6-b106-4fcb52a8d060)

### 我已经查看了之前（包括已经关闭）的 issue，但这并不能解决我的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢反馈，请问可以提供一下游戏大区、问题复现过程以及日志文件吗？

**Comment by singleqaq** [comment]
[Uploading Seraphine_2024-01-12_ERROR.log…]()

**Comment by Zzaphkiel** [comment]
@singleqaq 这个 log 似乎没有上传成功？还有希望可以提供一下复现过程以及游戏大区~

**Comment by KaguraNanaq** [comment]
@Zzaphkiel 我也遇到了这个情况，黑色玫瑰区的，进游戏时看不到队友以及对面战绩。
![seraphine](https://github.com/Zzaphkiel/Seraphine/assets/140292911/1c75dc84-01f1-44b5-9f23-132ec63f96f1)

![seraphine2](https://github.com/Zzaphkiel/Seraphine/assets/140292911/d2846576-5683-4eb8-862a-bc0993808c85)

**Comment by Zzaphkiel** [comment]
@KaguraNanaq 请问问题仍存在吗？

**Comment by KaguraNanaq** [comment]
@Zzaphkiel 虽然还会有问题，但通过新增的刷新按钮已经可以解决了

**Comment by KaguraNanaq** [comment]
@Zzaphkiel 现在会有新开一局但查战绩界面还在上局的情况，但是可以通过刷新解决
