### ISSUE TITLE
[Question] 关于项目打包成.exe文件

### ISSUE THREAD

**Issue by lengyingmofeng** [Zzaphkiel/Seraphine#206]
### 问题描述

我没有7z改成了bandizip打包，运行出现下面这种情况，怎么解决？
![image](https://github.com/Zzaphkiel/Seraphine/assets/62734268/c8bab38a-a5c2-43ca-8c10-176f538e5580)

### 我已经查看了之前（包括已经关闭）的 issue，但这并不能解决我的问题

- [x] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈

1. 您可以选择不生成压缩文件（只需稍微修改一下 `make.ps1` 脚本）
2. 或您可以自行参考 Bandizip 的[官方文档](https://cn.bandisoft.com/bandizip/help/parameter/)来解决您的问题。

**Comment by Hpero4** [comment]
@lengyingmofeng 

现版本的make脚本可以使用 -dbg 参数来跳过压缩流程.

pack结果生成在./dict下
