### ISSUE TITLE
对局信息偶尔会无法加载显示

### ISSUE THREAD

**Issue by qq891534** [Zzaphkiel/Seraphine#208]
### 问题描述

从队列中进入英雄选择界面，如果Seraphine不是停留在对局信息界面而是停在其他功能页，对局信息有时会无法加载出来，完全退出程序后再打开会正常显示（也有加载不出来的时候）。这种情况经常出现，出现的频率还会比较高。
目前是北京时间凌晨1点47，服务器应该是属于正常状态，游戏内也可以正常查看排位记录，切查询其他玩家对局信息。再次5分钟之前，也出现了上述情况。

### 我已经查看了之前（包括已经关闭）的 issue，但这并不能解决我的问题

- [X] 是

**Comment by qq891534** [comment]
![QQ图片20240115015426](https://github.com/Zzaphkiel/Seraphine/assets/74325172/839a8e11-4721-4ea5-908a-5768792ef0b9)

**Comment by Hpero4** [comment]
@qq891534 

感谢反馈

能否提供下log, 在Seraphine目录下

**Comment by qq891534** [comment]
辛苦~
[Seraphine_2024-01-12_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/13932654/Seraphine_2024-01-12_ERROR.log)
[Seraphine_2024-01-13_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/13932656/Seraphine_2024-01-13_ERROR.log)
[Seraphine_2024-01-14_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/13932657/Seraphine_2024-01-14_ERROR.log)

**Comment by qq891534** [comment]
![2222](https://github.com/Zzaphkiel/Seraphine/assets/74325172/5a0d6231-518e-4972-a49b-19839621681e)

可以使用Seraphine查询队友战绩，但对局信息还是无法正常显示

**Comment by Hpero4** [comment]
@qq891534 

请问 你是用的seraphine版本是?

**Comment by qq891534** [comment]
> @qq891534
> 
> 请问 你使用的seraphine版本是?

0.10.1

**Comment by Hpero4** [comment]
@qq891534 

在设置页面关闭 "排位过滤" 功能再试下

该问题由 b835a01731042c1cca0ddc65675cce8010c138f1 引发, 与昨日的提交 a647a086621dfcf852a94f67d120ee015e9c5507 中修复, 因此release版本0.10.1中应该存在该BUG, 现象与你的描述一致.

**Comment by Zzaphkiel** [comment]
[v0.10.2](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.10.2) 已修复该问题
