### ISSUE TITLE
[Enhancement] 关于对局详情的段位显示

### ISSUE THREAD

**Issue by swRains** [Zzaphkiel/Seraphine#209]
### 功能描述

目前的段位显示是当前段位显示，但在赛季初，这对双方实力判断不太有参考价值，我期望能否多一行上赛季段位，最高段位，以及对过去多个赛季的加权段位

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈，个人感觉对局信息界面目前已经足够紧凑，放不下更多的信息了，考虑到实现效果与意义还是决定暂时不加入更多信息的展示，还请谅解 ~
