### ISSUE TITLE
Windows Security报告有木马病毒？

### ISSUE THREAD

**Issue by chaosink** [Zzaphkiel/Seraphine#21]
![image](https://github.com/Zzaphkiel/Seraphine/assets/6009211/e7b126ed-2c22-4015-a47a-9237c36c3dcd)

真的是安全的吗？
应该没事吧？

**Comment by Zzaphkiel** [comment]
我这不报毒啊 🥺 要不您重新去 [release](https://github.com/Zzaphkiel/Seraphine/releases/latest) 下载一个试试？

实在害怕的话可以 clone 仓库到本地直接运行，毕竟代码里写了什么不是一目了然嘛~
