### ISSUE TITLE
[BUG] 生涯对局分路显示错误

### ISSUE THREAD

**Issue by Lingling-LynnChan** [Zzaphkiel/Seraphine#211]
### 问题描述

在查看生涯时，发现对局记录中单双排显示的分路与实际分路不符。

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.10.1

### 客户端状态（若有）

正常运行

### 复现方法（若有）

只需启动软件，点进个人生涯即可复现，重启软件仍无法显示正确分路

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈。

分路信息由 LCU API 提供，其不准确的现象当初加入该信息时已经被注意到了（见 #120），只是一直都没有更好的解决方案 😥
