### ISSUE TITLE
[Enhancement] 利用大数据判断玩家性别

### ISSUE THREAD

**Issue by Yuki-mua** [Zzaphkiel/Seraphine#212]
### 功能描述

我希望可以根据玩家使用软辅助的使用频率来判断是否为妹妹，方便我加好友哈哈

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈哈~

您的想法确实很有 ~娱乐~ 建设意义 😄，但要做到准确的判断可能需要一些更多的工作（必须训练个模型？），这里我们还是不实现您所提到的功能了，可能您的主观判断比程序判断的更为准确 😋
