### ISSUE TITLE
[Question] 软件打开

### ISSUE THREAD

**Issue by buynonsense** [Zzaphkiel/Seraphine#213]
### 问题描述

![image](https://github.com/Zzaphkiel/Seraphine/assets/97596221/b2c315ed-6787-4ed7-b2f0-aaddc4ebaba9)
是什么问题呢？

### 我已经查看了之前（包括已经关闭）的 issue，但这并不能解决我的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈，可以详细描述一下问题并提供一下 Seraphine 版本、游戏大区以及日志文件吗？

**Comment by buynonsense** [comment]
我发现自己手动设置的游戏目录，无法通过这个来启动游戏。 而且软件的功能必须要登录游戏客户端才启动。 如果我只是想查个战绩，并不想登录游戏，或者这个电脑没有安装游戏就不行了

**Comment by Hpero4** [comment]
@buynonsense 

Hi!

感谢反馈, 运行LOL客户端是Seraphine查询战绩(或其他功能)的前置条件, 

因为这部分功能本身就源自LOL客户端, Seraphine只是对其进行了二次封装.
