### ISSUE TITLE
[BUG] 客户端信息请求失败

### ISSUE THREAD

**Issue by ECO-eco** [Zzaphkiel/Seraphine#214]
### 问题描述

<img width="647" alt="微信图片_20240121201253" src="https://github.com/Zzaphkiel/Seraphine/assets/76828465/9f76e167-3afb-4789-a1f4-d3532653cc0d">
启动lol客户端之后就提示这个，然后一直转圈圈。

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

v0.10.1

### 复现方法（若有）

启动客户端就报错。

### 日志文件

[Seraphine_2024-01-21_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/14001281/Seraphine_2024-01-21_ERROR.log)

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Hpero4** [comment]
@ECO-eco 

感谢反馈

请问是否开启了代理？

在进入游戏时, 客户端是否需要排队？
