### ISSUE TITLE
建议对局信息添加开黑车队展示

### ISSUE THREAD

**Issue by wei6718189** [Zzaphkiel/Seraphine#216]
### 功能描述

比如对局信息展示我方和对方时候，哪些人是一起开黑的。
1、5个ID昵称下标分别是12345、则五个人都是路人 。 
2、5个ID昵称下标分别11222.说明下标是“1”的两个人是一起的开黑的、 下标是“2”三个人时一起开黑
3、5个ID昵称如果是11111 。说明是5黑。

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by wei6718189** [comment]
另外提议就是，对局信息展示的时候，输的局备注是不是发起投降的。可以展示万家最近对局心态是不是动不动就想点投降，我觉得挺有意思的。不知道接口
![Uploading 建议1.png…]()
是不是有这些字段。

**Comment by wei6718189** [comment]
![建议1](https://github.com/Zzaphkiel/Seraphine/assets/16144847/3bda0958-9604-41cb-9575-4d5699483a6f)
类似这样的备注

**Comment by Zzaphkiel** [comment]
感谢反馈。

1. 现在的玩家背景颜色就是您所想的数字 “1”、“2”、“3”。
2. 如您所见，目前的布局已经没有位置放 “投降” 的标记了。
![QQ截图20240124192142](https://github.com/Zzaphkiel/Seraphine/assets/60383222/f043f583-e1b6-4678-8f32-31ac43c3e0ae)

**Comment by wei6718189** [comment]
.感谢你您的回答，
您说背景颜色是指 ID昵称的名字吗？
图片显示黄色框是开黑的，但是ID颜色并没有变，都是白色。
![敌方png](https://github.com/Zzaphkiel/Seraphine/assets/16144847/b51a74d6-f056-46b8-ad86-79bbb7fd67dc)![我方](https://github.com/Zzaphkiel/Seraphine/assets/16144847/1861a069-c1f0-4057-8028-416f8e4b5cb6)

**Comment by Hpero4** [comment]
Hi @wei6718189 

关于你的疑问回答如下

1. 预组队的显示在左侧的面板, 黄色背景的玩家是“开黑”的, 若还有一队, 则会标记为粉色. 并且, 将鼠标悬停在上面, 会展示预组队队伍中所有人的ID.

2. 预组队数据来源于客户端本身, 不存在逻辑上的错误, 一般也不会误判. 关于提到的有些 对局没有, 可能是因为该状态在进入游戏后（读条）才能够获得并展示, bp阶段没有.

3. 目前主要开发者只有2位, 若您有好的想法, 欢迎pr！

4. ID的颜色用于标记上一盘遇到的玩; 若某一名玩家与你一同进行了上一局游戏, 他的id会被标记成红色（对面）或绿色（队友）, 鼠标悬停在id上能看到其上一盘使用的英雄.
