### ISSUE TITLE
[Question] 能否查询好友的在线状态？

### ISSUE THREAD

**Issue by JohnnieWind** [Zzaphkiel/Seraphine#217]
### 问题描述

这个功能有计划实现吗？

### 我已经查看了之前（包括已经关闭）的 issue，但这并不能解决我的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈，请问该功能的意义是什么呢 🥺？

**Comment by JohnnieWind** [comment]
> 感谢您的反馈，请问该功能的意义是什么呢 🥺？

haha，目前来看是我的个人场景，有时想知道有没有好友上线游玩，想到基于lcu api，是否能够获得这项数据？

**Comment by Zzaphkiel** [comment]
> > 感谢您的反馈，请问该功能的意义是什么呢 🥺？
> 
> haha，目前来看是我的个人场景，有时想知道有没有好友上线游玩，想到基于lcu api，是否能够获得这项数据？

我们目前的功能都是只能在**客户端打开**时使用的，直接看好友列表不是更方便嘛？
