### ISSUE TITLE
[BUG] 第一次进入游戏后无法自动获取客户端状态，导致对局信息不刷新

### ISSUE THREAD

**Issue by qweretsd** [Zzaphkiel/Seraphine#218]
### 问题描述

14.2更新之后，在一把打完之后，再匹配下一轮的时候无法自动接收。手动进入房间也无法读取队友信息

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.10.1

### 客户端状态（若有）

匹配

### 复现方法（若有）

重启后，
先打开客户端再打开萨勒芬妮
第一次仍然可以自动接受匹配邀请
结束之后
在第二次弹出邀请时，无法自动接受。
且进入房间时，无法读取队友信息

### 日志文件

文件夹中今日日志显示为空白

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by qweretsd** [comment]
该问题在重启萨勒芬妮后会重置到第一局接受之前，然后第二局仍旧无法接受

**Comment by Zzaphkiel** [comment]
感谢您的反馈，经过测试发现是 LOL 客户端 `/lol-gameflow/v1/gameflow-phase` 接口的 websocket 订阅在昨天的版本更新后出现问题，导致 Seraphine 无法实时更新客户端状态，与 “自动接收对局” 功能并无关系，该问题的修复还请耐心等待。

在这期间，您可暂时手动重启 Seraphine 来获取双方对局信息 😥

**Comment by wow233** [comment]
我也有同样的问题，期待修复哥

**Comment by Zzaphkiel** [comment]
[v0.10.2](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.10.2) 加入了刷新状态功能，点击该按钮可以重新与客户端进行状态同步。
