### ISSUE TITLE
使用0.9.2被封号了

### ISSUE THREAD

**Issue by singleqaq** [Zzaphkiel/Seraphine#219]
### 问题描述

![image](https://github.com/Zzaphkiel/Seraphine/assets/148246534/319fdef7-2db1-4aef-96ea-9d5fb6ce1b91)

### 我已经查看了之前（包括已经关闭）的 issue，但这并不能解决我的问题

- [X] 是

**Comment by Hpero4** [comment]
@singleqaq 

你好 感谢反馈

截至目前暂未收到过指向Seraphine的集中性封号反馈. 

我们会密切关注此类问题, 当出现疑似Seraphine导致封号时, 我们会对所有使用者进行通知. 

若就此有问题任何进一步发现欢迎随时反馈~
