### ISSUE TITLE
想问一下下大佬~能否增加云顶之弈战绩查询功能？

### ISSUE THREAD

**Issue by MarRole** [Zzaphkiel/Seraphine#22]
因为现在在全网搜索好像并没有能够查询云顶之弈战绩的方法，这个是否可以实现？
最后谢谢大佬！给大家带来了很大的便利！十分感谢！~

**Comment by Zzaphkiel** [comment]
感谢支持与建议！

关于云顶之弈战绩是否要支持查询之前已经讨论很多次了（见 #4、#9、#16），由于个人精力原因，暂时不会实现云顶之弈相关的功能，但欢迎云顶之弈相关功能的 pr。
