### ISSUE TITLE
[BUG] 当前对局信息不显示

### ISSUE THREAD

**Issue by TonwiR** [Zzaphkiel/Seraphine#221]
### 问题描述

只有打开程序游戏第一把显示当前对局信息，之后就不显示了，自己接受对局也没用

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

v0.101

### 客户端状态（若有）

队列中 游戏中

### 出现率（若有）

每次这么做大部分时候会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈，我们已定位该问题，请访问 #218 来获取相关进展。
