### ISSUE TITLE
[Question] 最新一次更新后，可能会被LOL检测出来

### ISSUE THREAD

**Issue by Gexiaolungg** [Zzaphkiel/Seraphine#222]
### 问题描述

首先阐明我在此没有怪作者或者软件的意思，刚刚被封了一个小时，腾讯游戏安全中心说是存在违规行为，可能是软件被监测到了

### 我已经查看了之前（包括已经关闭）的 issue，但这并不能解决我的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈。

Seraphine 不含任何对客户端以及游戏本体的内存读取或破坏其完整性的行为，也遵守[《<英雄联盟>游戏插件公约》](https://lol.qq.com/webplat/info/news_version3/152/4579/4581/m3106/201509/381618.shtml)对 “绿色功能” 的定义。但同时，由于国服运营对于该类软件的封号判定规则较为模糊，还请大家酌情使用 😥
