### ISSUE TITLE
[BUG] 2024.01.27更新之后自动同意对局失效

### ISSUE THREAD

**Issue by handsomekai** [Zzaphkiel/Seraphine#223]
### 问题描述

更新之后自动同意对局失效，对局信息只有第一把有效，会一直卡在第一把游戏中

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.10.1

### 客户端状态（若有）

游戏中

### 您进行游戏的服务器（若有）

黑玫

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢反馈，和 #218 重复了，请移步 #218 关注相关进展
