### ISSUE TITLE
[BUG] 对局信息不显示

### ISSUE THREAD

**Issue by cool1319** [Zzaphkiel/Seraphine#224]
### 问题描述

如题所示 匹配进入后点击对局信息进去什么都没有，无论是哪方的战绩都看不到

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.10.1

### 客户端状态（若有）

所有时间

### 日志文件

[Seraphine_2024-01-26_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/14071117/Seraphine_2024-01-26_ERROR.log)
[Seraphine_2024-01-27_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/14071119/Seraphine_2024-01-27_ERROR.log)

### 您进行游戏的服务器（若有）

德玛西亚

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈，目前我无法复现该问题，请问该问题仍存在吗？

**Comment by cool1319** [comment]
哎 换了最新版本也是不显示

**Comment by Zzaphkiel** [comment]
@cool1319 是只有打开软件后的第一局会显示还是全部都不显示？

**Comment by longyi995661393** [comment]
> @cool1319 是只有打开软件后的第一局会显示还是全部都不显示？

使用的最新的版本就是这样  第一局正常 后面就不正常了

**Comment by Zzaphkiel** [comment]
@longyi995661393 英雄联盟 14.2 版本更新之后的新 BUG，目前需要在每一局游戏结束后点击左侧**刷新状态**按钮，才能让下一句的对局信息界面正常显示。

**Comment by Zzaphkiel** [comment]
47b1a9b 已修复该问题。
