### ISSUE TITLE
[BUG] 概率会卡掉游戏小队语音

### ISSUE THREAD

**Issue by AyaHuLi** [Zzaphkiel/Seraphine#225]
### 问题描述

偶尔和朋友新开一把游戏，这个会直接把客户端卡掉，就剩下游戏窗口，然后语音也掉了，打完这一局就会重启。不用这个软件就不会出现这种情况。还有一个是，点击接受对局，准备进入选英雄界面，然后突然闪退，要重启游戏又会进入选英雄界面，而且这个不算秒，不知道是什么原因。设置了win10开机自启动

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

9.2-10.0都出现过

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

差不多一半的情况会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈，我们之前已经知道该问题的存在（见 #158、#182、#194 等），我们怀疑是由于 LCU API 并发访问量过大导致的（虽然现在只有 2 了）。

~针对该问题的修复还没有什么头绪 🥲~
