### ISSUE TITLE
[BUG] 只有第一次打开软件对局信息才加载，后面都不加载对局信息

### ISSUE THREAD

**Issue by riveovo** [Zzaphkiel/Seraphine#226]
### 问题描述

[BUG] 只有第一次打开软件对局信息才加载，后面都不加载对局信息，只卡在第一局的对局信息

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.10.1

### 客户端状态（若有）

所有状态

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢反馈。我们正在尝试修复该问题，在这期间您可以手动重启 Seraphine 来获取对局信息。

（和 #218 重复了，请移步 #218 关注相关进展）
