### ISSUE TITLE
[BUG] 仓库最新代码版本无法运行

### ISSUE THREAD

**Issue by qq891534** [Zzaphkiel/Seraphine#228]
### 问题描述

克隆了最新版本代码，但程序一直打不开，卡在如图所示位置

### 系统信息

Windows 11

### 运行方式

在 Python 环境中直接运行源代码

### 软件版本

0.10

### 客户端状态（若有）

选择英雄

### 复现方法（若有）

![QQ图片20240127213919](https://github.com/Zzaphkiel/Seraphine/assets/74325172/77506cd6-4a2c-4046-987e-2d4fa7a079c7)

### 日志文件

- [ ] 
[Seraphine_2024-01-27_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/14072443/Seraphine_2024-01-27_ERROR.log)

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢反馈，重新配置一下环境试试看呢？我们更新了 UI 组件库的依赖版本
