### ISSUE TITLE
[BUG] 自动接受失败

### ISSUE THREAD

**Issue by wqdraf2** [Zzaphkiel/Seraphine#230]
### 问题描述

自动接受失败 不管什么延迟都要手动按接受

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.102

### 客户端状态（若有）

排队中

### 复现方法（若有）

开游戏排队 等接受弹出来

### 日志文件

[Seraphine_2024-01-28_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/14079647/Seraphine_2024-01-28_ERROR.log)

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

每次这么做都必定会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢反馈。

由于英雄联盟 14.2 之后的新 BUG，Seraphine 会随机地与客户端失去同步，导致 Seraphine 无法获得客户端的状态（比如在需要匹配确认时不知道要接受匹配），您需要**在房间或匹配时手动点击左侧导航栏中的刷新状态按钮**，让 Seraphine 重新获取客户端的状态（此时窗口标题栏会提示房间组队中或匹配中），这样自动接受功能就可以正确工作了。
