### ISSUE TITLE
[Question] v10.2打包后无法正常运行

### ISSUE THREAD

**Issue by MoeLightOvO** [Zzaphkiel/Seraphine#232]
### 问题描述

你好，我在使用make.ps1脚本打包后生成的压缩文件 解压之后并不能正常运行 但用python main.py可以正常运行 这是为什么

### 我已经查看了之前（包括已经关闭）的 issue，但这并不能解决我的问题

- [X] 是

**Comment by MoeLightOvO** [comment]
已解决 将app文件夹拷贝至_internal文件夹下即可正常使用

**Comment by Zzaphkiel** [comment]
使用 6.0.0 版本以下的 pyinstaller 将不生成 `_internal` 文件夹（如 `readme.md` 中的 5.13），此时脚本生成的可执行程序可以正常使用~

**Comment by MoeLightOvO** [comment]
好的 谢谢！我用默认版本的pyinstaller会报错 pathlib不兼容 但实际上我没有安装pathlib库 所以就把pyinstaller升级了一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月31日(周三) 下午4:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Zzaphkiel/Seraphine] [Question] v10.2打包后无法正常运行 (Issue #232)




 
使用 6.0.0 版本以下的 pyinstaller 将不生成 _internal 文件夹（如 readme.md 中的 5.13），此时脚本生成的可执行程序可以正常使用~
