### ISSUE TITLE
[BUG] 游戏ID显示异常

### ISSUE THREAD

**Issue by duzhor** [Zzaphkiel/Seraphine#233]
### 问题描述

近期使用改名卡修改过ID。侧边栏设置上方的游戏ID显示正确，生涯页面和战绩查询页面的游戏ID后多一个方框特殊符号。

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

v0.10.2

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

未进行具体的重复测试

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢反馈，因**缺少字体**导致该问题，详情见 #196
