### ISSUE TITLE
增加添加好友功能

### ISSUE THREAD

**Issue by Reksai01** [Zzaphkiel/Seraphine#234]
### 功能描述

目前客户端存在bug，通过ID无法添加好友（之前是重复添加几次即可），能否增加添加好友功能？

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的反馈，经过测试发现好友请求接口 `/lol-chat/v1/friend-requests` 目前不可用的样子（会 404），我们可能暂时无法实现该功能 😭
