### ISSUE TITLE
[Question]  101.qq.com的符文装备数据有什么接口获取吗？

### ISSUE THREAD

**Issue by httpsColon** [Zzaphkiel/Seraphine#235]
### 问题描述

疼讯应该做了js加密

### 我已经查看了之前（包括已经关闭）的 issue，但这并不能解决我的问题

- [X] 是

**Comment by httpsColon** [comment]
opgg我这好像被墙了。。。

**Comment by Zzaphkiel** [comment]
目前我们还没怎么开始做这块的内容 🥺，相关进展可以查看一下 #10

**Comment by Ninohana** [comment]
# GET
https://lol.qq.com/act/lbp/common/guides/champDetail/champDetail_[英雄ID].js
