### ISSUE TITLE
[BUG] 在选英雄的时候刷新对局信息有概率导致游戏闪退

### ISSUE THREAD

**Issue by Jiuxia0823** [Zzaphkiel/Seraphine#236]
### 问题描述

在选择英雄时进行对局信息刷新会导致游戏闪退

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.10.2

### 客户端状态（若有）

选择英雄

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

非常低的概率会出现

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢反馈。

我们怀疑是并发 API 访问导致的该问题（见 #158、#182、#194），我们预计在下版本中提供设置项让用户自行决定 API 并发数量。

**Comment by Zzaphkiel** [comment]
> 感谢反馈。
> 
> 我们怀疑是并发 API 访问导致的该问题（见 #158、#182、#194），我们预计在下版本中提供设置项让用户自行决定 API 并发数量。

40dae24 已实现该特性。
