### ISSUE TITLE
游戏结束后游戏客户端出现bug

### ISSUE THREAD

**Issue by DevilYee** [Zzaphkiel/Seraphine#237]

**Comment by Zzaphkiel** [comment]
请详细描述您能的问题 😥

**Comment by DevilYee** [comment]
后台挂着seraphine玩一盘lol之后，lol客户端就变透明了，只显示一小块，只能重启lol才行，每局都这样。

**Comment by DevilYee** [comment]
> 请按照 BUG report 模板详细描述您的问题 😥

助手没出现bug，但是挂着助手玩游戏lol端有bug。

后台挂着seraphine玩一盘lol之后，lol客户端就变透明了，只显示一小块，只能重启lol才行，每局都这样。

**Comment by Zzaphkiel** [comment]
> 后台挂着seraphine玩一盘lol之后，lol客户端就变透明了，只显示一小块，只能重启lol才行，每局都这样。

这是英雄联盟**客户端 BUG**，与 Seraphine 无关。

您可以选择尝试：

1. 在客户端设置中关闭 **偏好 DX9 传统模式** 选项；
2. 或当客户端出现该问题时，使用 Seraphine 辅助功能中的 **修复客户端窗口** 功能来修复客户端。

**Comment by DevilYee** [comment]
> > 后台挂着seraphine玩一盘lol之后，lol客户端就变透明了，只显示一小块，只能重启lol才行，每局都这样。
> 
> 
> 
> 这是英雄联盟**客户端 BUG**，与 Seraphine 无关。
> 
> 
> 
> 您可以选择尝试：
> 
> 
> 
> 1. 在客户端设置中关闭 **偏好 DX9 传统模式** 选项；
> 
> 2. 或当客户端出现该问题时，使用 Seraphine 辅助功能中的 **修复客户端窗口** 功能来修复客户端。

感谢，可能是网吧的问题。
