### ISSUE TITLE
[Question] 一直卡在这个界面

### ISSUE THREAD

**Issue by Ninohana** [Zzaphkiel/Seraphine#238]
### 问题描述

![image](https://github.com/Zzaphkiel/Seraphine/assets/71210982/5d553306-6997-46f0-b99a-71f11ca6aa43)

### 我已经查看了之前（包括已经关闭）的 issue，但这并不能解决我的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢反馈。麻烦提供一下运行程序的方式（exe 还是运行的代码）、环境信息以及日志文件 🥺

**Comment by Ninohana** [comment]
# 环境

win11 x64 conda

# 运行方式

代码

![image](https://github.com/Zzaphkiel/Seraphine/assets/71210982/ab6fdae5-0aa8-4d64-a822-c55715b1d9af)

# 备注

日志不知道怎么看，之前可以正常运行的，git pull了之后就这样了

**Comment by Zzaphkiel** [comment]
@Ninohana `pip install -r requirements.txt` 更新一下依赖~
