### ISSUE TITLE
[Question] （电脑安装了Net 7后自动接受对局经常失效）

### ISSUE THREAD

**Issue by Yoogt** [Zzaphkiel/Seraphine#239]
### 问题描述

为了用BetterGI，给电脑安装了Net 7（NET SDK 7.0.405（x64））后自动接受对局经常失效，只会在开电脑后的第一局生效

### 我已经查看了之前（包括已经关闭）的 issue，但这并不能解决我的问题

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢反馈，解决方法见 #218，仓库代码已修复该问题。
