### ISSUE TITLE
出现了这个问题请问怎么解决

### ISSUE THREAD

**Issue by BruceAllenCS** [Zzaphkiel/Seraphine#24]
<img width="338" alt="1694175199598" src="https://github.com/Zzaphkiel/Seraphine/assets/93517646/b5b1eb7c-50d0-4ec0-a90a-e87a7819954c">

**Comment by Zzaphkiel** [comment]
感谢反馈。

请问是打开程序之后会稳定触发的问题吗？我这里没法复现这个问题呢 😥
