### ISSUE TITLE
Enhancement （删去左右圆括号，并在此处简要描述功能）

### ISSUE THREAD

**Issue by tlqiqiqi** [Zzaphkiel/Seraphine#242]
### 功能描述

开发组您好，现在LOL的ID后面增加了数字（比如：ID#123），所以像以前一样查玩家ID查不到了，需要有ID+数字才能查，请开发组考虑下是否更新查找ID功能，十分感谢。

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by tlqiqiqi** [comment]
追加——ID能看与我对局的玩家ID，不能查对局以外的玩家ID，比如别的服务器或朋友的

**Comment by Zzaphkiel** [comment]
感谢反馈。

由于我们的所有功能均基于 LCU API 实现，现有条件不足以我们实现**不通过完整名字 + 数字 ID 查询召唤师**的功能（以及查询其他服务器），故我们暂时无法实现该特性 🥺。
