### ISSUE TITLE
[Enhancement] 希望能软件客户端热更新

### ISSUE THREAD

**Issue by chasiopen** [Zzaphkiel/Seraphine#243]
### 功能描述

每次更新都要删掉重新下载，希望能热更新或者原路径自动安装。

### 我已经查看了之前（包括已经关闭）的 issue，但并没有与我相同的建议

- [X] 是

**Comment by Zzaphkiel** [comment]
感谢您的建议，我们将逐步实现更新功能（软件内下载 + 替换旧版本文件）

**Comment by Zzaphkiel** [comment]
6b5062c 已实现该功能
