### ISSUE TITLE
[BUG] 全区封号一小时

### ISSUE THREAD

**Issue by Dashaguo** [Zzaphkiel/Seraphine#246]
### 问题描述

今天两个号排位选人时陆续被强制登出，被全区封号1小时，腾讯游戏安全中心都给出相同理由：游戏行为异常

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.10.3

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

未进行具体的重复测试

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
感谢反馈。关于封号问题之前已有很多讨论（见 #64、#104、#153、#180、#219、#222 等），使用 Seraphine 前请自行权衡斟酌。
