### ISSUE TITLE
[Enhancement] 自动删除客户端部分文件功能

### ISSUE THREAD

**Issue by rno0n** [Zzaphkiel/Seraphine#248]
### 功能描述

能否考虑加入启动客户端的时候清除内置cross，wegame，TenioDL，FeedBack这样的功能。

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
感谢反馈。

> 删除内置 cross，wegame，TenioDL，FeedBack

关于这项操作有什么参考嘛？

**Comment by Ninohana** [comment]
what's it for?

**Comment by rno0n** [comment]
> 感谢反馈。
> 
> > 删除内置 cross，wegame，TenioDL，FeedBack
> 
> 关于这项操作有什么参考嘛？

清理额外文件可以让游戏变的流畅，TenioDL，FeedBack，还有内置加速器会在后台偷偷扫盘。

**Comment by Zzaphkiel** [comment]
对客户端文件进行操作比较*危险*，故我们暂不会实现该功能 🥺

~删文件写个 bat 不就可以了嘛？~
