### ISSUE TITLE
战绩显示界面的一点小建议

### ISSUE THREAD

**Issue by MZY1995** [Zzaphkiel/Seraphine#25]
![RbmRRYDqMA](https://github.com/Zzaphkiel/Seraphine/assets/144452488/2880e39a-f5cf-49cb-9a6b-529d093756bd)
战绩显示查询能否做成图片这个样子，刚刚注册的这个，我是编程小白，如果有冒犯或者建议不合理请不要在意。
非常感谢作者制作的这个便民小工具，谢谢。

**Comment by MZY1995** [comment]
还有就是能否生涯显示里加上大乱斗的场次和胜率，像我这种玩家就是只玩大乱斗的，峡谷匹配排位不打

**Comment by Zzaphkiel** [comment]
感谢反馈！

1. 没太看懂您的意思，是把左边的这个战绩预览部分做成现在的五倍大小嘛？这样做的话，右边显示对局详细信息的位置就被压缩了呀？
2. 其实我最初也挺想显示的，但目前 LCU API 并不支持查大乱斗（以及匹配模式和其他特殊模式）的总场次以及胜场；甚至在查别人的时候，排位模式的总场次也是查不到的，所以目前没办法显示其他人（甚至包括自己）的大乱斗场次和胜率~

**Comment by MZY1995** [comment]
感谢回复
1.本意是想在一页内看到更多的战绩，现在想想确实没什么必要，您就当我胡言乱语吧
2.原来如此，我就说不应该没乱斗吗。
不知做单局内数据统计的难度如何，比如伤转，kda，承伤，参团率这类关键数据

**Comment by Zzaphkiel** [comment]
这些数据都很好计算，只是它们没地方放了（放进去的话整个窗口要宽很多），所以没做

**Comment by 824348454** [comment]
借主题问一下，状态改成离线是真的看不到了还是只是伪装的

**Comment by Zzaphkiel** [comment]
> 借主题问一下，状态改成离线是真的看不到了还是只是伪装的

@824348454 建议新开 issue 哦~

改成离线状态后，在游戏大厅时，其他人看自己的状态就是离线的
