### ISSUE TITLE
[BUG] 云顶双人模式时对局信息展示异常

### ISSUE THREAD

**Issue by Ninohana** [Zzaphkiel/Seraphine#251]
### 问题描述

![image](https://github.com/Zzaphkiel/Seraphine/assets/71210982/2b61e5ed-f55f-4fca-b0a8-c31479a6bb24)

### 系统信息

Windows 11

### 运行方式

在 Python 环境中直接运行源代码

### 软件版本

0.10.3

### 出现率（若有）

未进行具体的重复测试

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
感谢反馈。

云顶之弈时客户端也会有 `ChampSelect` 状态导致这一问题，目前通过判断召唤师数量修复了 🥲
