### ISSUE TITLE
[Question]  杀毒软件报木马

### ISSUE THREAD

**Issue by Kuronekooo** [Zzaphkiel/Seraphine#252]
### 问题描述

请问一打开exe，就报木马拦截是因为什么原因，直接不用360吗

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Ninohana** [comment]
添加信任即可，不过每次更新可能需要重新添加。使用时可以将360暂时关闭，卸载也未尝不可。
