### ISSUE TITLE
[Enhancement] 实现用户自定义胜利/失败卡片的颜色

### ISSUE THREAD

**Issue by i11421** [Zzaphkiel/Seraphine#254]
### 问题描述

我是色弱，红绿有点难分辨，十分感谢！![NN }E60 XX%QEC(}T2A2V%A](https://github.com/Zzaphkiel/Seraphine/assets/161206100/eae1f19c-64ab-4378-aa0c-0dae67474ab2)

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
很有意义的建议！我们会在下版本中实现用户对 **胜利 / 失败自定义颜色** 的功能

**Comment by Zzaphkiel** [comment]
[`7bb97b1`](https://github.com/Zzaphkiel/Seraphine/commit/7bb97b1205e6c3904903bb123fc2e186631fe5ee) 已实现该特性，其将随下个打包版本上线

**Comment by i11421** [comment]
辛苦了，感谢！
