### ISSUE TITLE
[BUG] 观战无法进入一直加载

### ISSUE THREAD

**Issue by maker2524211** [Zzaphkiel/Seraphine#256]
### 问题描述

观战无法进入一直加载

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.103

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
应该是 LOL 观战服务器的问题～
