### ISSUE TITLE
[Enhancement] 修复无限转圈功能怎么没有了

### ISSUE THREAD

**Issue by yukiSign** [Zzaphkiel/Seraphine#257]
### 功能描述

如题，在最新版的程序中，没有【修复无限转圈】的功能了，旧版本上是有的。能不能加回来。下图1是旧版本0.10.2上的功能截图
![QQ截图20240228014022](https://github.com/Zzaphkiel/Seraphine/assets/31638756/4328487a-9bd7-48ed-97be-e30036b3946c)

图2是最新版本的功能截图，版本0.10.3
![图2](https://github.com/Zzaphkiel/Seraphine/assets/31638756/bfb329f4-9c8a-47c8-a700-d128dd1b0d44)

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Ninohana** [comment]
移到了这里

![image](https://github.com/Zzaphkiel/Seraphine/assets/71210982/cce62136-83ff-47b6-8743-0a6e9aae4a78)
