### ISSUE TITLE
[Question] 没有自动禁英雄的功能

### ISSUE THREAD

**Issue by Elysium6364** [Zzaphkiel/Seraphine#260]
### 问题描述

没有自动禁英雄的功能
![QQ截图20240301112712](https://github.com/Zzaphkiel/Seraphine/assets/161793248/b2387906-9bbd-43c6-8866-8f97cc8e4280)

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
仓库版本已实现该功能，打包版本将随下个发布上线～
