### ISSUE TITLE
[Enhancement] 大区显示功能

### ISSUE THREAD

**Issue by az4325899** [Zzaphkiel/Seraphine#263]
### 功能描述

希望能在查询战绩页面添加一个显示该玩家大区的功能 比如图上面的这样
![微信图片_20240303195708](https://github.com/Zzaphkiel/Seraphine/assets/33874782/7d998a3c-2867-4f50-959f-06e166ef6494)

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
感谢反馈~

1. 请问显示它意义是什么呢？因为我们只能查同大区的战绩呀
2. 显示在启动页（左侧导航栏第一个界面）可以嘛？目前这个界面感觉放哪都不是很好看

**Comment by az4325899** [comment]
lol不是有部分大区合区了嘛，假设在联盟一区排位的话，里面是分很多小区的，如图
![image](https://github.com/Zzaphkiel/Seraphine/assets/33874782/fb304fbf-fbdf-42a9-9e67-b92aea8be933)
查战绩的时候能显示大区的话更方便查看，如果能在显示战绩页面显示哪个区的话也是可以的
![image](https://github.com/Zzaphkiel/Seraphine/assets/33874782/d6ee857a-21dc-4e81-bd3e-e94e77f9dd39)
就像这样

**Comment by Zzaphkiel** [comment]
有道理哈，不过可能我们还需要调查一下能不能获得召唤师的所在大区数据～

**Comment by longyi995661393** [comment]
今天电信区的跨区全部打通了，看了其他几款战绩查询的页面是可以显示出来是哪个大区的了
![Uploading Snipaste_2024-03-12_23-40-09.png…]()

**Comment by longyi995661393** [comment]
![Snipaste_2024-03-12_23-40-09](https://github.com/Zzaphkiel/Seraphine/assets/158059884/c7e0be02-27e1-4200-8168-feba953e3190)
今天电信区的跨区全部打通了，看了其他几款战绩查询的页面是可以显示出来是哪个大区的了

**Comment by longyi995661393** [comment]
> @longyi995661393 可否提供一下相关软件名字？

https://lol.lzyumi.top/
是一个网站 您可以去看看

**Comment by Zzaphkiel** [comment]
@longyi995661393 @az4325899 暂时不知道从哪里可以得到玩家的**原大区**信息，我们现有的接口只能拿到新的大区信息（合区之后的）🥹
