### ISSUE TITLE
[Enhancement] （希望能注明队友/对方是否为组队）

### ISSUE THREAD

**Issue by Asahey** [Zzaphkiel/Seraphine#264]
### 功能描述

虽然可以查看对方战绩大致判断是否为组队，但是希望可以增添自动识别对方近几场次是否重合的功能

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
见 https://github.com/Zzaphkiel/Seraphine/issues/216#issuecomment-1911243119
