### ISSUE TITLE
[Question] 艾欧尼亚大区无法查询战绩

### ISSUE THREAD

**Issue by RO6351** [Zzaphkiel/Seraphine#265]
### 问题描述

![QQ截图20240305135806](https://github.com/Zzaphkiel/Seraphine/assets/162279339/806f129c-de9e-4de1-80d2-8427a980fa20)

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
请问您开代理了吗？关闭代理试试呢？

**Comment by RO6351** [comment]
还真是，解决了，谢谢大佬
