### ISSUE TITLE
第一次接触python

### ISSUE THREAD

**Issue by Mynameisfwk** [Zzaphkiel/Seraphine#268]
### 问题描述

宝塔直接配置文件就可以了么 需要装环境么

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
需要 `conda` 创建虚拟环境，在虚拟环境中安装依赖包，之后就可以克隆代码运行了~

**Comment by Zzaphkiel** [comment]
#267
