### ISSUE TITLE
直接崩溃  点击那个最近队友 然后点进去就崩溃

### ISSUE THREAD

**Issue by wdfeng456n** [Zzaphkiel/Seraphine#269]
### 问题描述

Traceback (most recent call last):
  File "app\view\career_interface.py", line 364, in __onCareerInfoChanged
KeyError: 'tagLine'

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.10.3

### 客户端状态（若有）

大厅

### 日志文件

[Seraphine_2024-03-06_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/14500374/Seraphine_2024-03-06_ERROR.log)

### 您进行游戏的服务器（若有）

暗影岛

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
感谢反馈，仓库代码已在 bb36b68 修复该问题，将在下个版本上线。

~导致该问题的原因是因为一个单词拼错了~
