### ISSUE TITLE
Enhancement （删去左右圆括号，并在此处简要描述功能）

### ISSUE THREAD

**Issue by tlqiqiqi** [Zzaphkiel/Seraphine#270]
### 功能描述

关于观战功能解释：
1、观战功能必须要有LOL更新后ID后缀的#****数字才能观战，直接用老版本ID是不识别的
2、若你在排队房间内是无法观战的，软件右上角会出现《玩家不在游戏内的提示》，退到大厅后就可以使用此功能观战，观战功能是正常可以使用的。
3、不要使用OPGG下载的录像以及方法，把录像文件放到游戏目录下运行，这样会导致观战功能无法正常在被使用（黑屏或黑屏概率增加）
本人亲测，希望开发组今后遇到同样的问题以这个为最终答复！

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
感谢🙏

**Comment by tlqiqiqi** [comment]
追加
4、跨区观战需要你登陆指定玩家大区才能观战，现版本有的大区只有ID没有后缀（比如：比尔吉沃特），所以，没有ID后缀的大区观战功能不需要ID后缀也能观战。

**Comment by tlqiqiqi** [comment]
追加
5、进入观战时，如有黑屏加载的情况请多试几次（开发组说观战功能是基于观战服务器链路生成的，所以要看观战服务器当时的网络状况而定）。
如果进入双方读取界面说明可成功观战，卡顿属正常现象，不用理会延迟是否是零，多等一会就能进入。
其实观战系统跟你回放游戏录像是一样的，也需要读取时间，快慢取决于观战服务器的网络状况和你的PC性能。
