### ISSUE TITLE
文件路径找不到

### ISSUE THREAD

**Issue by huizhiye** [Zzaphkiel/Seraphine#271]
### 问题描述

在网吧使用的时候，无法找到正确的文件路径，我是通过wegame顺网专版启动，
![IMG_20240308_014949](https://github.com/Zzaphkiel/Seraphine/assets/86034038/944652f1-83d4-4a3d-8319-d8174ef9ba05)
![Uploading IMG_20240308_015410.jpg…]()

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
这个路径是在客户端第一次启动之后才会被自动设置的，在 Seraphine 第一次打开的时候，它默认显示自己的路径而不是客户端的路径。

请问您是指它在客户端启动之后仍然显示不正确的路径吗？

**Comment by huizhiye** [comment]
这一次使用的时候，可以自动显示正确路径的：先开软件，再开客服端。
第二次，关了以后，无论先开辅助还是客服端，都显示文件路径失败。在网吧换机子也没用。
第一次用的是旧版本，眼看旧版不行，我就去网站上下载你的最新版使用，还是这样。
我在电脑上将英雄联盟所在文件夹打开，和再软件上打开，软件上显示不了启动程序这些。
我明天再去那个网吧试试。

Zaphkiel ***@***.***> 于 2024年3月8日周五 14:17写道：

**Comment by huizhiye** [comment]
要不，远程电脑屏幕控制，你看看。毕竟是网吧电脑，需要约个时间

Jonathan Davis ***@***.***> 于 2024年3月10日周日 02:43写道：

**Comment by huizhiye** [comment]
对的，在客服端启动以后，任然不显示正确路径

Jonathan Davis ***@***.***> 于 2024年3月10日周日 13:16写道：

**Comment by Zzaphkiel** [comment]
可能是由于网吧电脑比较特殊的原因导致该问题（游戏文件并不是保存在真的本地），不过这个路径不正确并不影响功能的使用吧？

**Comment by huizhiye** [comment]
不行，搜战绩都不行

Zaphkiel ***@***.***> 于 2024年3月10日周日 16:10写道：

**Comment by Zzaphkiel** [comment]
是搜的时候会报错，还是压根连接不上客户端？
