### ISSUE TITLE
[Enhancement] 能否实现在多开客户端的情况下切换使用

### ISSUE THREAD

**Issue by longyi995661393** [Zzaphkiel/Seraphine#273]
### 功能描述

首先描述我自身的使用情况：
日常多开两个客户端，Seraphine软件只会识别到第一个登录的账号使用
例如我第一个登录的是A号，第二个登录的是B号
Seraphine软件只会识别到A号
并且一切功能以A号为主

这个时候我如果想要Seraphine软件识别到B号的话
这个时候就得关闭Seraphine软件和两个客户端
然后第一个去登录B号 第二个去登录A号
这样Seraphine软件就识别到了B号

我希望能够在不退出多开客户端并且重新上号的情况下
让Seraphine软件可以在多开客户端的情况下去切换各个LOL客户端使用

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
感谢反馈哈，感觉理论上是能实现无缝切换的。

但我们还是想知道您是如何双开客户端的？我们就算实现这个功能了也测试不了呀

**Comment by longyi995661393** [comment]
> 感谢反馈哈，感觉理论上是能实现无缝切换的。
> 
> 但我们还是想知道您是如何双开客户端的？我们就算实现这个功能了也测试不了呀



> 感谢反馈哈，感觉理论上是能实现无缝切换的。
> 
> 但我们还是想知道您是如何双开客户端的？我们就算实现这个功能了也测试不了呀

好的，给您介绍下如何双开客户端
将整个LOL文件夹数据
复制到另一个分区
然后在【英雄联盟\TCLS\Client.exe】
启动这个原始登陆器 
进行游戏登录 即可双开
如果分区够多
每个分区盘都复制一份
可以进行三开 四开 五开

**Comment by longyi995661393** [comment]
> 感谢反馈哈，感觉理论上是能实现无缝切换的。
> 
> 但我们还是想知道您是如何双开客户端的？我们就算实现这个功能了也测试不了呀

该功能我个人使用意愿比较强烈
我愿意免费给您提供可以实现双开客户端的主机供您远程测试使用

**Comment by longyi995661393** [comment]
> 了解了，感谢。我自己先试试哈～

好的 麻烦您了。期待您的消息，如果有需要帮忙测试的地方，可以随时联系我！

**Comment by Zzaphkiel** [comment]
[`8aaafae`](https://github.com/Zzaphkiel/Seraphine/commit/8aaafaed0c81cbd749ee8108ddfc974f481451ab) 已实现该功能。

![2](https://github.com/Zzaphkiel/Seraphine/assets/60383222/34efd3b5-7eef-4360-ac25-5d9a59a77185)

**Comment by longyi995661393** [comment]
不是很了解如何使用 
 是需要等待您发布成品吗？
还是需要我自己操作？

**Comment by Zzaphkiel** [comment]
仓库代码已实现该特性，打包好的程序将随下个发布上线，还请耐心等待

**Comment by longyi995661393** [comment]
> 仓库代码已实现该特性，打包好的程序将随下个发布上线，还请耐心等待

感谢！希望早点发布！很想快点用上，另外有没有您个人的捐赠赞助途径？

**Comment by Zzaphkiel** [comment]
暂无接受赞助的途径，感谢支持！

**Comment by longyi995661393** [comment]
大佬 您的10.4版本 啥时候能发布 很着急用这个切换客户端的功能 
每天都在不断地重复上下号o(╥﹏╥)o

**Comment by Zzaphkiel** [comment]
我们还在研究大区显示和卸头像框能不能一并上线了，大概这周之内能发

**Comment by longyi995661393** [comment]
卸载头像框我这边有可以使用的软件，需要给您发一份吗
说不定可以给你点作用

**Comment by Zzaphkiel** [comment]
不需要了，已经实现了，感谢🙏
