### ISSUE TITLE
跨区匹配功能已经上线，请求大佬加入在生涯页面加入所在大区显示

### ISSUE THREAD

**Issue by coldmountein** [Zzaphkiel/Seraphine#275]
### 功能描述

跨区匹配功能已经上线，实测目前工具是能够查到其他区的玩家的要是能在对局信息里面显示就好了

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
感谢建议。

和 #263 重复了，相关进展可以关注一下 #263 的讨论。
