### ISSUE TITLE
我设置了离线状态，但是马上就又变成在线了。很难受

### ISSUE THREAD

**Issue by ZMNUTT63000** [Zzaphkiel/Seraphine#279]
### 问题描述

我设置了离线状态，但是马上就又变成在线了。很难受

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

v0.11.0

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
无法复现该问题 😥
![QQ截图20240316155307](https://github.com/Zzaphkiel/Seraphine/assets/60383222/863ef31d-05bb-4028-8ef9-02379d83aff0)

经过测试，该离线状态仅在大厅待机时可用；进入房间或进入游戏后，状态改变是正常现象。

**Comment by ZMNUTT63000** [comment]
那后续更新可以一直保持离线状态吗。

**Comment by Zzaphkiel** [comment]
> 那后续更新可以一直保持离线状态吗。

应该实现不了，受到使用接口的限制，进入房间之后，即使继续手动设置，也是会显示在房间的状态的 😭
