### ISSUE TITLE
对局队友信息历史记录

### ISSUE THREAD

**Issue by ZMNUTT63000** [Zzaphkiel/Seraphine#280]
### 功能描述

每次进入游戏都可以看到队友的信息，但是一旦游戏结束或者有人秒退的时候，这些记录就没办法回访了，希望可以添加一个最近的历史记录查看的功能。

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
感谢反馈，这个看秒掉的游戏的队友是有什么具体使用场景或者意义嘛？

**Comment by ZMNUTT63000** [comment]
有的时候可能是出于好奇，就啥都想看看

**Comment by Zzaphkiel** [comment]
实现起来有点复杂了，意义感觉也不是特别大，还是不实现了吧 🥹？
