### ISSUE TITLE
[建议] 关于自动选择英雄功能

### ISSUE THREAD

**Issue by qq891534** [Zzaphkiel/Seraphine#283]
### 功能描述

一、建议能够自动预选，否则有可能会被队友禁用。二、建议预选后能够有延迟自动确认选择功能，以便于能够根据阵容更换选择英雄。

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Ninohana** [comment]
上述功能不是已经实现了吗？如果有与你预期不符的情况发生请提交bug并且尽可能详细地描述复现步骤。

> PS：可能需要检查是否与最新仓库版本一致
