### ISSUE TITLE
[BUG] Seraphine程序崩溃

### ISSUE THREAD

**Issue by qq891534** [Zzaphkiel/Seraphine#284]
### 问题描述

在英雄选择确认完毕到加载界面过程中，Seraphine有概率会出现崩溃情况，在游戏结束后，游戏也会直接闪退。

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.11.0

### 客户端状态（若有）

选择英雄到加载界面过程

### 复现方法（若有）

概率出现，今天就出现了两回。在之前使用代码运行也会出现这种情况

### 日志文件

[Seraphine_2024-03-16_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/14623937/Seraphine_2024-03-16_ERROR.log)
![111](https://github.com/Zzaphkiel/Seraphine/assets/74325172/fe7bf67b-5474-4542-885d-bf5825b6d185)

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

非常低的概率会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
和 #277 一样吗？

**Comment by qq891534** [comment]
> 和 #277 一样吗？

看起来是的
