### ISSUE TITLE
[BUG] 自动更新易被杀毒软件拦截

### ISSUE THREAD

**Issue by swRains** [Zzaphkiel/Seraphine#285]
### 问题描述

今天使用了新增的自动更新功能，但是因为使用的是cmd，频频被360拦截，导致了更新失败，相信其他软件也是相同的问题。

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.11.1

### 出现率（若有）

未进行具体的重复测试

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by swRains** [comment]
此外，建议软件更新添加个默认系统代理

**Comment by Zzaphkiel** [comment]
感谢反馈。

1. 更新时的 bat 被 360 拦截可能暂时没有什么好办法
2. `v0.11.1` 版本已将下载源改为 Gitee，应该以后用不上代理了
