### ISSUE TITLE
[BUG] variable 'win' referenced before assignment

### ISSUE THREAD

**Issue by Zzaphkiel** [Zzaphkiel/Seraphine#286]
![Snipaste_2024-03-17_19-41-54](https://github.com/Zzaphkiel/Seraphine/assets/158059884/332f53b1-f9ca-4f64-b879-3ed9355dc07a)

> @qq891534 暂时无法复现该问题

刚刚我也出现了这个问题

_Originally posted by @longyi995661393 in https://github.com/Zzaphkiel/Seraphine/issues/277#issuecomment-2002430808_

**Comment by Zzaphkiel** [comment]
@longyi995661393 可以描述一下怎么复现该问题吗（或者怎么遇到的）？您遇到的和原 issue 中其他人遇到的不一样

**Comment by longyi995661393** [comment]
> @longyi995661393 可以描述一下怎么复现该问题吗（或者怎么遇到的）？您的问题和原 issue 中其他人遇到的不一样

属于偶发性的，高强度使用了一天，目前就出现了一次这个情况

**Comment by longyi995661393** [comment]
> @longyi995661393 可以描述一下怎么复现该问题吗（或者怎么遇到的）？您的问题和原 issue 中其他人遇到的不一样

链接：https://pan.baidu.com/s/1Agv3nX5cl67mglzjzDfyaw 
提取码：1234 
请麻烦观看下这个视频，刚刚复现操作把这个弹窗又复现出来了

**Comment by longyi995661393** [comment]
基本上可以确定：
多开客户端之后，打开Seraphine软件，识别到A号之后无任何操作立马切换链接到B号
然后不停的查几次战绩，就会报错这个弹窗。

**Comment by longyi995661393** [comment]
链接：https://pan.baidu.com/s/1QDC168FsZCvNjeQj-57wLA 
提取码：1234 
麻烦请观察这第二个报错视频
这个视频是没有进行任何切号动作的前提下 进行了几次查询战绩
也出现了这个报错提醒

**Comment by Zzaphkiel** [comment]
感谢，我去排查一下

**Comment by longyi995661393** [comment]
还发现一种情况
多开客户端的情况下
在对局详情中点击某个人的战绩跳转到搜索页面查询时
会出现假死情况
随即软件未响应
只能强行关闭软件重新打开

**Comment by longyi995661393** [comment]
> > 链接：https://pan.baidu.com/s/1944w3MMp8wCQb7X8dF5-9Q 提取码：1234 麻烦请观看一下这第三个报错的BUG 出现假死的情况的报错
> 
> 收到了，我找时间排查一下吧，最近太忙了 🥺，暂时先操作软件的时候慢点吧~

好的 辛苦啦

**Comment by Hpero4** [comment]
#332 应该修复了相关问题, 可以多开客户端测试下

**Comment by longyi995661393** [comment]
> #332 应该修复了相关问题, 可以多开客户端测试下

是否需要等待0.11.2版本更新了 才能测试呢

**Comment by Hpero4** [comment]
@longyi995661393 是的, 或者从当前源码构建

**Comment by longyi995661393** [comment]
> @longyi995661393 是的, 或者从当前源码构建

太久没更新了  不知道下次更新是什么时候呢

**Comment by Zzaphkiel** [comment]
[v0.12.0](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.12.0) 已修复该问题。
