### ISSUE TITLE
[Question] no OPENSSL_Applink

### ISSUE THREAD

**Issue by hxlg4ever** [Zzaphkiel/Seraphine#287]
### 问题描述

![微信图片_20240318030548](https://github.com/Zzaphkiel/Seraphine/assets/41727075/bb2b7764-7350-43b7-90ac-b5faa6e59ac8)

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
看一下 [这个](https://blog.csdn.net/qq_17328759/article/details/127802435) 呢？应该是和代码没啥关系的 😥

**Comment by lg266** [comment]
感谢

**Comment by Zzaphkiel** [comment]
> 感谢

问题解决了吗？

**Comment by lg266** [comment]
是的
