### ISSUE TITLE
[Enhancement] 增加去除主页黄点功能

### ISSUE THREAD

**Issue by kkplmao** [Zzaphkiel/Seraphine#288]
### 功能描述

客户端主页那个云顶按钮总有一个黄点，点一下就消失，希望可以增加自动点击以消除黄点

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
感谢反馈哈，考虑到实用性和实现难度，暂无实现该特性的计划 🥹
