### ISSUE TITLE
[BUG] （更新后自动开启客户端功能失效）

### ISSUE THREAD

**Issue by RicharYe** [Zzaphkiel/Seraphine#291]
### 问题描述

![76UAT_VZ`)L4X))MLNV%`JK](https://github.com/Zzaphkiel/Seraphine/assets/129949451/2a23dd69-22d8-4d46-b8c1-bdf74afa0511)
之前版本软件打开软件这样设置都能自动打开游戏客户端，这次更新了之后该功能无法生效。

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.11.1

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by RicharYe** [comment]
可以在软件内手动启动，不是游戏路径问题。

**Comment by Zzaphkiel** [comment]
感谢反馈！

刚在 [`55900b8`](https://github.com/Zzaphkiel/Seraphine/commit/55900b89df770901fb92d841d3d0f425740eb567) 修复了该问题 🥺

~之前为了实现多开客户端重构了部分代码，这个功能的代码忘记加回来了😱😱~
