### ISSUE TITLE
[Question] （默认对局数量最大只有60能不能更大）

### ISSUE THREAD

**Issue by yukiSign** [Zzaphkiel/Seraphine#292]
### 问题描述

如题，设置中【默认对局数量】，也就是在个人生涯界面中显示的最大对局数量，这个最大只能改到60，能不能允许改到更大。

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
感谢反馈，根据之前的经验，该值过大会导致服务器返回不正确的内容从而报错（见 #170），为了稳定性我们才把上限改为了 60 😥，故该上限可能暂时不会做调整～

**Comment by Zzaphkiel** [comment]
重新试了下，好像 100 不会有什么问题的样子，下版本把上线改成 100 好了~
