### ISSUE TITLE
自动选英雄优化

### ISSUE THREAD

**Issue by ZMNUTT63000** [Zzaphkiel/Seraphine#296]
### 功能描述

根据我所在我寻找英雄的顺序来选择，比如我再5L 阵容AP英雄多 默认随机选取一个我预设好的AD池内随机一个英雄，相反则随机从AP英雄池里面抽取一个。我是玩打野位的所以我会有这样的想法。如果我在1L2L靠前的位置，我无法看到队友选什么，那么我就从我的预设英雄池里面随机选取一名英雄。不知道这样的系统能不能实现....（其实只实现随机选取预设池里面的一个也是很好的！）小小的建议反馈一下，因为现在自动接收和自动BAN英雄体验太好了。

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
太复杂了，现在还是以修 bug 为主吧，前面那俩闪退跟报错的 bug 还不知道咋修呢 😢
