### ISSUE TITLE
[BUG] bug

### ISSUE THREAD

**Issue by Keyle777** [Zzaphkiel/Seraphine#297]
### 问题描述

如图示

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

v0.11.1

### 日志文件

![屏幕截图 2024-03-24 154741](https://github.com/Zzaphkiel/Seraphine/assets/90593019/d602183d-ad87-4dc2-93e2-4e616e05a127)
![屏幕截图 2024-03-24 154752](https://github.com/Zzaphkiel/Seraphine/assets/90593019/6cc1d449-7de6-4a7d-a671-a2212c5fffbf)

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

非常低的概率会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
感谢反馈，怀疑原因同 #203
