### ISSUE TITLE
[BUG] 修复客户端窗口功能

### ISSUE THREAD

**Issue by qq891534** [Zzaphkiel/Seraphine#298]
### 问题描述

 修复客户端窗口功能好像不太好用，修复后大小显示还是异常。窗口尺寸之前设置的是 1600X900

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.10.3

### 客户端状态（若有）

游戏结束

### 复现方法（若有）

游戏结束时窗口大小显示异常，使用Seraphine修复功能后出现

### 日志文件

![QQ图片20240325064311](https://github.com/Zzaphkiel/Seraphine/assets/74325172/4464afa6-5f9d-49e7-aa01-ea39a3bf53d3)

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

未进行具体的重复测试

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
管理员权限开了没？

**Comment by qq891534** [comment]
> 管理员权限开了没？

开了
