### ISSUE TITLE
[Enhancement] 希望提供匹配秒选功能，以及选择英雄模糊或根据英雄名搜索的功能

### ISSUE THREAD

**Issue by Roselearn** [Zzaphkiel/Seraphine#299]
### 功能描述

我自己也在该项目中进行修改，增加了若游戏是匹配模式则秒选英雄，以及可以查找本人所拥有的英雄（在本项目中似乎是直接返回了全部的英雄）并实现了模糊搜索功能，如有需要可以合并到一起。现在有点小问题是匹配秒选速度较慢（大概需要等两秒才选出来）如果作者能加上这个功能就更好了，我自己写的另一个项目涵盖了秒选功能，但是没有这么漂亮的可视化界面，希望可以补充。

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Ninohana** [comment]
目前架构下是不支持的

当前是被动式地等待wss消息，就是说至少要等有人亮了英雄才会去选进行英雄选择。而且这也违背了这个工具的初衷：助手而不是外挂。抢英雄这种活儿，还请各凭本事。

**Comment by Zzaphkiel** [comment]
您好。

1. 我们现在提供的是自动亮起，并在时间结束前自动锁定的功能，暂无秒锁的实现计划。
2. 我们现在的输入编辑框应该也是支持模糊搜索的吧？
3. 关于亮起速度较慢，不知现在的仓库代码是否仍存在该问题？
