### ISSUE TITLE
观战的一些建议

### ISSUE THREAD

**Issue by 111333www** [Zzaphkiel/Seraphine#30]
如果观战一个id不存在的召唤师抛出的是程序异常弹窗。如果是一个存在但不在游戏中的id，是没有反应，这个情况是否可以优化一下
![image](https://github.com/Zzaphkiel/Seraphine/assets/110336737/e09402bb-702d-4a6b-a650-d582b2017b29)

**Comment by Zzaphkiel** [comment]
感谢反馈，下个版本优化~

**Comment by Zzaphkiel** [comment]
已修复该问题
