### ISSUE TITLE
[Enhancement] 能否出一个可以标记的黑名单

### ISSUE THREAD

**Issue by HFJ-GG** [Zzaphkiel/Seraphine#302]
### 功能描述

能否出一个可以标记的黑名单

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
感谢反馈。

关于该功能之前已有过多次讨论，我们暂无实现计划。

![IMG_1001](https://github.com/Zzaphkiel/Seraphine/assets/60383222/47c9939d-ce67-4118-b558-c5caaf04fe8f)
