### ISSUE TITLE
[BUG] 观战报错

### ISSUE THREAD

**Issue by MVPjoker** [Zzaphkiel/Seraphine#303]
### 问题描述

观战游戏好友时候报错！
一下错误信息：
Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\auxiliary_interface.py", line 790, in __onButtonClicked
  File "app\lol\connector.py", line 639, in spectate
KeyError: 'puuid'

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

v0.11.1

### 客户端状态（若有）

主界面

### 日志文件

[Seraphine_2024-03-27_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/14774448/Seraphine_2024-03-27_ERROR.log)

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
感谢。

报错是因为名字没输对，现在要跟着 #编号 一起输入进去才行；下个版本加了一个错误提示，而不是直接报错了

**Comment by MVPjoker** [comment]
我试过了一次，按照ID + #数字这样观战  我好友列表里面他明明是在游戏，软件提示该人没有加入对局，这和他玩云顶之弈有关系吗？云顶是不是不允许观战。我不太清楚。

**Comment by Zzaphkiel** [comment]
那应该就是不能吧，大乱斗和峡谷应该都可以观战的😰
