### ISSUE TITLE
[添加对位康特英雄推荐]

### ISSUE THREAD

**Issue by JaxonNing** [Zzaphkiel/Seraphine#304]
### 功能描述

能不能做一个阵容推荐，或者对位康特英雄推荐，比如对面选了个鳄鱼，根据U.gg和OPGG，对位打出经济差最大的英雄是俄洛依VN等英雄，这样就可以省去来回翻网站的功夫，Seraphine检测到双方已经选的英雄，用户可以点击已选英雄查看康特这个英雄的选择，甚至是出装符文，这样会很酷

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
感谢建议，我们一直有该计划，但限于我们有限的精力，目前进度较为缓慢 🥲

（P.S. 跟 #10 重复了，您可以请访问 #10 来获取相关内容开发的最新进展）
