### ISSUE TITLE
[Question] 打开萨勒芬妮一直提示以下图中

### ISSUE THREAD

**Issue by lg266** [Zzaphkiel/Seraphine#307]
### 问题描述

![微信图片_20240328222040](https://github.com/Zzaphkiel/Seraphine/assets/41727075/e45d034e-2bfc-49a9-8be7-132df5fef494)

连续几天了，设置了代理可以正常连接github，我以为是服务器问题，但是我看issues里没有朋友提到，不知道是哪里的问题？
使用0.11.1和0.11.0均相同

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by lg266** [comment]
大区为艾欧尼亚

**Comment by linkairui0526** [comment]
段位更改有用吗

**Comment by Zzaphkiel** [comment]
见 #203，电一经常这样，服务器原因😢

**Comment by Zzaphkiel** [comment]
> 段位更改有用吗

@linkairui0526 只是看起来变了，肯定改不了你真实的段位呀

**Comment by linkairui0526** [comment]
> > 段位更改有用吗
> 
> @linkairui0526 只是看起来变了，肯定改不了你真实的段位呀

就是看的效果都没有
