### ISSUE TITLE
[Question]  本地部署时环境能否用miniconda代替？

### ISSUE THREAD

**Issue by rolypolytoy1** [Zzaphkiel/Seraphine#308]
### 问题描述

因为build在虚拟机，磁盘空间有点捉襟见肘了，所以想着能否用miniconda代替？如果有区别的话，需要手动安装哪些包？

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
我也没用过 miniconda，你先装着试试呗，看缺啥再补啥hh

**Comment by rolypolytoy1** [comment]
好滴
