### ISSUE TITLE
[Enhancement] 在对局信息界面显示最近胜率

### ISSUE THREAD

**Issue by RicharYe** [Zzaphkiel/Seraphine#310]
### 功能描述

在另外已经被关闭的ISSUE提过这一点，不知道CLOSE的ISSUE是否还会对作者进行提醒所以开一个新的再问一下~

个人信息中的对局能通过不同颜色（绿色和红色）来区分胜负场，能否通过对类似于颜色数量的统计来计算胜率，不需要总的胜率计算，就计算设置的默认对局数量的胜率。
然后这个胜率数据放置于对局信息里面。

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
现在这种显示方式不已经挺直观的了嘛？

**Comment by RicharYe** [comment]
想要的是胜率 这个数据 w(ﾟДﾟ)w

**Comment by Zzaphkiel** [comment]
胜率也能显示这 11 局的胜率呀，而且现在也没啥地方能放了吧 0.0

**Comment by RicharYe** [comment]
位置的话写在段位附近，加一行字应该不是很占地方，emmm  关于局数的话 我的想是以在设置中自己设置的局数为限

**Comment by Zzaphkiel** [comment]
感觉不是很有意义。如果一次请求过多的局数，接口返回效率会很差，这个界面就会加载的比较慢（还有可能带着客户端闪退）；如果请求的局数不多，那跟直接看右边的总览也没啥区别了 😥

**Comment by RicharYe** [comment]
我这边设置的默认对局数量为40，在对局信息中只能看到11，剩余的需要点进个人的生涯界面里面来查看更多，如果有胜率来直接看这40把的胜率的话我认为会更直观一点。不需要一个个人点进去查看

**Comment by RicharYe** [comment]
我认为对一些人是有些帮助的，如果作者认为没必要的话 那就算啦吧

**Comment by Zzaphkiel** [comment]
明白了，我先试试效果吧，不过实现的优先度不是很大，修前面几个 BUG 的优先度高一些哈

**Comment by RicharYe** [comment]
好的~

**Comment by twomoonbird** [comment]
我觉得不如显示当前英雄场数和胜率

**Comment by Zzaphkiel** [comment]
抱歉，还是暂时决定不实现该特性 😥

**Comment by 0400H** [comment]
> 抱歉，还是暂时决定不实现该特性 😥

可以通过开关决定是否显示胜率在还是很重要的。
比如玩排位或者大乱斗，通过查看胜率就可以快速了解队友的能力，毕竟扫一眼胜率只用几秒，而一页页翻队友要很长时间，游戏开了更没有时间去看。
