### ISSUE TITLE
[BUG] （删去左右圆括号，并在此处简要描述问题）

### ISSUE THREAD

**Issue by Porco97** [Zzaphkiel/Seraphine#311]
### 问题描述

vpn正常，无法连接github，无法获取更新
![Snipaste_2024-03-31_14-37-51](https://github.com/Zzaphkiel/Seraphine/assets/83524236/be5a57fe-5e0d-43ba-a238-112c10d8dd09)
![Snipaste_2024-03-31_14-38-01](https://github.com/Zzaphkiel/Seraphine/assets/83524236/93ef2fc8-0f6e-4a67-8410-519a2d1ae697)

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

v.0.11.1

### 客户端状态（若有）

正常运行

### 日志文件

[Seraphine_2024-03-31_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/14814400/Seraphine_2024-03-31_ERROR.log)
[Seraphine_2024-03-21_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/14814395/Seraphine_2024-03-21_ERROR.log)
[Seraphine_2024-03-28_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/14814396/Seraphine_2024-03-28_ERROR.log)
[Seraphine_2024-03-29_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/14814398/Seraphine_2024-03-29_ERROR.log)
[Seraphine_2024-03-30_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/14814399/Seraphine_2024-03-30_ERROR.log)

### 您进行游戏的服务器（若有）

祖安

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
关掉 vpn，或者开 vpn 之后在 Seraphine 设置界面设置一下代理地址。
