### ISSUE TITLE
[Enhancement] 对局信息界面显示所有人当前英雄的场次和胜率以及是否和其他人开黑

### ISSUE THREAD

**Issue by twomoonbird** [Zzaphkiel/Seraphine#312]
### 功能描述

希望可以在对局信息里展示所有人当前英雄的场次和胜率，这样可以在开局前大致了解队友和对手对当前使用英雄的熟练度情况。同时也希望对比下最近5场的组队情况，把开黑的人用各种颜色标记出来，这样对局时能更好地做好防gank。

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
您好。

1. 开黑的提示已经在左侧通过颜色显示出来了。
2. 英雄胜率应该不会实现，因为用于统计的局数过少。近期总胜率的实现进展请关注 #310。
