### ISSUE TITLE
[Enhancement] 设置界面选项分类错误

### ISSUE THREAD

**Issue by xiaomingzzzzz** [Zzaphkiel/Seraphine#313]
### 功能描述

作者你好，现在软件上有很多美妙的功能，但是他们的分布太分散了且难以找到，有些游戏设置也在【设置】里，会使得用户在使用时经常难以迅速找到，根据这个情况我给出如下建议：
1.整合一下功能，例如增加分类，提升用户的使用体验
2.没启动客户端时的页面可以美化一下加个logo啥的

最后感谢你的这款软件 让我上了王者932分

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
感谢支持。

1. 关于您提到的“游戏功能也在设置中”，可以具体举例一下吗？
2. 目前在软件加载的过程中有 logo 显示，客户端没启动时的界面应该暂时不会做大幅改动（现在感觉挺好的了）

**Comment by xiaomingzzzzz** [comment]
例如【客户端里设置最大游戏对局数量】在设置中，设置更多的让人们理解为对于软件的设置，比如我觉得很棒的云母色，可以把功能整合到一起，甚至包括核心的查战绩~

**Comment by xiaomingzzzzz** [comment]
很高兴作者积极的回复 或许可以建立一个针对这款软件的粉丝群哈哈哈

**Comment by xiaomingzzzzz** [comment]
btw 自定义对局的战绩查询可能可以实现吗

**Comment by Zzaphkiel** [comment]
1. 设置中设置的是软件生涯界面的对局数量，并非客户端的。
2. 云母效果是关于程序外观个性化的设置，与核心功能查战绩应该放不到一起
3. 由于接口限制，自定义对局的战绩只能查到自己的。
4. 反馈群还需要再考虑下，目前在维护 Seraphine 的开发者都有自己的主业，使用其它反馈方式不一定比 GitHub 更有效率。

**Comment by xiaomingzzzzz** [comment]
![8f4ffdd0dd72d7408b3b118888f0ea3](https://github.com/Zzaphkiel/Seraphine/assets/143982845/5a488b98-86c5-4bd4-8fb3-52c2276d8ab4)
跟大佬分享一下~目前公众号lz玉米的功能支持查询自定义战绩（这张截图上没有），界面上的其他功能也可以看看~祝大佬生活愉快

**Comment by Zzaphkiel** [comment]
用的接口不一样，我们用的 LCU API。
