### ISSUE TITLE
近期对局、大乱斗、符文系统

### ISSUE THREAD

**Issue by Anzi212** [Zzaphkiel/Seraphine#317]
### 功能描述

对局详情内加入mvp这些标识，增加失败类型，例如投降则显示投降，水晶被推则原本显示失败。
大乱斗玩家也比较需要对应英雄增强削弱BUFF显示，和无CD切换备选英雄。
符文系统也快快加入，一键选择对应模式符文，化繁为简。
[Pengu Loader_1.1.0(20240213).zip](https://github.com/Zzaphkiel/Seraphine/files/14892222/Pengu.Loader_1.1.0.20240213.zip)
附上文件，是在找到Seraphine之前一直在使用的项目，其中就有大乱斗BUFF查看器，无CD选择备选英雄，希望能帮助作者打磨项目，谢谢。

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
和之前的 issue 重复了
