### ISSUE TITLE
召唤师名称过长时, 会超出控件无法显示完全

### ISSUE THREAD

**Issue by Hpero4** [Zzaphkiel/Seraphine#32]
![YR(NL%0TT}8VFLKT A}2{(6](https://github.com/Zzaphkiel/Seraphine/assets/40506420/0a93b414-7f74-4336-a2dc-c32d103b9350)

尝试在代码中通过重写resizeEvent方法使font_size自适应控件宽度, 测试了一下没有效果, 因此没有上传代码, 大佬有空可以看看https://github.com/Zzaphkiel/Seraphine/blob/8a3a1e99ec3dd6a9a951d394b91a85884770c644/app/components/summoner_name_button.py#L14

**Comment by Zzaphkiel** [comment]
感谢反馈

感觉更暴力一点，改一下 layout 的 margin，或者干脆直接使用更小一号的字体就行了，因为如果名字有大有小的也不是很好看 0.0 后面我改一下好了~

**Comment by Zzaphkiel** [comment]
已通过修改字体大小和 margin 修复这个问题
