### ISSUE TITLE
[Enhancement] 增加大乱斗胜率队提醒功能

### ISSUE THREAD

**Issue by RaiderZP** [Zzaphkiel/Seraphine#321]
### 功能描述

最近老遇到胜率队，想泉水挂机3分重开，但有的时候就是忘记看对面战绩了，没注意，等到进游戏开始对线才发觉。
所以能不能出一个功能，当进入大乱斗对局后会自动查询对方5人战绩，如果5人全隐藏，则提醒胜率队风险；如果有人没隐藏，且前2页战绩除了重开就是胜利，则也提醒胜率队风险，希望大佬能加一下，从逻辑上实现应该不难，谢谢！

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
感谢反馈。和 #85 重复了，暂无相关计划。
