### ISSUE TITLE
[Question] 禁止商用实际上已经属于衍生许可证

### ISSUE THREAD

**Issue by mzji** [Zzaphkiel/Seraphine#323]
### 问题描述

GPLv3 作为 copyleft license ，本身不会也不可能限制被授权实体的用途，因此所有限制用途的条款本质上会使软件变为非自由（non-free）软件；
如果确有这方面的需求，建议将授权更改为 AGPLv3 协议，能够对用途作出明确限制的同时保证软件的自由性质。

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
感谢，我不太了解这方面的知识 😭。

请问由于我使用了 GPLv3 的 [PyQt-Fluent-Widgets](https://github.com/zhiyiYo/PyQt-Fluent-Widgets)，我可以要求不可以商用我的代码以及二进制文件吗？只需要（合法地）修改 GPLv3 为 AGPLv3 即可吗？

**Comment by mzji** [comment]
限制用途与自由软件许可证存在严重冲突， AGPLv3 的话要求在任何场景下都保证软件源码可被获取（避免非自由利用）
如果一定要禁止任何商用，建议切换为 CC BY-NC-SA 协议

**Comment by Zzaphkiel** [comment]
因为我使用了 GPLv3 的 GUI 库，所以我可以修改协议为您提到的 CC BY-NC-SA 4.0 吗？

**Comment by mzji** [comment]
> 因为我使用了 GPLv3 的 GUI 库，所以我可以修改协议为您提到的 CC BY-NC-SA 4.0 吗？

问了一下 ChatGPT 说是有冲突，用了 GPLv3 就还得用 GPLv3
hmmmmmmmm 难搞喔

**Comment by mzji** [comment]
主要是 GPLv3 本身不限制用途，再加条款可能会被宣布违反 GPLv3 所以协议无效
不过协议无效就自动回退到私有协议所以好像也没事？
总之这里肯定是有坑的

**Comment by Zzaphkiel** [comment]
如果我无法限制商用行为的话，那我就把 Readme 中的要求删掉了 🥹
