### ISSUE TITLE
打开应用出现：请求 APl getSummonerGamesByPuuid: 服务器返回了不正常内容，可能其正在维护中

### ISSUE THREAD

**Issue by Kejiboy** [Zzaphkiel/Seraphine#325]
### 问题描述

打开应用出现：请求 APl getSummonerGamesByPuuid: 服务器返回了不正常内容，可能其正在维护中

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.11.1

### 客户端状态（若有）

游戏中、房间组队中、队列中

### 复现方法（若有）

任何客户端状态双击后出现：
![image](https://github.com/Zzaphkiel/Seraphine/assets/61222820/fbc1269f-7fd2-4339-a0bd-d0cb6a854325)

### 日志文件

[Seraphine_2024-04-08_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/14906627/Seraphine_2024-04-08_ERROR.log)

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
见 #203 。

**Comment by Kejiboy** [comment]
感谢您！
