### ISSUE TITLE
[BUG] Exception occurred：KeyError: 21452922 KeyError: 21452922

### ISSUE THREAD

**Issue by Rei-Nakki** [Zzaphkiel/Seraphine#326]
### 问题描述

选英雄和开始加载会报错
![image](https://github.com/Zzaphkiel/Seraphine/assets/70908717/187037d6-040c-428d-bef3-4eca78d574b5)

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.11.1

### 客户端状态（若有）

选英雄和开始对局加载

### 您进行游戏的服务器（若有）

OCE 澳服，但是日文客户端

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
台服好像也有这个问题（见 https://github.com/Zzaphkiel/Seraphine/issues/277#issuecomment-2011229424 ），暂时换 0.10.3 试试？（虽然我感觉也会有这个问题）

**Comment by Rei-Nakki** [comment]
> 台服好像也有这个问题（见 [#277 (comment)](https://github.com/Zzaphkiel/Seraphine/issues/277#issuecomment-2011229424) ），暂时换 0.10.3 试试？（虽然我感觉也会有这个问题）。
> 
> 目前我们实在腾不出时间来修 BUG，还请耐心等待 🥲

Hi换0.10.3就不报错了，谢谢妮

**Comment by Zzaphkiel** [comment]
c1cff6c 修复了该问题。
