### ISSUE TITLE
[Question] 此应用已在闲鱼平台上售卖

### ISSUE THREAD

**Issue by jqyisbest** [Zzaphkiel/Seraphine#329]
### 问题描述

如题

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
感谢您的反馈。

这确实是让我们比较愤怒也比较寒心的事情，目前我们已经通过闲鱼平台举报。

近期会在程序开启的公告中提示用户，预防上当受骗，付费购买开源。
