### ISSUE TITLE
[BUG] 关机时提示

### ISSUE THREAD

**Issue by happyLiu97** [Zzaphkiel/Seraphine#330]
### 问题描述

Seraphine: Seraphine.exe-应用程序错误
0x00000210A119BEC0指令引用了0x00000210A119BEC0内存，该内存不能为 written.
要终止程序，请单击“确定”

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

v0.11.1

### 客户端状态（若有）

关闭

### 复现方法（若有）

关机时候提示 之前提示应用程序什么的 

### 日志文件

[Seraphine_2024-04-12_ERROR.log](https://github.com/Zzaphkiel/Seraphine/files/14960386/Seraphine_2024-04-12_ERROR.log)

### 您进行游戏的服务器（若有）

德玛西亚

### 出现率（若有）

每次这么做大部分时候会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
感谢反馈，之前 #193 的时候我都没法复现这问题，目前依旧是无法复现的 😥

~就算复现了我也不知道怎么修啊~

**Comment by Ninohana** [comment]
这应该是win11的bug，其他软件照样会报
