### ISSUE TITLE
[BUG] 多服切换导致程序报错

### ISSUE THREAD

**Issue by yyd003** [Zzaphkiel/Seraphine#337]
### 问题描述

我平常同时玩台服和国服，更改链接的客户端到国服后，在生涯tab还是显示#TW2，导致查询战绩时找不到对局报错并退出
![image](https://github.com/Zzaphkiel/Seraphine/assets/19585311/6e40b8ae-927e-49ad-993a-7d8ca9d9e084)

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

v0.11.1

### 客户端状态（若有）

大厅

### 复现方法（若有）

问题描述已提及

### 日志文件

Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 802, in __onCareerGameClicked
  File "app\view\search_interface.py", line 1136, in updateGameDetailView
AttributeError: 'SearchInterface' object has no attribute 'puuid'

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
感谢反馈。

请问可以提供一下具体的复现过程吗？（指从打开 Seraphine 开始到报错中间的全过程）

**Comment by yyd003** [comment]
打开 Seraphine-打开台服lol-打开国服lol-启动页tab更改链接的客户端到国服-生涯tab点击任一最近战绩-弹窗程序出现异常，应该是切换国服了，查询战绩时保留了#TW2后缀，查询为空导致的

**Comment by Zzaphkiel** [comment]
> 打开 Seraphine-打开台服lol-打开国服lol-启动页tab更改链接的客户端到国服-生涯tab点击任一最近战绩-弹窗程序出现异常，应该是切换国服了，查询战绩时保留了#TW2后缀，查询为空导致的

这样应该最多是提示一下搜不到人呀，应该不会报错的。

方便的话可以在设置中调整日志等级为 debug，复现该问题并提供一下日志文件吗？

（因其中可能包含账号用户名等敏感信息，可以考虑通过邮件发送给 seraphine.feedback@outlook.com）

**Comment by Zzaphkiel** [comment]
[v0.12.0](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.12.0) 尝试修复了该问题，试一下吧 😋

**Comment by yyd003** [comment]
Nice! Thanks for your new release
