### ISSUE TITLE
[Enhancement] 能否增加个人与对局平均隐藏分显示功能

### ISSUE THREAD

**Issue by gk997290588** [Zzaphkiel/Seraphine#339]
### 功能描述

最近一个隐藏分查询网站曝光度上升，个人使用了一下感觉是个很有趣的功能
但是不知道他们是怎么实现和度量的，我也不确定你们使用的API是否支持
不过确实挺有意思，因为大乱斗选手之前都不太清楚自己的隐藏分
在此提出这项功能希望得到你们的考虑
另外，此网站因急剧扩散压力陡增目前已被迫关站拒绝流量，也请你们同样将这个情况纳入考量
![image](https://github.com/Zzaphkiel/Seraphine/assets/68001274/67d59837-2eda-40ac-88a5-560132eaa8f4)
![image](https://github.com/Zzaphkiel/Seraphine/assets/68001274/0651db31-fbd1-4b9e-bacc-a8441e50cebc)

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
感谢建议。

1. 这个网站我之前是知道的，但是他们是从哪里得到相关数据的我们还未知
2. 我们使用英雄联盟的官方 API，应该不存在用户访问流量方面的压力吧~

**Comment by gk997290588** [comment]
所以这个功能是否在考虑内了呢，很喜欢你们的软件

**Comment by 1106545708** [comment]
这个应该是腾讯的程序员带出来了一部分内部的隐藏分数据，作者要是能完成这一部分内容的话就太好了，现在该网站关闭已经没有地方可查了

**Comment by Zzaphkiel** [comment]
@gk997290588 @1106545708 暂时还不知道他们是怎么搞到这个 “隐藏分” 数据的，我们理论上还没法实现这个功能
