### ISSUE TITLE
[Enhancement] 请问有考虑过添加赛马相关功能么

### ISSUE THREAD

**Issue by Jerry-FaGe** [Zzaphkiel/Seraphine#343]
### 功能描述

通过数据量化队友和对手的水平有助于在对局中更好的进行资源分配，我这里有一份之前几个项目的评分规则，不知道您有没有计划

![175abee366b862aa859feeaa0faa9ef1](https://github.com/Zzaphkiel/Seraphine/assets/40235071/fa3e8d1b-830a-44ff-a39d-5f58a63cf611)

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
见 #189，暂无相关计划
