### ISSUE TITLE
[Question] 更新之后可以打包一下吗？

### ISSUE THREAD

**Issue by SUZHIWAI** [Zzaphkiel/Seraphine#345]
### 问题描述

希望更新之后可以打包一下。

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
五一之前会有新版本发布，还请期待一下

**Comment by Zzaphkiel** [comment]
[v0.12.0](https://github.com/Zzaphkiel/Seraphine/releases/tag/v0.12.0) 已发布。
