### ISSUE TITLE
[BUG] 点击斗魂竞技场战绩报错

### ISSUE THREAD

**Issue by asd2422313947** [Zzaphkiel/Seraphine#346]
### 问题描述

Traceback (most recent call last):
  File "C:\hj\lib\site-packages\qasync\__init__.py", line 780, in _error_handler
    task.result()
  File "C:\Seraphine-main\app\view\search_interface.py", line 1166, in __onGameTabClicked
    await self.updateGameDetailView(tab.gameId, self.puuid)
  File "C:\Seraphine-main\app\view\search_interface.py", line 1176, in updateGameDetailView
    game = await parseGameDetailData(puuid, game)
  File "C:\Seraphine-main\app\lol\tools.py", line 364, in parseGameDetailData
    teams[tid]['kills'] += kills
KeyError: 600

### 系统信息

Windows 10

### 运行方式

在 Python 环境中直接运行源代码

### 软件版本

最新源代码

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
感谢，已定位该问题

**Comment by Zzaphkiel** [comment]
已在 c5cad96 修复该问题。

**Comment by saiveen1** [comment]
> 已在 [c5cad96](https://github.com/Zzaphkiel/Seraphine/commit/c5cad964ec3131fd3a6b0418b97090459ff72b50) 修复该问题。

国服斗魂目前没有分段
[tools.py#L417](https://github.com/Zzaphkiel/Seraphine/blob/ab157e2ef1e1d1540e2e7c9c2100ff28f5283613/app/lol/tools.py#L417)

**Comment by Zzaphkiel** [comment]
> > 已在 [c5cad96](https://github.com/Zzaphkiel/Seraphine/commit/c5cad964ec3131fd3a6b0418b97090459ff72b50) 修复该问题。
> 
> 国服斗魂目前没有分段 [tools.py#L417](https://github.com/Zzaphkiel/Seraphine/blob/ab157e2ef1e1d1540e2e7c9c2100ff28f5283613/app/lol/tools.py#L417)

已在 792dd63 修复该问题，感谢！

**Comment by saiveen1** [comment]
> > > 已在 [c5cad96](https://github.com/Zzaphkiel/Seraphine/commit/c5cad964ec3131fd3a6b0418b97090459ff72b50) 修复该问题。
> > 
> > 
> > 国服斗魂目前没有分段 [tools.py#L417](https://github.com/Zzaphkiel/Seraphine/blob/ab157e2ef1e1d1540e2e7c9c2100ff28f5283613/app/lol/tools.py#L417)
> 
> @saiveen1 已在 [792dd63](https://github.com/Zzaphkiel/Seraphine/commit/792dd63bd3f5deb02b86f849fd821a58a496235d) 修复该问题，感谢！

[tool.py#L916](https://github.com/Zzaphkiel/Seraphine/blob/a8b195180f447340f76e7a2cd2cb40009a6ae1d0/app/lol/tools.py#L916)
斗魂模式进入选人界面obfuscatedSummonerId获取到的summoner是404引发崩溃

**Comment by Zzaphkiel** [comment]
@saiveen1 7a256f8 修复了该问题，昨晚意识不清醒瞎写的代码没测试，我的问题 😭

**Comment by saiveen1** [comment]
> @saiveen1 [7a256f8](https://github.com/Zzaphkiel/Seraphine/commit/7a256f821a155549243aceef4580512341e87160) 修复了该问题，昨晚意识不清醒瞎写的代码没测试，我的问题 😭

辛苦，感谢作者无私提供这么好用的软件！
