### ISSUE TITLE
[BUG] 对局信息面板可能显示玩家名为空

### ISSUE THREAD

**Issue by asd2422313947** [Zzaphkiel/Seraphine#347]
### 问题描述

这个问题需要进一步测试，请等待我的测试结果，或者您也可以进行测试，请不要关闭此Issue。

### 系统信息

Windows 10

### 运行方式

在 Python 环境中直接运行源代码

### 软件版本

最新源代码

### 出现率（若有）

每次这么做大部分时候会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
方便的话可以打印一下 ``main_window.py: 792`` ``__onChampionSelectBegin`` 函数中的 ``session`` 变量嘛？今晚我用了一晚上也没遇到过这个问题呀

**Comment by asd2422313947** [comment]
> 方便的话可以打印一下 `main_window.py: 792` `__onChampionSelectBegin` 函数中的 `session` 变量嘛？今晚我用了一晚上也没遇到过这个问题呀

对局信息面板的左侧虽然名字是空的，但是可以点击到对应玩家战绩页面，但是右上方的点击就会显示召唤师名字为空

**Comment by asd2422313947** [comment]
> 方便的话可以打印一下 `main_window.py: 792` `__onChampionSelectBegin` 函数中的 `session` 变量嘛？今晚我用了一晚上也没遇到过这个问题呀

排位模式不存在这个问题，就是匹配会有这个问题，不知道为什么

**Comment by Zzaphkiel** [comment]
1. 是召唤师峡谷匹配吗？我在极地大乱斗没遇到过这个问题。
2. 出现该问题后，立即关了程序重开，问题依旧会存在（即会在同一局游戏中稳定复现）吗？

**Comment by asd2422313947** [comment]
> 1. 是召唤师峡谷匹配吗？我在极地大乱斗没遇到过这个问题。
> 2. 出现该问题后，立即关了程序重开，问题依旧会存在（即会在同一局游戏中稳定复现）吗？

是召唤师峡谷匹配，我没有尝试关了重开，但是几把匹配下来基本都遇到了这种情况

**Comment by asd2422313947** [comment]
> 方便的话可以打印一下 `main_window.py: 792` `__onChampionSelectBegin` 函数中的 `session` 变量嘛？今晚我用了一晚上也没遇到过这个问题呀

![微信图片_20240501211527](https://github.com/Zzaphkiel/Seraphine/assets/47559534/53279ea1-0aa1-4652-87fc-19718e8740a4)

**Comment by asd2422313947** [comment]
> 方便的话可以打印一下 `main_window.py: 792` `__onChampionSelectBegin` 函数中的 `session` 变量嘛？今晚我用了一晚上也没遇到过这个问题呀

{'actions': [[{'actorCellId': 0, 'championId': 0, 'completed': False, 'id': 0, 'isAllyAction': False, 'isInProgress': True, 'type': 'ban'}, {'actorCellId': 1, 'championId': 0, 'completed': False, 'id': 1, 'isAllyAction': False, 'isInProgress': True, 'type': 'ban'}, {'actorCellId': 2, 'championId': 0, 'completed': False, 'id': 2, 'isAllyAction': False, 'isInProgress': True, 'type': 'ban'}, {'actorCellId': 3, 'championId': 0, 'completed': False, 'id': 3, 'isAllyAction': False, 'isInProgress': True, 'type': 'ban'}, {'actorCellId': 4, 'championId': 0, 'completed': False, 'id': 4, 'isAllyAction': False, 'isInProgress': True, 'type': 'ban'}, {'actorCellId': 5, 'championId': 0, 'completed': False, 'id': 5, 'isAllyAction': True, 'isInProgress': True, 'type': 'ban'}, {'actorCellId': 6, 'championId': 0, 'completed': False, 'id': 6, 'isAllyAction': True, 'isInProgress': True, 'type': 'ban'}, {'actorCellId': 7, 'championId': 0, 'completed': False, 'id': 7, 'isAllyAction': True, 'isInProgress': True, 'type': 'ban'}, {'actorCellId': 8, 'championId': 0, 'completed': False, 'id': 8, 'isAllyAction': True, 'isInProgress': True, 'type': 'ban'}, {'actorCellId': 9, 'championId': 0, 'completed': False, 'id': 9, 'isAllyAction': True, 'isInProgress': True, 'type': 'ban'}], [{'actorCellId': -1, 'championId': 0, 'completed': False, 'id': 103, 'isAllyAction': False, 'isInProgress': False, 'type': 'ten_bans_reveal'}], [{'actorCellId': 0, 'championId': 0, 'completed': False, 'id': 10, 'isAllyAction': False, 'isInProgress': False, 'type': 'pick'}], [{'actorCellId': 5, 'championId': 0, 'completed': False, 'id': 11, 'isAllyAction': True, 'isInProgress': False, 'type': 'pick'}, {'actorCellId': 6, 'championId': 0, 'completed': False, 'id': 12, 'isAllyAction': True, 'isInProgress': False, 'type': 'pick'}], [{'actorCellId': 1, 'championId': 0, 'completed': False, 'id': 13, 'isAllyAction': False, 'isInProgress': False, 'type': 'pick'}, {'actorCellId': 2, 'championId': 0, 'completed': False, 'id': 14, 'isAllyAction': False, 'isInProgress': False, 'ty

**Comment by asd2422313947** [comment]
> 方便的话可以打印一下 `main_window.py: 792` `__onChampionSelectBegin` 函数中的 `session` 变量嘛？今晚我用了一晚上也没遇到过这个问题呀

玩家的战绩数据均可以正常显示，就是名字为空

**Comment by Zzaphkiel** [comment]
> > 方便的话可以打印一下 `main_window.py: 792` `__onChampionSelectBegin` 函数中的 `session` 变量嘛？今晚我用了一晚上也没遇到过这个问题呀
> 
> ![微信图片_20240501211527](https://private-user-images.githubusercontent.com/47559534/327130087-53279ea1-0aa1-4652-87fc-19718e8740a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1Njk3MDUsIm5iZiI6MTcxNDU2OTQwNSwicGF0aCI6Ii80NzU1OTUzNC8zMjcxMzAwODctNTMyNzllYTEtMGFhMS00NjUyLTg3ZmMtMTk3MThlODc0MGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDEzMTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MzM0YjZmNmU4MzA3MjY5MjhkOWQ0MDk0MDdhNjA1YzkxYTYyYTZiZGJjYmQwYjNhYTE3NjdmYWNkZjU2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GOkebbhCvOA8-L487PcTnM7PoXGan79Nln68X7pv4FA)

看样子这是在进入游戏之后吗？可以贴一下 `main_window.py: 839` `__onGameStart` 的 `session` 吗？

**Comment by asd2422313947** [comment]
> > > 方便的话可以打印一下 `main_window.py: 792` `__onChampionSelectBegin` 函数中的 `session` 变量嘛？今晚我用了一晚上也没遇到过这个问题呀
> > 
> > 
> > <img alt="微信图片_20240501211527" width="183.46875" height="21" src="https://private-user-images.githubusercontent.com/47559534/327130087-53279ea1-0aa1-4652-87fc-19718e8740a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1Njk3MDUsIm5iZiI6MTcxNDU2OTQwNSwicGF0aCI6Ii80NzU1OTUzNC8zMjcxMzAwODctNTMyNzllYTEtMGFhMS00NjUyLTg3ZmMtMTk3MThlODc0MGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDEzMTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MzM0YjZmNmU4MzA3MjY5MjhkOWQ0MDk0MDdhNjA1YzkxYTYyYTZiZGJjYmQwYjNhYTE3NjdmYWNkZjU2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GOkebbhCvOA8-L487PcTnM7PoXGan79Nln68X7pv4FA">
> 
> 看样子这是在进入游戏之后吗？可以贴一下 `main_window.py: 839` `__onGameStart` 的 `session` 吗？

是的，进入游戏之后，上面贴了session变量内容

**Comment by asd2422313947** [comment]
> > > 方便的话可以打印一下 `main_window.py: 792` `__onChampionSelectBegin` 函数中的 `session` 变量嘛？今晚我用了一晚上也没遇到过这个问题呀
> > 
> > 
> > <img alt="微信图片_20240501211527" width="183.46875" height="21" src="https://private-user-images.githubusercontent.com/47559534/327130087-53279ea1-0aa1-4652-87fc-19718e8740a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1Njk3MDUsIm5iZiI6MTcxNDU2OTQwNSwicGF0aCI6Ii80NzU1OTUzNC8zMjcxMzAwODctNTMyNzllYTEtMGFhMS00NjUyLTg3ZmMtMTk3MThlODc0MGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDEzMTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MzM0YjZmNmU4MzA3MjY5MjhkOWQ0MDk0MDdhNjA1YzkxYTYyYTZiZGJjYmQwYjNhYTE3NjdmYWNkZjU2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GOkebbhCvOA8-L487PcTnM7PoXGan79Nln68X7pv4FA">
> 
> 看样子这是在进入游戏之后吗？可以贴一下 `main_window.py: 839` `__onGameStart` 的 `session` 吗？

就是玩家的战绩数据是正常获取的，但是有部分玩家的名字是显示不出来的，为空的

**Comment by Zzaphkiel** [comment]
暂时没有好的修复方法，左边点击能查询是因为它使用的不是召唤师名而是 `puuid`，右侧的名字点击了不能查是因为搜索界面必须要召唤师名 + 数字编号才可以。

因为我暂时没法复现这个问题，所以只能尝试地打了个补丁 7a256f8，不知道有用没用 😥

**Comment by asd2422313947** [comment]
> 暂时没有好的修复方法，左边点击能查询是因为它使用的不是召唤师名而是 `puuid`，右侧的名字点击了不能查是因为搜索界面必须要召唤师名 + 数字编号才可以。
> 
> 因为我暂时没法复现这个问题，所以只能尝试地打了个补丁 [7a256f8](https://github.com/Zzaphkiel/Seraphine/commit/7a256f821a155549243aceef4580512341e87160)，不知道有用没用 😥

好的，希望有用，哈哈

**Comment by asd2422313947** [comment]
> @asd2422313947 请问目前还有再遇到这个问题吗？

经过两天测试，目前没有再次发现此问题
