### ISSUE TITLE
[Enhancement] 自动BAN英雄增加多选

### ISSUE THREAD

**Issue by Keyle777** [Zzaphkiel/Seraphine#353]
### 功能描述

![image](https://github.com/Zzaphkiel/Seraphine/assets/90593019/f20280f6-f39f-4067-a0bb-6f6c550a52cb)
前提：如有精力可以优化的选项。
我希望在这个页面增加多选BAN英雄的选择，原因很简单，我们自己的位置大多数情况下就是自己的主位置或者备选、再或者补位到其他位置，可能大家要BAN的英雄也不一样。比如我这把是上路我就需要BAN剑姬、这把我是ADC我就BAN德莱文等等，目前这个功能感觉不是太完善，它的初始目的是减轻玩家的负担，可以做的再好些。

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Keyle777** [comment]
再或者另外一种情况，队友把预BAN的英雄提前BAN掉了。我是不是有备选的英雄的选择。

**Comment by Zzaphkiel** [comment]
感谢建议，选择英雄时目前已支持多选，自动 BAN 还需要时间开发。

**Comment by Zzaphkiel** [comment]
仓库代码已实现该特性
