### ISSUE TITLE
[Enhancement] （为什么没有黑名单功能，参考隔壁joi英雄联盟助手）

### ISSUE THREAD

**Issue by 3150214587** [Zzaphkiel/Seraphine#355]
### 功能描述

[Enhancement] （为什么没有黑名单功能，参考隔壁joi英雄联盟助手，可以excel导入和导出，并且在对局中提示）

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
暂无开发计划。
