### ISSUE TITLE
大佬你这功能不太实用啊

### ISSUE THREAD

**Issue by damoshen123** [Zzaphkiel/Seraphine#36]
功能实用的也就一个战绩查询。但你这战绩查询只给出了战绩。我想应该使用一些直观的数据。例如对手队友最近的kda ，最近的排位胜率。该英雄的场次和胜率。一眼直观的看出队友和对手坑不坑。

**Comment by Hpero4** [comment]
感谢反馈, 确实存在相关的场景, 后期考虑添加

**Comment by Zzaphkiel** [comment]
感谢反馈。

> 对手队友最近的kda ，最近的排位胜率。该英雄的场次和胜率。

最近 KDA、英雄胜率都可以在个人生涯界面中看到（点击对局信息的召唤师卡片上的召唤师名），最近排位胜率也可以在对局信息右侧的最近战绩一眼看到呀，不知道还有什么更直观的方式了？

**Comment by damoshen123** [comment]
> 感谢反馈。
> 
> > 对手队友最近的kda ，最近的排位胜率。该英雄的场次和胜率。
> 
> 最近KDA、英雄胜率都可以在个人生​​涯界面中看到（点击对局信息右侧的指令师操作上的指令师名），最近排位胜率也可以在对局信息右侧的最近战绩快速看到呀，不知道还有什么更有趣的方式呢？

需要的是一目了然。对局开始了没有太多的时间查询。可能要考虑实际应用，kda也该更加直观 例如（k+a）/d*3

**Comment by Zzaphkiel** [comment]
目前考虑给对局信息界面加入召唤师近期的 KDA 信息，其他信息就不准备加入了。

当初在写这个界面的时候选择了展示最近**对局记录详情**（英雄、胜负、模式、时间、本局 KDA）的方案，而不是只展示双方最近**统计信息**的方案，要在目前的基础上加入比较详细的统计信息应该是不太可能的，还是有所取舍吧~

**Comment by Zzaphkiel** [comment]
已添加召唤师 KDA 信息，有关对局信息界面的其他改进的讨论请移步 #41
