### ISSUE TITLE
[BUG] 外服无法通过此程序直接启动

### ISSUE THREAD

**Issue by kkplmao** [Zzaphkiel/Seraphine#363]
### 问题描述

![image](https://github.com/Zzaphkiel/Seraphine/assets/121577015/e02c8f07-55c7-47de-939d-9970d7d2bb14)
![屏幕截图 2024-05-08 231145](https://github.com/Zzaphkiel/Seraphine/assets/121577015/fa3efcc4-6524-465f-827a-bb6c80efd4a9)

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.12.2

### 客户端状态（若有）

未开启

### 您进行游戏的服务器（若有）

台服

### 出现率（若有）

未进行具体的重复测试

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
不好修，国服和外服客户端目录和启动方式应该不一样，软件没法提前知道启动的是什么服务器 😥

**Comment by Zzaphkiel** [comment]
#364 已修复该问题
