### ISSUE TITLE
[Enhancement] （可否添加一个好友列表 点击能直接查看好友战绩）

### ISSUE THREAD

**Issue by axeasy** [Zzaphkiel/Seraphine#365]
### 功能描述

想看很久没一起玩的朋友的战绩 他隐藏了 现在必须输入后缀才能查战绩

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
搜一次就能在搜索框直接点搜索记录了，感觉没必要搞得太复杂
