### ISSUE TITLE
[Enhancement] 增加自定义更换召唤师图标的功能

### ISSUE THREAD

**Issue by Furinakkk** [Zzaphkiel/Seraphine#366]
### 功能描述

或许可以实现吗
![image](https://github.com/Zzaphkiel/Seraphine/assets/169392056/c12beaed-2bbe-4119-b97c-017b93fc6af9)
没有相关计划也没关系，已经特别好用且全面了，万分感谢大佬'◡'

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Hpero4** [comment]
@Furinakkk 我先研究一下, 如果有其他工具做到了的话, 或许可以实现

**Comment by Zzaphkiel** [comment]
调查了一下，有两个接口可以 “实现” 该功能：
1. 向 `/lol-chat/v1/me`  put 一个 `{"icon": iconId}` ，就可以 “更换” 右上角的召唤师图标（就是您图片中展示的那样），但生涯里的不会更换，且鼠标放在头像上显示的仍是原来的图标。合理推断使用这种方法**别人看不见**。
2. 向 `/lol-summoner/v1/current-summoner/icon` put 一个 `{"profileIconId": iconId}`，就可以真正意义上的实现更换召唤师图标，但它**仅支持更换自己已经有的图标**。

综上，考虑到实现的意义，决定暂时不实现该功能。
