### ISSUE TITLE
给自动接收对局加入延迟时间的建议

### ISSUE THREAD

**Issue by RicharYe** [Zzaphkiel/Seraphine#37]
关于自动接收对局功能，可以考虑加个自选延时时间（但是时间在超时拒绝之前）。
因为开启自动接受对局也有人去上厕所或者短暂不在电脑面前的时间，稍微延长一点时间可以让时间充足一点。

**Comment by Zzaphkiel** [comment]
感谢反馈。

感觉可行，后面会实现的~

**Comment by Zzaphkiel** [comment]
已实现
