### ISSUE TITLE
[Enhancement] （记录闪现时间）

### ISSUE THREAD

**Issue by liangyuR** [Zzaphkiel/Seraphine#372]
### 功能描述

假如：TOP 代指上单（这里先不考虑 TOP 如何与英雄绑定）。

在聊天框中输入：TOP F

是否有API提供对局中敌方英雄的天赋装备信息？
是否提供的有客户端API来获取当前对局的聊天信息？
如果有，能否通过计算（天赋+CD鞋等）算出当前时刻开始，TOP的闪现什么时候能转好？并在转好前 10~20 将该信息输出给队友。

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
感谢反馈，您提到的两点“是否有”的答案都是**没有**，故暂无开发计划。
