### ISSUE TITLE
[E#数字ID] 根据数字ID查询召唤师战绩

### ISSUE THREAD

**Issue by Jiangguankun** [Zzaphkiel/Seraphine#374]
### 功能描述

最近的一次版本更新中加入了数字ID，能不能尝试看看，能否通过数字ID查询战绩或者查询召唤师id

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
做不到啊~
