### ISSUE TITLE
[Enhancement] 能否支持对云顶对手的查询

### ISSUE THREAD

**Issue by ilixtic** [Zzaphkiel/Seraphine#377]
### 功能描述

目前软件仅适用与峡谷，对云顶没用，希望能添加对云顶的支持，比如查询对手段位功能

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
暂无相关计划。

![QQ截图20240521230406](https://github.com/Zzaphkiel/Seraphine/assets/60383222/519bc213-a590-4de7-87b8-3272c8c1764d)

**Comment by xiaomingzzzzz** [comment]
大佬对这个问题目前看法如何~OPGG是有云顶项目的，考虑直接连API来看阵容吗 最基础的功能且好像开发量没那么大？（我猜的hh 个人感觉云顶还查战绩有点没必要了）

**Comment by xiaomingzzzzz** [comment]
好吧我看到了作者在其他帖子的回复 看起来是一个纯LOL不带云顶的软件了~
