### ISSUE TITLE
[Enhancement] 可不可以增加一个一键牛马喊话呢？

### ISSUE THREAD

**Issue by Hollowoooo** [Zzaphkiel/Seraphine#378]
### 功能描述

一键喊话上等马下等马牛马的功能

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
感谢建议，暂无相关计划（#4）。

![IMG_1031](https://github.com/Zzaphkiel/Seraphine/assets/60383222/295901e3-cb36-441d-8663-9c6543dc9bd1)
