### ISSUE TITLE
[BUG] 通过召唤师名搜索战绩时可能会卡死

### ISSUE THREAD

**Issue by weluck** [Zzaphkiel/Seraphine#379]
### 问题描述

按人名搜索，有几率软件一直请求，导致软件一直刷新，甚至别的页面都切不过去，软件一请求软件就会弹到最上层，只能重启电脑或者拼手速

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.12.2

### 客户端状态（若有）

游戏中或者房间内

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

非常低的概率会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
感谢反馈，暂时无法复现该问题。

**Comment by asd2422313947** [comment]
> 感谢反馈，暂时无法复现该问题。

目前已经可以稳定复现该问题，操作步骤：
搜索任意召唤师战绩，在转圈的过程中点开搜索下拉框，转圈完毕后立刻点击其他召唤师名字搜索战绩，然后切换窗口到其他程序，软件UI就会卡死无响应

**Comment by asd2422313947** [comment]
> 感谢反馈，暂时无法复现该问题。
两种方向解决：1.在搜索用户战绩时，设置界面组件禁止操作(不太建议这种，因为有时会一直转圈就是不显示战绩)

**Comment by asd2422313947** [comment]
> 感谢反馈，暂时无法复现该问题。

两种方向解决：1.在搜索用户战绩时，设置界面组件禁止操作(不太建议这种，因为有时会一直转圈就是不显示战绩)
2.从线程方法入手，这个可能需要重构搜索部分

**Comment by Hpero4** [comment]
#448 已修复

**Comment by Hpero4** [comment]
@asd2422313947 关于提到的一直转圈问题在测试过程中有出现, 后续会着手排查尝试修复

**Comment by Hpero4** [comment]
快速切换搜索目标时, 转圈时间很长 #448 修了
