### ISSUE TITLE
[Question] 无法观战好友

### ISSUE THREAD

**Issue by ykxhzfj** [Zzaphkiel/Seraphine#382]
### 问题描述

好友在游戏中，但观战时提示未在游戏中
![微信图片_20240529203040](https://github.com/Zzaphkiel/Seraphine/assets/42665257/7989a3db-53b2-4bb4-ae84-2ce56ca18f9b)
![微信图片_20240529203059](https://github.com/Zzaphkiel/Seraphine/assets/42665257/84b6cc24-9526-4e8e-8db1-d3be1448be91)

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
观战服务器由腾讯提供，接口由 LCU 提供；若输入正常且符合观战条件，不能观战系服务器问题。
