### ISSUE TITLE
[BUG] 对局信息友方玩家名字全部为空

### ISSUE THREAD

**Issue by asd2422313947** [Zzaphkiel/Seraphine#386]
### 问题描述

![微信图片_20240602202928](https://github.com/Zzaphkiel/Seraphine/assets/47559534/2a765b23-8e8f-4db7-9ecc-4ac59df81fa8)

### 系统信息

Windows 10

### 运行方式

在 Python 环境中直接运行源代码

### 软件版本

最新源代码

### 客户端状态（若有）

游戏内

### 复现方法（若有）

正常进入对局就会触发，而且概率很高，重开软件可以恢复正常，但是下一把又会这样

### 出现率（若有）

每次这么做大部分时候会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
感谢，已修复该问题。
