### ISSUE TITLE
[Question] 使用软件打开客户端并登录，腾讯安全中心会提示非常用环境登录

### ISSUE THREAD

**Issue by andwind1223** [Zzaphkiel/Seraphine#387]
### 问题描述

![微信图片_20240603143703](https://github.com/Zzaphkiel/Seraphine/assets/110027293/82bbedf4-2361-438d-a6fc-4d6748f197a1)

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
原因未知，可以考虑使用 WeGame 打开游戏，酌情使用 Seraphine。
