### ISSUE TITLE
[Enhancement] 按照分路自动选择英雄

### ISSUE THREAD

**Issue by LixVer** [Zzaphkiel/Seraphine#388]
### 功能描述

希望作者添加一个按分路自动选定随机英雄的功能 万分感谢

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
可以做，还请等待。

**Comment by Zzaphkiel** [comment]
仓库代码已实现该特性
