### ISSUE TITLE
[Enhancement] 能在对局信息中显示近20场的总胜率吗

### ISSUE THREAD

**Issue by q751654992** [Zzaphkiel/Seraphine#389]
### 功能描述

# 能在对局信息中显示进20场的总胜率吗
- 比如近20场赢10场, 显示胜率50%
- 感觉放在战绩和召唤师名称中间就好, 召唤师名称往上挪一下

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
暂无相关计划，见 #310
