### ISSUE TITLE
[Question] 创建并激活新的 Anaconda 环境

### ISSUE THREAD

**Issue by Ban417** [Zzaphkiel/Seraphine#392]
### 问题描述

title中这一步的代码是在哪里实现呢？

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
``` shell
conda create -n seraphine python=3.8
conda activate seraphine
```
