### ISSUE TITLE
使用卸下勋章功能后似乎直接将勋章和头衔数据清空了

### ISSUE THREAD

**Issue by 2633858554** [Zzaphkiel/Seraphine#393]
### 问题描述

使用卸下勋章功能游戏客户端设置勋章和头衔的界面自己拥有的东西全部被清空了

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

v0.12.2

### 客户端状态（若有）

大厅

### 复现方法（若有）

点击卸下勋章后 再查看自己的勋章和头衔页面

### 您进行游戏的服务器（若有）

德玛西亚

### 出现率（若有）

未进行具体的重复测试

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
正常现象，且暂时修不了
