### ISSUE TITLE
[Question] 客户端在线状态问题。

### ISSUE THREAD

**Issue by Anzi212** [Zzaphkiel/Seraphine#394]
### 问题描述

修改了离线状态后，在开局游戏或者观战他人游戏时，原本设定的离线状态又会自动显示成游戏中/观战中。
那要是想要一直隐身离线状态的话，就需要每开一局或观战后，再次手动从工具中设置离线状态，
能不能只设置一次在线状态，在开局或观战时不会再自动还原呢，因为很多时候也只想自己一个人玩会游戏，不想被好友打扰到。

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
见 #279。
