### ISSUE TITLE
希望战绩列表新增队友是否大腿标记

### ISSUE THREAD

**Issue by clearWeber** [Zzaphkiel/Seraphine#395]
### 功能描述

判断队友是否为上等马和下等马的类似标识，快速对局势做出判断，还有战绩对局中每个人的类似尽力局，甩锅局，躺赢局的标识是否可以增加

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
感谢反馈，但暂无相关开发计划。

关于 “评分” 相关功能见 #108，关于牛马和一键发送相关功能见 #189。
