### ISSUE TITLE
[BUG] 从生涯页面进入同一人的战绩查询页面不会刷新

### ISSUE THREAD

**Issue by clo5er** [Zzaphkiel/Seraphine#396]
### 问题描述

刚更新的版本 从主页战绩点进去 左侧菜单不显示刚打的最新对局 只能通过主页的战绩查看

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.13.0

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by clo5er** [comment]
重新退出软件再登录没问题 一直开着打的战绩看不到

**Comment by clo5er** [comment]
然后还有个问题 大乱斗的BUFF在哪看呢，没发现有提示的地方
![image](https://github.com/Zzaphkiel/Seraphine/assets/37649234/f159c37b-c9ec-4619-b394-dbf683b9cc27)
![image](https://github.com/Zzaphkiel/Seraphine/assets/37649234/c8a14f34-1332-42d7-826b-3dcb34817376)

**Comment by ZhengZhengyang** [comment]
FluentTranslator没有啊

**Comment by Zzaphkiel** [comment]
感谢反馈~

> 从生涯点进去搜索页面，搜索页面左侧栏不会刷新

其实这应该算是特性，因为我们在实际使用中发现，会有**在同一召唤师的生涯页面反复点击对局，跳转至搜索界面**的场景，为了性能优化角度的考虑，针对同一目标召唤师，从生涯界面跳转至搜索界面时，**并不会触发搜索界面左侧栏的刷新**。

要不要取消这个设计，感觉还需要权衡讨论一下？

> 大乱斗 BUFF 在哪里查看？

在大乱斗模式选英雄时，鼠标放在对局信息左侧的英雄头像上就能看见了。

**Comment by Zzaphkiel** [comment]
> FluentTranslator没有啊

@ZhengZhengyang 参考自述文件里的环境配置步骤。

**Comment by Zzaphkiel** [comment]
@clo5er 感觉还是从生涯界面进入搜索界面**不主动刷新**；按回车或者点击搜索栏按钮手动刷新一下合理一些。
