### ISSUE TITLE
能否有个双排提示功能

### ISSUE THREAD

**Issue by flylj999** [Zzaphkiel/Seraphine#397]
### 功能描述

容易实现吗，友方双排

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
已经实现过了，对局信息界面召唤师背景颜色相同的是组队的。

**Comment by flylj999** [comment]
这两天观察 好像都是白色啊，没有其他颜色的。。

发件人: Zaphkiel
发送时间: 2024年6月15日 14:37
收件人: Zzaphkiel/Seraphine
抄送: flylj999; Author
主题: Re: [Zzaphkiel/Seraphine] 能否有个双排提示功能 (Issue #397)

已经实现过了，对局信息界面召唤师背景颜色相同的是组队的。

**Comment by Zzaphkiel** [comment]
进入游戏后再观察
