### ISSUE TITLE
增加云顶之弈战绩查询以及一键喊话功能建议

### ISSUE THREAD

**Issue by ZzzMAA** [Zzaphkiel/Seraphine#4]
感觉可以增加一个云顶之弈的战绩查询功能，还有查询队友跟敌方战绩后可以一键喊话将信息给到队友

**Comment by Zzaphkiel** [comment]
感谢反馈。查到战绩自动喊话感觉可以有，后面会逐步实现；云顶之弈的战绩查询可能我需要再考虑一下~

**Comment by Zzaphkiel** [comment]
1、研究了一下，在游戏内直接发送消息可能涉及到对游戏进程的逆向行为，应该是实现不了直接发送的功能了，我现在的想法是查到战绩之后把战绩信息自动放到剪贴板里，进入游戏之后手动 `Ctrl + V` 粘贴发送，你觉得如何？

2、云顶之弈的战绩查询功能应该不会实现~不好意思哈~

**Comment by Zzaphkiel** [comment]
> 在游戏内直接发送消息可能涉及到对游戏进程的逆向行为[[参考]](https://stackoverflow.com/questions/17343264/how-to-read-league-of-legends-ingame-chat-in-java)，应该是实现不了直接发送的功能了，我现在的想法是查到战绩之后把战绩信息自动放到剪贴板里，进入游戏之后手动 Ctrl + V 粘贴发送

又研究了一下，我发现只有在游戏内复制的东西才可以粘贴到游戏聊天框里，所以粘贴发送可能也不行了。另外可行的方法可能是调用 `win32api` [[参考]](https://github.com/4379711/lol-helper/blob/master/src/main/java/yalong/site/utils/MyUser32Util.java)，但我不知道这种行为是不是官方所允许的。

**Comment by ZzzMAA** [comment]
我看了一下你那个参考，那是是读取游戏内消息数据，但是一键喊话不需要读取消息数据，我看之前包括wegame、盒子等平台都有一键喊话功能，官方应该有提供相应的接口，你不忙的话可以找找看。

**Comment by Zzaphkiel** [comment]
目前我只找到了 [[参考1](https://github.com/4379711/lol-helper/blob/master/src/main/java/yalong/site/utils/MyUser32Util.java)] 以及 [[参考2](https://github.com/4379711/lol-helper/issues/5)]，使用的是模拟按键 + 发送消息（使用 `win32api`）的方式

官方只给了游戏外聊天的接口，好像确实没有给游戏内聊天发送内容的接口 😥
