### ISSUE TITLE
黑名单功能

### ISSUE THREAD

**Issue by TIANCHENWEI609** [Zzaphkiel/Seraphine#400]
### 功能描述

能添加黑名单功能吗，可以添加黑名单，再匹配到时进行提示。

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
暂无开发计划。

![QQ截图20240616141730](https://github.com/Zzaphkiel/Seraphine/assets/60383222/6f5ce5e8-5501-4a2e-9c31-4e267a0d6b8b)
