### ISSUE TITLE
[Enhancement] 保存多个可选的客户端路径

### ISSUE THREAD

**Issue by kokobk** [Zzaphkiel/Seraphine#402]
### 问题描述

场景：
电脑里又有台服又有国服
玩完台服 开启萨勒芬妮 地址自动变成了台服的  实际上是想启动国服

建议优化 如果多个服务器的情况下 增加选择启动哪个 或者默认启动哪个

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
合理，感觉可以实现一下试试

**Comment by Zzaphkiel** [comment]
已实现该特性。
