### ISSUE TITLE
[Enhancement] 能否新加一个显示队友大区的功能

### ISSUE THREAD

**Issue by cypressmax** [Zzaphkiel/Seraphine#404]
### 功能描述

我希望能够在战绩显示页面队友的头像下显示其所在的大区，这样可以更好地评估双方的实力，合区以后不同区的相同段位水平还是有区别的

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
#263
