### ISSUE TITLE
[Question] 打开软件，会超出屏幕范围（即使设置最大化启动

### ISSUE THREAD

**Issue by liucheng12156** [Zzaphkiel/Seraphine#406]
### 问题描述

![image](https://github.com/Zzaphkiel/Seraphine/assets/116372247/055001dc-d4a1-4d95-a381-33c44d2f82ba)

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [x] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
因为系统 DPI 缩放过大，导致窗口也被放大得过大了。可以尝试：

1. 打开文件夹 ``C:/Users/{用户名}/AppData/Roaming/Seraphine``，
2. 打开配置文件 ``config.json``，
3. 找到 ``"DpiScale"`` 设置项，将其对应值 ``"Auto"`` 改为 ``1``。
4. 重启 Seraphine。
