### ISSUE TITLE
[BUG] 搜索战绩时有概率界面卡死无响应

### ISSUE THREAD

**Issue by asd2422313947** [Zzaphkiel/Seraphine#407]
### 问题描述

https://github.com/Zzaphkiel/Seraphine/assets/47559534/c782e852-735c-4944-a5a8-0dcd11655ed9

### 系统信息

Windows 10

### 运行方式

在 Python 环境中直接运行源代码

### 软件版本

最新源代码

### 复现方法（若有）

正常搜索战绩就有概率触发(百分之10的概率)，这个问题无法通过调试器捕捉，即使使用debug模式，也无法捕捉问题所在

### 出现率（若有）

非常低的概率会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by asd2422313947** [comment]
猜测好像是战绩获取线程阻塞了UI界面线程

**Comment by Zzaphkiel** [comment]
和 #379 重复了
