### ISSUE TITLE
使用一年多，第一次出现封号

### ISSUE THREAD

**Issue by Bedwyr111** [Zzaphkiel/Seraphine#408]
### 问题描述

使用中出现封号 9个人出现发现作弊者对局强制结束

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

 ver.0.13.0

### 日志文件

Seraphine ver.0.13.0
-----
Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 511, in __onLolClientChanged
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 439, in __onLolClientStarted
  File "app\view\main_window.py", line 421, in __changeCareerToCurrentSummoner
  File "app\lol\connector.py", line 114, in wrapper
  File "app\lol\connector.py", line 88, in wrapper
  File "app\lol\connector.py", line 380, in getCurrentSummoner
ReferenceError

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

未进行具体的重复测试

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by keaideykg** [comment]
封了多久

**Comment by BakaFT** [comment]
Issue发起者提供的信息不足以证明 `使用 Seraphine => 封号`，一个运行LOL的PC里有太多的变量可能导致ACE反作弊觉得你不对劲

另外，考虑到大部分人都分不清楚，我说一点：**客户端** 和 **游戏** 是两回事，反作弊一般仅针对后者

Seraphine 作为一个合规与 **客户端** 部分交互的工具，理论上没有任何可能导致游戏部分检测到作弊行为

请仔细思考，你是不是对游戏部分做了修改（换肤、血液补丁、挂载自定皮肤、甚至是某些软件的游戏内覆盖）？

或者你运行/开启了任何让反作弊觉得不舒服的软件（CE、OD等调试器；Procmon等系统及调试工具；甚至是某些开发工具）？


> 腾讯游戏安全中心发布《无畏契约》禁止/不建议使用的软硬件列表。在运行该游戏中，如果玩家使用以下设备或工具可能会受到惩罚。
>
> 禁止使用：
>
> 1. 硬件：DMA、分线器/桥接器、KMbox、融合器、同步器、USB盒子、带有宏脚本的鼠标等；
>
> 2. 黑客工具：CheatEngine、YDArk、PowerTool、PCHunter、PYArk、APIMonitor、ProcMon、x96dbg、Windbg、Ollydbg、ProcessHacker、ProcessMonitor和DbgPlugin等；
>
> 3. 模拟类：[按键精灵](https://xiazai.zol.com.cn/detail/35/344930.shtml)和具有恶意功能的[OBS](https://xiazai.zol.com.cn/detail/44/431905.shtml)插件等；
>
> 4. 虚拟化[软件](https://xiazai.zol.com.cn/)：[VMWare](https://xiazai.zol.com.cn/detail/4/37058.shtml)、KVM和VT-x等。
>
> 不建议使用：
>
> 1. 远控和桌面共享软件：Todesk、向日葵、[TeamViewer](https://xiazai.zol.com.cn/detail/31/308111.shtml)、AnyDesk 以及 [Steam](https://xiazai.zol.com.cn/detail/44/430273.shtml) Link 以及 NvStreamer等；
>
> 2. 截帧工具：RenderDoc以及WinPix等；
>
> 3. 模拟类：AutoHotkey, DD键鼠[驱动](https://driver.zol.com.cn/), 大漠插件, python脚本等。

**Comment by BakaFT** [comment]
说完客观的分析，我补充一些主观角度的看法

腾讯和拳头对开发者的态度十分微妙

- 这个月，在**没有任何事先告知**的情况下，拳头大批封禁了 调用某个RiotClient API的 用户（这些人借此能够得到英雄选择阶段被隐藏起来的队友ID），这完全是对用户和开发者的不尊重，尽管你找不到理由谴责他，只能在道德层面BB赖赖

- 腾讯和拳头保留最终解释权，事实是：官方的合作伙伴（Blitz.gg等）可以在惩罚其用户前前得到警告，从而整改；而各种野生工具通常只能听天由命，盼着老爷不要杀头

尽管如此，他们对 **客户端** 部分依旧十分宽松，你可以随便调用、订阅客户端的API和WS事件，这些范围内都是可以在官方社区里公开讨论的，拳头也会时常解答，只是不做额外支持

而我的客户端经常通过镜像劫持的方式注入一个DLL进去，从而修改客户端底层的一些逻辑，这远比 Seraphine 这类工具做的深入，一年多内也为遭到过任何封号处罚（有些人可能知道，这是PenguLoader)

有的人使用 PenguLoader 之后封号，跑过来问我为什么，然后交流的过程中他无意间透露自己开了换肤，还说其他号没封就封了这个，我无话可说。 这些人封号之后，只是想起来了开过的工具里面**名字最熟悉的**/**出镜次数最多**的一个罢了

当然，@Zzaphkiel 也 [没有保证完全不封号](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%A5%97%E7%9B%BE%E7%8E%AF%E8%8A%82-%EF%B8%8F) 尽管我觉得不是 Seraphine 的问题

**Comment by Zzaphkiel** [comment]
@BakaFT 的回答已经非常详细了~

~P.S. 我们的仓库的岁数还没够一年呢~
