### ISSUE TITLE
[Enhancement] （不知道能否添加一个加入自定义房间的功能，开启后一直搜索该房间名然后输入密码进入）

### ISSUE THREAD

**Issue by W105110107** [Zzaphkiel/Seraphine#409]
### 功能描述

不知道能否添加一个加入自定义房间的功能，开启后一直搜索该房间名然后输入密码进入

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
意义不大，而且这客户端摸两下就闪退了，不敢弄。
