### ISSUE TITLE
登录游戏，进入大厅就会崩溃

### ISSUE THREAD

**Issue by kksama2020** [Zzaphkiel/Seraphine#412]
### 问题描述

Seraphine ver.0.13.0
-----
Traceback (most recent call last):
  File "qasync\__init__.py", line 780, in _error_handler
  File "app\view\main_window.py", line 487, in __onLolClientStarted
  File "app\lol\aram.py", line 42, in checkAndUpdate
  File "app\lol\aram.py", line 143, in __checkUpdate
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.130

### 客户端状态（若有）

进入大厅

### 复现方法（若有）

Microsoft Windows [版本 10.0.22631.3235]
(c) Microsoft Corporation。保留所有权利。

C:\Windows\System32>wmic process WHERE name='LeagueClientUx.exe' GET commandline
没有可用实例。

C:\Windows\System32>wmic process WHERE name='LeagueClientUx.exe' GET commandline
CommandLine
e:/wegameapps/wegameapps/英雄联盟/LeagueClient/LeagueClientUx.exe "--riotclient-auth-token=ZoU9raqco9_1Ri93qVoWRg" "--riotclient-app-port=1118" "--riotclient-tencent" "--no-rads" "--disable-self-update" "--region=TENCENT" "--locale=zh_CN" "--t.lcdshost=hn1-k8s-feapp.lol.qq.com" "--t.chathost=hn1-k8s-ejabberd.lol.qq.com" "--t.storeurl=https://hn1-k8s-sr.lol.qq.com:8443" "--t.rmsurl=wss://hn1-k8s-rms.lol.qq.com:443" "--rso-auth.url=https://prod-rso.lol.qq.com:3000" "--rso_platform_id=HN1" "--rso-auth.client=lol" "--t.location=loltencent.gz1.HN1" "--tglog-endpoint=https://tglogsz.datamore.qq.com/lolcli/report/" "--ccs=https://hn1-k8s-cc.lol.qq.com:8093" "--entitlements-url=https://hn1-k8s-entitlements.lol.qq.com:28088/api/token/v1" "--dradis-endpoint=http://some.url" "--remoting-auth-token=PZe7ipT35KKg6xMCVCJE2w" "--app-port=1178" "--install-directory=e:\wegameapps\wegameapps\鑻遍泟鑱旂洘\LeagueClient" "--app-name=LeagueClient" "--ux-name=LeagueClientUx" "--ux-helper-name=LeagueClientUxHelper" "--log-dir=LeagueClient Logs" "--crash-reporting=" "--crash-environment=HN1" "--app-log-file-path=e:/wegameapps/wegameapps/英雄联盟/LeagueClient/../Game/Logs/LeagueClient Logs/2024-06-30T08-17-06_22680_LeagueClient.log" "--app-pid=22680" "--output-base-dir=e:/wegameapps/wegameapps/鑻遍泟鑱旂洘/LeagueClient/../Game" "--no-proxy-server" "--ignore-certificate-errors"

### 日志文件

[Seraphine_2024-06-30_ERROR.log](https://github.com/user-attachments/files/16042655/Seraphine_2024-06-30_ERROR.log)

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

未进行具体的重复测试

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
把 `%APPDATA%\Seraphine` 目录下的 `AramBuff.json` 删了，再重新打开 Seraphine。
