### ISSUE TITLE
[Enhancement] 能否添加·显示历史段位

### ISSUE THREAD

**Issue by ASSSSBBBBBB** [Zzaphkiel/Seraphine#415]
### 功能描述

目前软件只显示当前赛季的单双排段位与灵活段位，不能显示过往段位

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
LCU API 应该是拿不到这些数据，如果能拿到倒是感觉可以显示一下。

该 issue 暂时关闭，欢迎在该 issue 下提供可行信息获取渠道。
