### ISSUE TITLE
[Question] 突然打不开了，删除重新安装重启都没用

### ISSUE THREAD

**Issue by Tebiexihuan** [Zzaphkiel/Seraphine#416]
### 问题描述

之前一直都正常，下载了上版本也不行，就是双击后没反应

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
试试新的版本能开不能吧（关掉杀毒软件），我也没啥好办法呢 😭

**Comment by Tebiexihuan** [comment]
> 试试新的版本能开不能吧（关掉杀毒软件），我也没啥好办法呢 😭

嗯晚上回家试一下，根据我之前的测试大概率是杀毒的问题，偶尔打开会弹出一个win自动阻止的窗口，尝试关掉了自带的Microsoft Defender还是没用，和旁边我弟的电脑对比了下文件也没有被强制删除，但是有一次发现游戏秒退后自动重连了（LOL官方客户端应该没有这个功能吧？）可能插件还在某个地方运行只是没有界面？任务管理器也没找到。感谢作者回复。

**Comment by Mikank0** [comment]
最新的13.1版本使用管理员身份运行还是无法打开，甚至没有反应，想问一下是什么情况

**Comment by Tebiexihuan** [comment]
> 最新的13.1版本使用管理员身份运行还是无法打开，甚至没有反应，想问一下是什么情况

还是打不开，我电脑很少装新东西，不知道是装了什么导致的，最近的话...你有没有装植物大战僵尸杂交版？
