### ISSUE TITLE
能否在战绩查询中加入大乱斗elo积分查询

### ISSUE THREAD

**Issue by Pizzdd** [Zzaphkiel/Seraphine#418]
### 功能描述

能否在战绩查询中加入大乱斗elo积分查询

具体内容查询方法和机制内容
https://www.bilibili.com/video/BV1Ew4m1a7U6/?vd_source=93c5e4a412096787ca136d2f7f36a992
已有可以查询网站，但是不完善 
http://i.lzyumi.top/
希望作者能参看下，谢谢。

### 在提交之前，请您确认

- [x] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by axeasy** [comment]
刚想发个issues就看到你 顶一下

**Comment by Hanxven** [comment]
> ### 功能描述
> 能否在战绩查询中加入大乱斗elo积分查询
> 
> 具体内容查询方法和机制内容 https://www.bilibili.com/video/BV1Ew4m1a7U6/?vd_source=93c5e4a412096787ca136d2f7f36a992 已有可以查询网站，但是不完善 http://i.lzyumi.top/ 希望作者能参看下，谢谢。
> 
> ### 在提交之前，请您确认
> * [x]  我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

不要强人所难

**Comment by Zzaphkiel** [comment]
1. 在 WeGame 请求之前等着，请求完之后抓一下看看返回的什么东西；
2. 主动伪造 WeGame 的请求（当然还有 cookie 等用于认证的信息），获取相应的返回值。

这两件事情的难度是**完全不同**的（后者甚至可能有点不合法）。

**Comment by Pizzdd** [comment]
> 1. 在 WeGame 请求之前等着，请求完之后抓一下看看返回的什么东西；
> 2. 主动伪造 WeGame 的请求（当然还有 cookie 等用于认证的信息），获取相应的返回值。
> 
> 这两件事情的难度是**完全不同**的（后者甚至可能有点不合法）。

我以为只是直接调用，没想到这么复杂。抱歉了
