### ISSUE TITLE
[Enhancement] 战绩查询增加显示大乱斗胜率

### ISSUE THREAD

**Issue by stone00x** [Zzaphkiel/Seraphine#419]
### 功能描述

战绩查询希望增加大乱斗总场次跟胜率,或者有类似的接口可以根据ID批量查询大乱斗总场次跟胜率吗?

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
[readme](https://github.com/Zzaphkiel/Seraphine/tree/feature/opgg?tab=readme-ov-file#q%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E6%8F%90%E4%BE%9B%E5%85%B7%E4%BD%93%E6%9F%90%E6%A8%A1%E5%BC%8F--%E6%9F%90%E8%8B%B1%E9%9B%84%E6%80%BB%E5%9C%BA%E6%AC%A1%E4%BB%A5%E5%8F%8A%E6%80%BB%E8%83%9C%E7%8E%87) 里写了。
