### ISSUE TITLE
[Enhancement] 请问能否添加一个一键启动的功能

### ISSUE THREAD

**Issue by kamisugi** [Zzaphkiel/Seraphine#421]
### 功能描述

我有多个不同大区的账户，但是每次登录都需要输入密码，选择大区，请问是否会推出一键登录之类的功能呢（我不太清楚实现的难度）
注：我看了4页issue没有相同的想法

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
不能做（也不知道怎么做）。

**Comment by namekkozZ** [comment]
我最近也有这个想法，理论上可以用 pywinauto 这类windows自动化工具 来进行键盘鼠标输入来输入密码然后启动游戏，但是这种使用可能会有风险，因为密码是需要直接暴露给程序的

**Comment by BakaFT** [comment]
这是一个死题
1> 模拟输入会产生信任问题，即使这是开源的
2> 模拟协议登录是一个密码学问题，能做到的不多，做到的也有进去蹲的

至于OP提到的Cookies，和游戏登录基本无关了。目前游戏采用的是基于Oatuh的Riot Sign On验证体系，尤其是到了国服为了适配QQ/微信还多了一层。客户端理论上可以通过强行输入已经过验证得到的access token切换状态，问题是不知道怎么做。
