### ISSUE TITLE
[BUG] 自带的更新会报错

### ISSUE THREAD

**Issue by yyyL17** [Zzaphkiel/Seraphine#422]
### 问题描述

打开程序之后弹出的更新直接进行下载会直接报错
![1720881168914](https://github.com/user-attachments/assets/01535a4d-127d-44cb-86e9-3f8328a67641)

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

0.13.0

### 出现率（若有）

未进行具体的重复测试

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
![1](https://github.com/user-attachments/assets/f458ef7a-9cbe-4788-ad11-cb000b4e52ec)
