### ISSUE TITLE
[Enhancement] 黑名单功能

### ISSUE THREAD

**Issue by 110011100101** [Zzaphkiel/Seraphine#424]
### 功能描述

记录id和编号,对此id标红

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
请查看历史 issues。

![QQ截图20240719143949](https://github.com/user-attachments/assets/c8f10417-3664-44b4-a499-10a618c67c61)
