### ISSUE TITLE
[Enhancement] （跟随系统动画设置）

### ISSUE THREAD

**Issue by kuarquernull** [Zzaphkiel/Seraphine#425]
### 功能描述

跟随系统动画设置，比如我在Windows 11系统设置中关闭了“动画效果”
![image](https://github.com/user-attachments/assets/b423c612-e75a-490a-89cd-137b5ee194d9)
Seraphine可以跟随系统设置关闭动画效果。

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
工程量太大了，不是简单加个开关就能解决的，就算有很大的实用意义（我个人）也不想做 😥
