### ISSUE TITLE
[Enhancement] （发现新的项目, 希望整合此项目中） https://github.com/ping11700/LOLKit

### ISSUE THREAD

**Issue by molover02** [Zzaphkiel/Seraphine#427]
### 功能描述

发现新的项目, 整合此项目中.  https://github.com/ping11700/LOLKit
1. 比较厉害的自动配置符文, 装备 101, opgg数据源
2. 能够像上述项目, 工具窗能贴合客户端, 并一起移动.

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
仓库代码已实现 OP.GG 接入，贴合客户端移动暂无开发计划。

**Comment by molover02** [comment]
opgg 英雄rank 我看没有呢. 英雄rank排名. 强度等. 是否有此数据源, 和开发计划

**Comment by Hanxven** [comment]
这能忍住不骂人也是厉害了。
