### ISSUE TITLE
opgg 英雄rank 我看没有呢. 英雄rank排名. 强度等. 是否有此数据源, 和开发计划

### ISSUE THREAD

**Issue by molover02** [Zzaphkiel/Seraphine#428]
opgg 英雄rank 我看没有呢. 英雄rank排名. 强度等. 是否有此数据源, 和开发计划

_Originally posted by @molover02 in https://github.com/Zzaphkiel/Seraphine/issues/427#issuecomment-2252138830_

**Comment by Zzaphkiel** [comment]
请不要发布重复 issue；**仓库代码**已实现该特性。
![QQ截图20240726155614](https://github.com/user-attachments/assets/c55ee373-a097-45a0-8e02-d46d65f0a306)
