### ISSUE TITLE
修改个人在线状态问题反馈及自动选择英雄的建议

### ISSUE THREAD

**Issue by fdsffdsffds** [Zzaphkiel/Seraphine#43]
修改个人在线状态问题反馈：
1.  在线状态修改成离线 应用 之后，游戏大厅显示离线，但是在掌盟上用另一个账号查看修改后的账号还是会显示游戏在线；
2.  一局游戏进行完之后游戏大厅会重新显示在线。

自动选择英雄可不可以不直接锁定。

最后还是感谢作者提供的工具，辛苦啦！

**Comment by Zzaphkiel** [comment]
感谢支持与反馈！

1. 修改在线状态的接口只是修改了状态的**显示**，并不会让您真正地表现的像不在线一样的~而且您修改为在线状态后，进入游戏时好友也是能看到您在游戏中的
2. 感觉确实不直接锁定稍微好一点，后续会直接改成不直接锁定，或者加一个设置选项卡放在设置界面里

**Comment by Zzaphkiel** [comment]
已实现
