### ISSUE TITLE
[BUG] 锁定英雄后所选英雄与筛选分路不同时opgg界面拉取数据失败

### ISSUE THREAD

**Issue by congealPlume** [Zzaphkiel/Seraphine#430]
### 问题描述

锁定英雄后所选英雄与筛选分路不同时opgg界面拉取数据失败
![2f51feb6597de9406c798d9d84f3aeac](https://github.com/user-attachments/assets/d8e9d908-d988-434d-9d4d-4dd695203aa4)

### 系统信息

Windows 10

### 运行方式

在 Python 环境中直接运行源代码

### 软件版本

1.0.0-beta1

### 客户端状态（若有）

英雄选择

### 复现方法（若有）

比如opgg页面筛选了辅助位置  但是所选英雄为其他位置则会拉取数据失败
仅在训练模式测试

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
我也想知道怎么样才能让它“智能地”选择正确的分路，有好的想法可以提议 🥺

**Comment by congealPlume** [comment]
> 我也想知道怎么样才能让它“智能地”选择正确的分路，有好的想法可以提议 🥺

或许可以在首次加载opgg界面的时候吧所有位置的数据都获取一遍，然后拿到每个英雄拥有的位置
在锁定英雄时自动跳转到该英雄的第一个位置中（如果是排位则跳转相应位置，不在相应位置中则第一个）
毕竟匹配中真的很难“智能的”选择位置，在界面中也加入像“opgg网页”中的分路选择按钮  （或许这个按钮应该和筛选绑定？）
![2cf9a05c258a1ef3e8fa66d6b925527f](https://github.com/user-attachments/assets/d2254883-bd38-4674-adc1-411b135bc442)

**Comment by Zzaphkiel** [comment]
已通过一个更优雅的方式修复该问题
