### ISSUE TITLE
能添加在排位选人阶段就显示双排玩家吗

### ISSUE THREAD

**Issue by buheshiji** [Zzaphkiel/Seraphine#431]
### 功能描述

能添加在排位选人阶段就显示双排玩家吗

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
早期版本有这个功能，但因无法做到准确判断，把它移除了。

**Comment by Inrstning** [comment]
希望回归，真的很需要！
