### ISSUE TITLE
[Question] Edge下载1.0版本时提示检测到病毒

### ISSUE THREAD

**Issue by xiaowj** [Zzaphkiel/Seraphine#434]
### 问题描述

 Edge下载1.0版本时提示检测到病毒

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by asd2422313947** [comment]
关闭Edge浏览器的Microsoft Defender Smartscreen即可

**Comment by asd2422313947** [comment]
使用软件前，也需要关闭系统自带的杀毒以及第三方杀毒软件
