### ISSUE TITLE
[BUG] 自动接受、自动 BP、一键符文失效，对局信息界面不加载

### ISSUE THREAD

**Issue by Keyle777** [Zzaphkiel/Seraphine#435]
### 问题描述

1、对局接受，总会失效；
2、自动ban人总会失效；
3、自动选人也会失效；
4、选人页面对局，无法加载，一片空白；
5、OPGG应用符文失败。

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

v1.0.0

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

未进行具体的重复测试

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by asd2422313947** [comment]
这个问题我也遇到过，一般是换游戏账号登录的时候会出现

**Comment by Zzaphkiel** [comment]
旧版本会遇到这个问题吗？

**Comment by asd2422313947** [comment]
> 旧版本会遇到这个问题吗？

如果是几个月前的版本，不存在这个问题，如果是最近的版本，确实会这样，换号了，自动相关的功能会失效

**Comment by asd2422313947** [comment]
> 旧版本会遇到这个问题吗？

对了，还有就是自动交换楼层这个一直是失效的

**Comment by Zzaphkiel** [comment]
1. 目前我无法复现：自动接受、自动 BP 失效、对局界面不刷新、OPGG 一键符文失效
2. 目前还待测试：自动交换楼层失效

如有稳定（或高概率）复现方法请提供 🙏

**Comment by asd2422313947** [comment]
> 1. 目前我无法复现：自动接受、自动 BP 失效、对局界面不刷新、OPGG 一键符文失效
> 2. 目前还待测试：自动交换楼层失效
> 
> 如有稳定（或高概率）复现方法请提供 🙏

你可以试试在BP环节秒掉游戏，然后换号登录

**Comment by asd2422313947** [comment]
> 1. 目前我无法复现：自动接受、自动 BP 失效、对局界面不刷新、OPGG 一键符文失效
> 2. 目前还待测试：自动交换楼层失效
> 
> 如有稳定（或高概率）复现方法请提供 🙏


> 1. 目前我无法复现：自动接受、自动 BP 失效、对局界面不刷新、OPGG 一键符文失效
> 2. 目前还待测试：自动交换楼层失效
> 
> 如有稳定（或高概率）复现方法请提供 🙏

秒掉游戏之后，对局信息还是生效的，就是自动相关的部分失效了，但是重开软件就恢复正常了，看起来像是获取不到状态了一样

**Comment by Jessire** [comment]
重开软件才会生效，一键符文基本不生效，转圈经常发生，大部分出现在先打开软件后启动客户端的情况下

https://github.com/user-attachments/assets/228db998-aaef-4365-9f24-5df43215eb37

**Comment by X012C** [comment]
> 1. 目前我无法复现：自动接受、自动 BP 失效、对局界面不刷新、OPGG 一键符文失效
> 2. 目前还待测试：自动交换楼层失效
> 
> 如有稳定（或高概率）复现方法请提供 🙏

我一键符文好像没有成功过。我想要问一下这个一键符文就是跳进去之后右侧那个“设为当前符文页”按钮吗？

**Comment by banmaovo** [comment]
> > 1. 目前我无法复现：自动接受、自动 BP 失效、对局界面不刷新、OPGG 一键符文失效
> > 2. 目前还待测试：自动交换楼层失效
> > 
> > 如有稳定（或高概率）复现方法请提供 🙏
> 
> 我一键符文好像没有成功过。我想要问一下这个一键符文就是跳进去之后右侧那个“设为当前符文页”按钮吗？

我也从没成功过

**Comment by banmaovo** [comment]
![image](https://github.com/user-attachments/assets/33b7cd06-e848-48c0-9ac1-89588b5e82bb)

**Comment by banmaovo** [comment]
> ![image](https://private-user-images.githubusercontent.com/101293685/360473199-33b7cd06-e848-48c0-9ac1-89588b5e82bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzYwMzMsIm5iZiI6MTcyNDMzNTczMywicGF0aCI6Ii8xMDEyOTM2ODUvMzYwNDczMTk5LTMzYjdjZDA2LWU4NDgtNDhjMC05YWMxLTg5NTg4YjVlODJiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQxNDA4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjJlYjZmMTIxYTRiZTk5ZmYxYTYxNTlmOTc4OGFiZjI2MTMwMzk0NzFjNDliMDY0MWZjNjIxOGM2M2ZmYTQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AtAu2C4JNMq5GwLrqKgu2oSuwCAvniLYWRPKyU9R9DU)

可以跳出来opgg，但是点了应用符文客户端没反应的

**Comment by Hpero4** [comment]
各位如遇类似问题, 可以收集下Log方便我们进一步定位

**Comment by banmaovo** [comment]
> 各位如遇类似问题, 可以收集下Log方便我们进一步定位

2024-08-22 20:49:25,976 - [MainWindow] CRITICAL - Seraphine started, version: 1.0.0
2024-08-22 20:49:26,765 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-08-22 20:49:26,766 - [MainWindow] CRITICAL - Seraphine listerners started
2024-08-22 20:49:26,984 - [MainWindow] CRITICAL - Seraphine initialized
2024-08-22 20:49:27,128 - [Connector] CRITICAL - connector started, server: HN1
2024-08-22 20:52:35,643 - [MainWindow] CRITICAL - Seraphine started, version: 1.0.0
2024-08-22 20:52:36,343 - [MainWindow] CRITICAL - Seraphine interfaces initialized
2024-08-22 20:52:36,343 - [MainWindow] CRITICAL - Seraphine listerners started

log里只有这些内容，我需要调一下日志等级吗？

**Comment by banmaovo** [comment]
[Seraphine_2024-08-23_DEBUG.log](https://github.com/user-attachments/files/16728265/Seraphine_2024-08-23_DEBUG.log)
[Seraphine_2024-08-23_DEBUG_1.log](https://github.com/user-attachments/files/16728266/Seraphine_2024-08-23_DEBUG_1.log)

**Comment by GreenMope** [comment]
我更换账号以后，重上游戏重新配置自动BAN选配置都不会生效，完全不起作用

**Comment by jiuxiajingfan** [comment]
您好 使用中发现符文功能并未生效且失败后将导致程序进入假死状态
系统为win11 10.0.22631
[[日志文件Seraphine_2024-09-12_DEBUG.log](https://github.com/user-attachments/files/16978821/Seraphine_2024-09-12_DEBUG.log)](https://github.com/user-attachments/files/16978821/Seraphine_2024-09-12_DEBUG.log)

https://github.com/user-attachments/assets/7a344263-6a19-498c-8667-4ffc121872f5

**Comment by QiFenQAQ** [comment]
尝试修复DX运行库和C++组件，我是这么弄好的
