### ISSUE TITLE
[BUG]  OP.GG窗口关闭后会直接把整个程序关闭掉

### ISSUE THREAD

**Issue by 592468495** [Zzaphkiel/Seraphine#437]
### 问题描述

OP.GG窗口关闭后会直接把整个程序关闭掉

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

v1.0.0

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
请提供复现过程或视频，我无法复现该问题

https://github.com/user-attachments/assets/65cc70b5-b45e-48dd-b75a-39d97e779f38
