### ISSUE TITLE
[BUG] 斗魂竞技场预选英雄被禁用后，无法自动选择下一个

### ISSUE THREAD

**Issue by Cat0x1** [Zzaphkiel/Seraphine#439]
### 问题描述

1、预选英雄被禁后，无法自动切换下一个预选英雄，
![image](https://github.com/user-attachments/assets/dbbeb9b4-c78c-4338-98b9-191a41ae3fe1)
![image](https://github.com/user-attachments/assets/32232dc7-74d4-4473-b44c-136a7a8d658e)

2、斗魂竞技场中opgg无法显示斗魂竞技场中选择英雄，而是之前大乱斗英雄
![image](https://github.com/user-attachments/assets/0ec096e0-9dfb-4250-aaa1-ec6512a66691)

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.0.0

### 客户端状态（若有）

选择英雄中

### 复现方法（若有）

问题秒速中有完整体现

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
1. 没有跳过被 ban 英雄应该是 bug，我们找时间研究一下。
2. OPGG 窗口的刷新都是在**英雄锁定**之后，亮起是不会刷新它的。

P.S. 从你的截图上来看，好像程序的样式表出现了一些问题，重新下载一个吧

**Comment by Cat0x1** [comment]
![image](https://github.com/user-attachments/assets/0ebe5a8f-7ce5-4aaf-b6d1-996f6987a4a5)
选择英雄后也opgg也未生效，另外那个bug问题应该是禁掉英雄后，接口依旧可以选择到这个英雄但无法进行确定选择这个英雄这个操作，所以需要加一个if获取被禁英雄信息，直接跳过这个英雄选择下一个英雄。

**Comment by Zzaphkiel** [comment]
> 所以需要加一个if获取被禁英雄信息，直接跳过这个英雄选择下一个英雄

如果你看过代码，你会发现这个逻辑本身是存在的；能否复现该问题还待测试、

**Comment by Zzaphkiel** [comment]
f954bb4 修复了该问题
