### ISSUE TITLE
[BUG] （删去左右圆括号，并在此处简要描述问题）

### ISSUE THREAD

**Issue by zK0G0w** [Zzaphkiel/Seraphine#440]
### 问题描述

使用时英雄联盟客户端自动重启（重启后还是原来的界面，依旧是列队中等状态）

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.0.0

### 出现率（若有）

未进行具体的重复测试

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
大概率和我们无关。
