### ISSUE TITLE
[Enhancement] 游戏退出自动关闭工具

### ISSUE THREAD

**Issue by Watson-Bao** [Zzaphkiel/Seraphine#441]
### 功能描述

实现英雄联盟游戏退出后自动关闭Seraphine

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
考虑到实用性，暂无开发计划。
