### ISSUE TITLE
[BUG] （程序一直放在后台，第二天或者第三天。。。斗魂竞技场自动禁用英雄，以及选择英雄会失效）

### ISSUE THREAD

**Issue by Cat0x1** [Zzaphkiel/Seraphine#442]
### 问题描述

程序一直放在后台，第二天或者第三天。。。斗魂竞技场自动禁用英雄，以及选择英雄会失效，在这我的电脑会处于睡眠状态再次打开
![image](https://github.com/user-attachments/assets/33c8a1bb-9d59-4042-9810-411d225cb60f)

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.0.0

### 客户端状态（若有）

选择英雄中

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by asd2422313947** [comment]
不用的时候，建议彻底关闭，Windows的睡眠功能会让软件产生BUG

**Comment by Zzaphkiel** [comment]
和 #435 重复了
