### ISSUE TITLE
[Enhancement] 是否可以在选择英雄（未锁定的时候）就切换到对应的OPGG界面

### ISSUE THREAD

**Issue by Inrstning** [Zzaphkiel/Seraphine#444]
### 功能描述

在OPGG界面增加识别当前预选英雄的功能

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by X012C** [comment]
支持，如果匹配在第五楼，除非手动选择页面，否则没时间来没时间看。

**Comment by xiaomingzzzzz** [comment]
顶顶

**Comment by Zzaphkiel** [comment]
考虑到有些人可能会在**亮英雄的时候狂点各种英雄而不点击确定**，若每次亮不同的英雄都重新拉取数据，可能造成**网络资源的浪费**。所以当时代码实现时将其设计为点击确定之后才会拉取英雄的具体 build。

关于 “如果匹配在第五楼，除非手动选择页面，否则没时间来没时间看” ，有两种情况：

1. **轮到你选择之前，你并不知道你要选什么英雄**
   在这种情况下，即使设计为亮英雄就拉取英雄 build，也没有意义：因为你并不知道你要亮什么英雄。
2. **轮到你选择之前，你知道你要选择什么英雄**
    在这种情况下，你可以提前在 OPGG 窗口中点击你想要选择的英雄，来查看英雄 build。

综上考虑，暂时不会改变 **刷新英雄 build 窗口** 的逻辑。

**Comment by Inrstning** [comment]
可以每2~3秒检测一次英雄选择&锁定检测一次英雄选择。您觉得这样是可行的吗？我们不在意浪们费网络资源，如果是您提供接入OPGG的服务器，是否可以改成本地网络访问，并打开预选后显示build的办法。我是可以直连OPGG的。

**Comment by Zzaphkiel** [comment]
> 可以每 2~3 秒检测一次英雄选择&锁定检测一次英雄选择

Seraphine 获取英雄选择状态使用的方法是 WebSocket 订阅，而不是固定时间间隔的轮询

目前关于 **用户高频率切换亮起的英雄** 该如何解决，我没有优雅的方法。

> 如果是您提供接入OPGG的服务器，是否可以改成本地网络访问

本来就是由客户端进行的 OPGG 访问，我们没有提供网络资源，提到的**网络资源浪费**本身指的就是用户客户端的网络资源。

**Comment by xiaomingzzzzz** [comment]
那是否可以把opgg的搜索英雄给做成一级页面，这样方便搜索一些，，还有每个位置的切换能否也list出来这样能快一些（上中下野辅），因为确实存在时间很紧迫的问题

**Comment by xiaomingzzzzz** [comment]
另外我怎么感觉我选完英雄也不会自动进去 搞得我亚索买错装备0-12了2333

**Comment by xiaomingzzzzz** [comment]
突然想到如果在OPGG上增加一个刷新按钮 刷新就能获得英雄详细信息 这样是不是挺优雅的doge
