### ISSUE TITLE
[BUG] 排位模式下 锁定英雄后opgg不自动跳转该英雄界面

### ISSUE THREAD

**Issue by congealPlume** [Zzaphkiel/Seraphine#445]
### 问题描述

排位模式下 锁定英雄后opgg不自动跳转该英雄界面
几乎是必定出现 

### 系统信息

Windows 10

### 运行方式

在 Python 环境中直接运行源代码

### 软件版本

v1.0.1-beta1

### 客户端状态（若有）

英雄选择

### 日志文件

[Seraphine_2024-08-10_ERROR.log](https://github.com/user-attachments/files/16570031/Seraphine_2024-08-10_ERROR.log)

### 出现率（若有）

每次这么做大部分时候会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Hpero4** [comment]
请检查网络, 与OPGG的连接是否通畅?

**Comment by Zzaphkiel** [comment]
63e4b2a 修复了该问题
