### ISSUE TITLE
[BUG] 默认设置下，会自动拒绝交换楼层申请

### ISSUE THREAD

**Issue by converblade** [Zzaphkiel/Seraphine#446]
### 问题描述

就新版本自动同意楼层设置啥的都没动，会秒自动拒绝，就图里这个功能（我们是五排，选着选着英雄变成了狼人杀QAQ）
![image](https://github.com/user-attachments/assets/a11f68e8-6907-4cba-afcc-e24b32ccf158)

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.0.0

### 客户端状态（若有）

bp

### 复现方法（若有）

换楼层必自动取消，换英雄没试

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Ninohana** [comment]
之前的版本存在这个问题吗？

**Comment by converblade** [comment]
之前的版本没有遇见过

**Comment by Ninohana** [comment]
目前在每个选人阶段结束时，客户端会自动取消所有交换请求，在新一阶段重新可用，应先排除这个情况。

**Comment by converblade** [comment]
这我测不了呀，已经没机会再开黑打游戏了

**Comment by Ninohana** [comment]
听起来像是一个悲伤的故事。

我们会跟进，感谢反馈。

**Comment by GreenMope** [comment]
我这边打开自动接受交换楼层这个功能以后一直自动拒绝...手动不影响

**Comment by Zzaphkiel** [comment]
1b95b13 修复了该问题
