### ISSUE TITLE
[BUG] 重复搜索战绩时，有时会没反应，需要重新点好几下才会开始转圈查询

### ISSUE THREAD

**Issue by asd2422313947** [Zzaphkiel/Seraphine#449]
### 问题描述

重复搜索战绩时，有时会没反应，需要重新点好几下才会开始转圈查询

### 系统信息

Windows 10

### 运行方式

在 Python 环境中直接运行源代码

### 软件版本

最新源代码

### 出现率（若有）

差不多一半的情况会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Hpero4** [comment]
@asd2422313947  #450 修了

**Comment by asd2422313947** [comment]
> @asd2422313947 #450 修了

个人主页背景更换功能貌似出问题了，点任意英雄头像就会触发异常崩溃提示
Seraphine ver.1.0.1-beta1
-----
Traceback (most recent call last):
  File "C:\hj\lib\site-packages\qasync\__init__.py", line 780, in _error_handler
    task.result()
  File "C:\Seraphine-main\app\components\message_box.py", line 465, in __onChangeSplashes
    url = await connector.getChampionSplashes(skinItem[1], False)
  File "C:\Seraphine-main\app\lol\connector.py", line 116, in wrapper
    raise exce
  File "C:\Seraphine-main\app\lol\connector.py", line 88, in wrapper
    res = await func(*args, **kwargs)
  File "C:\Seraphine-main\app\lol\connector.py", line 521, in getChampionSplashes
    with open(image, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'app/resource/game/splashes/1000_uncentered.jpg'

**Comment by Hpero4** [comment]
@asd2422313947 另开一个issue吧

**Comment by asd2422313947** [comment]
> @asd2422313947 感谢反馈 另开一个issue吧

好的

**Comment by asd2422313947** [comment]
> @asd2422313947 #450 修了

有反应是有反应了，好像不会查询最新的战绩，就是gamtab不会刷新新数据

**Comment by asd2422313947** [comment]
> @asd2422313947 #450 修了

昨天我试了一下，比如我看某一个好友的战绩，第一次搜索，然后等他打完我再次通过搜索战绩方式去刷新gamtab，但是不会刷新，我只能通过切换搜索目标，比如搜索好友A的战绩，然后再搜索好友B的战绩，以此达到刷新的目的

**Comment by asd2422313947** [comment]
> @asd2422313947 #450 修了

昨天我试了一下，比如我看某一个好友的战绩，第一次搜索，然后等他打完我再次通过搜索战绩方式去刷新gamtab，但是不会刷新，我只能通过切换搜索目标，比如搜索好友A的战绩，然后再搜索好友B的战绩，以此达到刷新的目的

**Comment by Hpero4** [comment]
@asd2422313947 逻辑是这样写的, 后面考虑改改

**Comment by Hpero4** [comment]
@asd2422313947 修了 https://github.com/Zzaphkiel/Seraphine/pull/450#issuecomment-2295676403
