### ISSUE TITLE
[BUG] 个人主页背景图更换功能出错

### ISSUE THREAD

**Issue by asd2422313947** [Zzaphkiel/Seraphine#451]
### 问题描述

Traceback (most recent call last):
File "C:\hj\lib\site-packages\qasync_init_.py", line 780, in _error_handler
task.result()
File "C:\Seraphine-main\app\components\message_box.py", line 465, in __onChangeSplashes
url = await connector.getChampionSplashes(skinItem[1], False)
File "C:\Seraphine-main\app\lol\connector.py", line 116, in wrapper
raise exce
File "C:\Seraphine-main\app\lol\connector.py", line 88, in wrapper
res = await func(*args, **kwargs)
File "C:\Seraphine-main\app\lol\connector.py", line 521, in getChampionSplashes
with open(image, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'app/resource/game/splashes/1000_uncentered.jpg'

### 系统信息

Windows 11

### 运行方式

在 Python 环境中直接运行源代码

### 软件版本

最新源代码

### 复现方法（若有）

点击任意英雄头像切换背景时，就会报错

### 出现率（若有）

未进行具体的重复测试

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Hpero4** [comment]
@asd2422313947 感谢反馈   请问必现吗？还是只出现一次？

**Comment by asd2422313947** [comment]
> @asd2422313947 感谢反馈 请问必现吗？还是只出现一次？

必定出现，但是有个变量就是，我用的账号是一个没有英雄的账号，尝试去设置背景图片

**Comment by Hpero4** [comment]
@asd2422313947  怪事  #433  测试时也是用的新账号（未创建角色）

**Comment by asd2422313947** [comment]
> @asd2422313947 怪事 #433 测试时也是用的新账号（未创建角色）

我当时是想设置个名人堂阿狸的背景签名皮肤，点阿狸的头像之后是没有图片预览的，应用也不生效，然后我在想设置别的英雄背景图片，就点头像就报错了，但是点阿狸的头像不会报错

**Comment by asd2422313947** [comment]
> @asd2422313947 怪事 #433 测试时也是用的新账号（未创建角色）

![Uploading 错误.png…]()

**Comment by asd2422313947** [comment]
![Uploading 错误.png…]()

**Comment by asd2422313947** [comment]
感觉是请求不到图片导致的错误

**Comment by Hpero4** [comment]
@asd2422313947 少了个逗号 🥹 ![image](https://github.com/user-attachments/assets/87ff092b-c888-4690-9796-30b6afb129d9)

**Comment by Hpero4** [comment]
#450 修了

**Comment by asd2422313947** [comment]
> @asd2422313947 少了个逗号 🥹 ![image](https://private-user-images.githubusercontent.com/40506420/358846199-87ff092b-c888-4690-9796-30b6afb129d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4OTkzOTcsIm5iZiI6MTcyMzg5OTA5NywicGF0aCI6Ii80MDUwNjQyMC8zNTg4NDYxOTktODdmZjA5MmItYzg4OC00NjkwLTk3OTYtMzBiNmFmYjEyOWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDEyNTEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MzY5OThjMWM4MjM4MjdhYTVjNjE4NzMxNGUxNmQxMmIwYjI1MTg0NTUwODczYmU3NTNhOGFjZDk3YTU3ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EAdhFfyhRLJ_1NWphn16kAF-4-bOmvQ8Mv2l4U96Ygs)

过于离谱

**Comment by Zzaphkiel** [comment]
> 过于离谱

挺正常的，我代码里也写过不少 typo 😆
