### ISSUE TITLE
[Enhancement] 选择英雄后OPGG能直接也自动进入该英雄推荐设施

### ISSUE THREAD

**Issue by xiaomingzzzzz** [Zzaphkiel/Seraphine#452]
### 功能描述

既然能获取到我选了什么英雄，那么OPGG同步进入详情似乎会更好

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
和 #444 重复了

**Comment by xiaomingzzzzz** [comment]
ok i slowly ~~ty i delete
