### ISSUE TITLE
[BUG] （开启Clash verge 显示拉取公告失败）

### ISSUE THREAD

**Issue by Yangless** [Zzaphkiel/Seraphine#453]
### 问题描述

开启Clash verge 显示拉取公告失败，但是战绩功能正常；使用通过基于进程名称的规则PROCESS-NAME还是无法拉取公告，拉取公告走的不是该应用吗？

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

v1.0.0

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Ninohana** [comment]
尝试：
1. 同时在Seraphine中设置代理
2. 检查防火墙设置（Github相关）
3. 检查host文件（Github相关）

**Comment by Yangless** [comment]
你好，Github浏览器访问正常；Seraphine中设置代理端口不起作用；并且在clash的连接中看不到该应用连接。
