### ISSUE TITLE
[Enhancement] opgg数据显示英雄技能冷却时间

### ISSUE THREAD

**Issue by qweazxcsdrtygvbn** [Zzaphkiel/Seraphine#454]
### 功能描述

opgg页面中有标注英雄技能的冷却时间，是否能加入到本软件中

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
太麻烦了，感觉意义也不是很大 😵‍💫
