### ISSUE TITLE
[BUG] tasklist returned non-zero exit status 3221225477.

### ISSUE THREAD

**Issue by asukamm** [Zzaphkiel/Seraphine#456]
### 问题描述

程序出错：Seraphine ver.1.0.0
-----
Traceback (most recent call last):
  File "app\lol\listener.py", line 32, in run
  File "app\common\util.py", line 158, in getLolClientPids
  File "subprocess.py", line 415, in check_output
  File "subprocess.py", line 516, in run
subprocess.CalledProcessError: Command 'tasklist /FI "imagename eq LeagueClientUx.exe" /NH' returned non-zero exit status 3221225477.

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

v1.0

### 客户端状态（若有）

闲置中

### 复现方法（若有）

双击打开即出现

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

未进行具体的重复测试

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by BakaFT** [comment]
注意到 `hex(3221225477)`=`'0xc0000005'`

可能相关 #367

**Comment by Zzaphkiel** [comment]
和 #367 重复了，都是因为第一次尝试使用 tasklist 的时候没报错，所以我们认为它可以正常工作，但之后的某次 tasklist 调用却报错了。
