### ISSUE TITLE
[Question] （是否算第三方插件）

### ISSUE THREAD

**Issue by wenlusama** [Zzaphkiel/Seraphine#457]
### 问题描述

看了前面的问题，我也是属于的行为异常，他给的理由是对局异常 账号风险 第三方插件残留等，我不是很理解为什么会出现行为异常，是他把这个软件算成第三方插件吗，罗技那个软件我也没开，实在想不出什么问题
/(ㄒoㄒ)/~~
在更新前保持去年九，十月份的版本没出现此问题，去年那个不能用之后换成上个月下载的新版后今天突然来这么一下
是单纯问下是否算第三方插件才算我行为异常，我也只用这个查战绩，打开opgg
其他也没开

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
肯定算第三方插件呢
