### ISSUE TITLE
台服的客户端能使用吗

### ISSUE THREAD

**Issue by 2324237950** [Zzaphkiel/Seraphine#46]

**Comment by Zzaphkiel** [comment]
没试过，不过我猜应该能用

**Comment by Zzaphkiel** [comment]
没试过，不过我猜应该能用

**Comment by 2324237950** [comment]
![image](https://github.com/Zzaphkiel/Seraphine/assets/55741014/6c062a0b-e6fa-425a-a80e-63e0333be51c)
这是我客户端安装的路径
![image](https://github.com/Zzaphkiel/Seraphine/assets/55741014/aaa59b00-3b82-4baa-9398-3369e12211ef)
在Seraphine 里看不到对应的应用程序，这是什么原因呢

**Comment by Zzaphkiel** [comment]
你可以先试试先登录客户端，再打开 Seraphine，它也许能自动设置路径（至少国服可以）

或者你可以在打开 Seraphine 的时候手动登录客户端，也是一样的效果~

P.S. 设置客户端路径并不是那么 “必要”，它只是为了能让程序的 “打开客户端” 功能可以使用罢了
