### ISSUE TITLE
[Question] （大乱斗隐藏分）

### ISSUE THREAD

**Issue by I-want-a-fish** [Zzaphkiel/Seraphine#461]
### 问题描述

听说大乱斗有隐藏分了，可以提供一下查询的功能吗，感谢

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
#339

**Comment by BakaFT** [comment]
如果是WeGame的ELO分，你听说得有点晚 https://github.com/Hanxven/LeagueAkari/issues/79#issuecomment-2263563020
这个在我工具视频 (https://www.bilibili.com/video/BV1BKaHecEAP) 发出来的第二天就已经挂了

如果是指随便找个算卦的给你算的ELO分，我觉得你不必陷入一种 **一定要量化游戏数据** 的误区
每个人都可以设计一个算法，通过输入游戏数据得到一个数字，准不准是一回事，信不信又是一回事
你信，那它就是真的，你不信，它就算是从WeGame偷的算法实现，也是假的。当算法得到大部分人认可且本身具备一定可信度时，它就成了多玩盒子战斗力。

不过，多玩盒子当时有自己大量的数据支撑才使得算法相对可靠，你觉得现在那些仅用一把数据就能算出来ELO的服务可靠吗？

如果你非要找一个什么新时代多玩盒子战斗力
如果在你被**坑完**了一把之后，你**再查**一下坑比的ELO会让你开心
如果你觉得仅仅基于**一把**的数据算出来的ELO分数准确
有的，现在有个人正卖呢，去找他买，你开心他也开心
