### ISSUE TITLE
[Question] 封号担忧——英雄选择阶段的Lobby Reveal行为

### ISSUE THREAD

**Issue by WordlessMeteor** [Zzaphkiel/Seraphine#463]
### 问题描述

1. 我的国际服账号之前因为使用过一些第三方工具而导致永久封禁，且机器被封禁4个月。当时我在留言中反复强调，自己的设备上只有OP.GG和LeagueTavern，没有其它换肤和脚本软件。与客服磋商无果，从此电脑上卸载了一切无关的软件，只保留了OP.GG。\
我注意到在国服使用的时候，可以看英雄选择阶段队友的战绩。这个行为在国际上称为[Lobby Reveal]。
![image](https://github.com/user-attachments/assets/f995d4a9-204a-449d-851b-e320affcb4c1)
拳头开发者表示[明确要封禁这种行为的执行者](https://x.com/RiotK3o/status/1792706933952311352)。首犯2周，再犯可能就是永久飞机票。\
![image](https://github.com/user-attachments/assets/bb7c9d8f-3a11-4bd1-b6ed-52075819a2f3)
我在观看一位国服的主播直播时，发现这个软件允许在英雄选择阶段看队友是不是一页红战绩。请问这个软件在国际服使用的时候，会对英雄选择阶段的查队友战绩的功能有约束吗？我在自己的代码中是选择直接跳过这部分代码，等待进入游戏后才允许进行队友战绩的查询。因为不想自己尝试，所以想先向您问清楚。\
![image](https://github.com/user-attachments/assets/40ffb695-73a3-43f8-a118-430dd57d229f)
2. 另外，请问这款软件除了Lobby Reveal以外，有没有其它潜在的封号风险？\
3. 请问这款软件有比较干净的卸载工具吗？是直接删除整个文件夹就行吗？问这个问题是因为担心可能存在注册项或临时文件等的残留。
以下是和客服的磋商过程。

----
![image](https://github.com/user-attachments/assets/d96ce650-2a60-4bfe-99ab-b8fce8008ed0)

----
![image](https://github.com/user-attachments/assets/7a403e9f-d433-4f0b-af82-e03eb29a65ee)

----
![image](https://github.com/user-attachments/assets/0955bc26-221c-4f6e-847b-e387c2264176)

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Ninohana** [comment]
你好。
你所提到的“大厅揭露”功能我认为是不违规的，当然这最终取决于官方的解释。
Seraphine 提供的查询完全是基于客户端所暴露的接口，如果官方认为这是一种违规使用，完全可以暂停或是移除相关接口。
作为一个玩家，对局前关心队友信息乃至于对手的信息是一种合理的诉求(当然对手的信息目前无法获取)，一定程度上可以避免出现“一面倒”的情况，这有助于提高对局的质量。
早在 Seraphine 未诞生的时候，就已经有玩家通过召唤师名称手动查询玩家“成分”，Seraphine 只是简化了这一过程而已。

**Comment by Ninohana** [comment]
另外我了解到非马服是查不到队友信息的，也没有用任何技术手段绕过，大厅揭露只在马服有效。

**Comment by WordlessMeteor** [comment]
拳头对于Lobby Revealer的管制，其实我也捉摸不透。首先，LCU API里有相应的接口，好像是允许的。但是现在国际服的单/双排英雄选择阶段，非预组队的队友信息都是用代号来称呼的，比如锋喙鸟、石甲虫之类的。这又表明拳头其实不想让玩家在房间内了解到队友的身份信息，所以真因为这个被封也不冤。但是国服的身份信息又都是开放的。当然腾讯和拳头毕竟是两个制度。\
反正官方的解释是用了就封。当然是**检测到**用了就封。我比较疑惑的一点就是我调用LCU API，它能检测出来什么？无非就是一个网站，我甚至可以在浏览器里用127.0.0.1的网站去打开，不知道是不是打开一下它就能标记我。抱歉因为我对这方面不熟悉，所以有很多疑问和好奇，啰里啰嗦说了这么多。\
官方的解释虽然是用了就封，但是在下面的评论里，官方又说实际惩罚对象的恶劣性远远逾之。
![image](https://github.com/user-attachments/assets/2d83d090-68b0-4481-9068-4d8779f63af8)

**Comment by Zzaphkiel** [comment]
在外服调 LCU API 也不能在 BP 阶段看到队友信息（如 puuid 等）吧？

**Comment by WordlessMeteor** [comment]
哦哦这样的话应该就没问题了。有机会的话去观察一下接口数据的变化，看是不是puuid被obfuscated了。\
那么还有一个问题，就是这个软件如果要卸载的话，有什么比较纯净的手段吗？直接删文件夹就行吗？

**Comment by Zzaphkiel** [comment]
`%AppData%/Seraphine` 里放了设置文件和一些资源缓存

**Comment by WordlessMeteor** [comment]
那请问有什么注册项吗？并且可以麻烦作者添加一个卸载程序，撤销打开软件时做的改动吗？自己删可能还是有些麻烦。

**Comment by Zzaphkiel** [comment]
> 那请问有什么注册项吗？并且可以麻烦作者添加一个卸载程序，撤销打开软件时做的改动吗？自己删可能还是有些麻烦。

为什么你这么怀疑我们有写注册表呢🥲（看代码不就能看到我们在做什么了嘛），“卸载“ 时删掉文件夹就行了

如果你使用了 “锁定游戏设置” 功能，那么你可能需要手动更改 LOL 设置文件读写属性以 “撤销软件做的改动”（见 readme 参考资料部分），但 “提供卸载程序” 我认为是没必要的。

**Comment by WordlessMeteor** [comment]
好的好的。对不起没仔细看过。我只是觉得卸载程序是一个锦上添花的功能，起码让用户觉得，用了这个卸载程序就可以放心地继续使用设备了。\
最够感谢作者和 @Ninohana 两位大佬的解答！

**Comment by Zzaphkiel** [comment]
感觉可以把 “如何卸载” 写在 readme 里，感谢您的建议。

**Comment by BakaFT** [comment]
Lobby reveal 是借用RiotClientServices 暴露的API实现的，这个API的原本用途应该是支持RC中的聊天功能

这个API存在已久且拳头一直不做任何声明，也不修复，直到前两个月的ban wave

那次ban wave 主要针对的是Kbotext用户，因为大部分人就是用这个才做到了lobby reveal，值得注意的是，拳头似乎动用了vanguard去做特征检测，就算你不打游戏只开客户端挂着还是会被封

另外，还有部分个例使用其他方式调用RCS的那个API也被封了，这说明可能还存在服务端的纪录，或者基于遥测的分析


简单来说的话，只要不碰RCS那个接口，应该是没问题的

**Comment by BakaFT** [comment]
基于Seraphine的实现来看，如果用在外服排位应该是无法获取信息的，不应有这些顾虑

**Comment by WordlessMeteor** [comment]
请教一下，Riot Client有聊天功能吗？我以为聊天功能是内置于League Client的，就好比点开一个好友聊天一样。\
然后RiotClientServices的API和LeagueClient的API是不一样的吗？如果不一样，那么通过lcu_driver获取到的connection就是与LeagueClientUx.exe进行通信吗？\
我那次被封了好几个号，跟这个所谓Kbotext是没有关系的，设备上没安装过这个软件，只有LeagueTavern、OP.GG，可能还有一个观战工具。当然也可能有我自己的脚本，但我自己的脚本在通信时都是使用lcu_driver库的。

**Comment by BakaFT** [comment]
https://github.com/Zzaphkiel/Seraphine/issues/463#issuecomment-2340917339
这里第一张图里的推文说的即是，RC中可以看到好友的在线状态，以及，如果你在英雄选择，你可以看到同房间的人的状态，这是没有做名字隐藏的。至于聊天，我不知道，但是状态是有的


英雄联盟的Chat服务依旧基于XMPP，LC和RC都可以成为XMPP前端，他们背后完全可以是同一个XMPP服务器。掌上无畏契约可以用手机和游戏里的聊天，外服的riot mobile应该也可以，他们大概率也实现了XMPP从而做到聊天（Riot Mobile也许就是RC支持XMPP的原因之一，可以随时聊天)

LeagueTavern不包含RCS调用，这个软件很早了，当时都没这回事。我不能从你的描述里判定到底是什么让你封号

**Comment by WordlessMeteor** [comment]
好的了解，感谢指导👍
