### ISSUE TITLE
[Enhancement] 侧边栏固定

### ISSUE THREAD

**Issue by WordlessMeteor** [Zzaphkiel/Seraphine#464]
### 功能描述

现在侧边栏在单击一下三杠按钮之后，再单击侧边栏以外的任意部分，侧边栏会收回，有的时候看字不太方便。请问有办法做到侧边栏固定吗？
![image](https://github.com/user-attachments/assets/acc3c227-a82b-43e6-9b0b-6b9fb4add5cf)
能不能做成Windows自带的UWP应用那样，点一下三杠表示固定侧边栏，再点一下取消固定？
![image](https://github.com/user-attachments/assets/f5b411ae-56f9-4cc7-b250-4fc898d18403)

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
暂无实现计划，目前收起侧边栏的逻辑是符合直觉的；且本身侧边导航栏并没有多少文字，图标也足以表明子页面内容
