### ISSUE TITLE
[Enhancement] SGP 地址获取，platformId 获取 提供

### ISSUE THREAD

**Issue by ekoooo** [Zzaphkiel/Seraphine#467]
### 功能描述

Hello, 看源码调用 SGP 接口地址是手动根据 platformId 判断拼接的，其实可以调用 LCU 接口获取：

有 SGP 地址，platformId 无所谓了

SGP: `/lol-platform-config/v1/namespaces/PlayerPreferences/LcuPurchaseWidget`
platformId: `/lol-platform-config/v1/namespaces/LoginDataPacket/platformId`

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by BakaFT** [comment]
第一个应为 `/lol-platform-config/v1/namespaces/PlayerPreferences`
![image](https://github.com/user-attachments/assets/fa2bcdf1-5046-47d5-865e-ef18e2575f2f)

**Comment by ekoooo** [comment]
> 第一个应为 `/lol-platform-config/v1/namespaces/PlayerPreferences/ServiceEndpoint`
> 
> ![image](https://private-user-images.githubusercontent.com/8694498/368413384-5b20ad51-651d-4984-9763-d1037e491e95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MzI0NDEsIm5iZiI6MTcyNjYzMjE0MSwicGF0aCI6Ii84Njk0NDk4LzM2ODQxMzM4NC01YjIwYWQ1MS02NTFkLTQ5ODQtOTc2My1kMTAzN2U0OTFlOTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MThUMDQwMjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTliNDc0MzhmZmRmZmUwNDI0YjY2NTYyNGQxOTNiNDVjMGFiMjhiNzU5YmExYjk4NjhhOWRjNTg4MDU3NTY5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZaBMBZX9caGWYHxiK7Ia8yuzOWW1AS_IU-K2iX1jFlI)

是的，国服这个配置刚好是对应得上，外服我测试了 台服，地址不行。

**Comment by Zzaphkiel** [comment]
这样做比现在的做法好在哪里了呢 😵‍💫？

**Comment by Zzaphkiel** [comment]
还是感谢您的提议🫡
