### ISSUE TITLE
显示程序出现异常

### ISSUE THREAD

**Issue by Nantrees** [Zzaphkiel/Seraphine#468]
### 问题描述

![Image_1726488117492](https://github.com/user-attachments/assets/aeda7c8a-68d8-466d-aa8a-eac45031c8ed)
Seraphine ver.1.0.0
Traceback (most recent call last):
File "app\olVistener.py", line 32, in run
File "app\common\util.py", line 158, in getLolClientPids File "subprocess.py", line 415, in check_output File "subprocess.py", line 516, in run
subprocess.CalledProcessError: Command 'tasklist /FI "imagename eq LeagueClientUx.exe" /NH' returned non-zero exit status 1.

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
同 #456
