### ISSUE TITLE
也许可以像添加opgg一样添加tactics.tools？（后者是一个有云顶之弈数据的网站）

### ISSUE THREAD

**Issue by sunteng1** [Zzaphkiel/Seraphine#469]
### 功能描述

希望可以有云顶之弈相关的数据可供查看
题外话：seraphine是我用过最棒的软件OvO

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
感谢支持，是可以 “像添加 OPGG 一样添加 tactikc.tool” ，但也意味着其需要和添加 OPGG 相当的工作量。况且本身 Seraphine 就没有考虑过实现任何云顶之弈相关的功能 🥲
