### ISSUE TITLE
无法连接客户端

### ISSUE THREAD

**Issue by wilson0312** [Zzaphkiel/Seraphine#47]
你好，感谢项目开发及分享
目前我使用release版本的exe可执行文件启动插件，游戏客户端启动后一直处于 客户端连接中 的状态，无法正常使用功能。
游戏安装在C盘，是否与此有关

**Comment by Zzaphkiel** [comment]
感谢反馈。和游戏装在哪里应该没啥关系，您或许可以尝试重新下载并解压程序，同时注意不要被杀毒软件误删了什么东西~

**Comment by MX2557** [comment]
你好，我也是反馈相同的问题，同一个号，登录在“艾欧尼亚”区一直处于 客户端连接中 的状态，无法正常使用功能。登录在其他区就能正常使用。是什么原因导致的呢，有录制好视频，请问能否发邮箱给你看看呢。

**Comment by Zzaphkiel** [comment]
应该不是我们的程序导致的，只能暂时等待英雄联盟那边修复了~

**Comment by wilson0312** [comment]
重新下载解压后没问题了 对比了md5也是一样的 不知道什么问题 谢谢啦
