### ISSUE TITLE
[BUG] 当调整了缩放比例，并且与系统缩放比例不同时，部分选项无法正常显示

### ISSUE THREAD

**Issue by JackShrINe** [Zzaphkiel/Seraphine#471]
### 问题描述

我的系统默认缩放比例为150%，我把seraphine调成了125%。当我点开某些下拉菜单时，内容没有正常显示。

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.0.3？

### 复现方法（若有）

将系统默认缩放比例设置为150%，把seraphine调成了125%。点开下拉菜单

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
应该是 UI 组件库的问题
