### ISSUE TITLE
[BUG] 新版观战拉起游戏后，软件对局信息无反应，不加载敌我战绩

### ISSUE THREAD

**Issue by asd2422313947** [Zzaphkiel/Seraphine#472]
### 问题描述

最新源代码的新版观战由于跳过LCU客户端直接使用命令行启动游戏进程，导致软件无法检测游戏状态，不能加载对局信息

### 系统信息

Windows 10

### 运行方式

在 Python 环境中直接运行源代码

### 软件版本

最新源代码

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by asd2422313947** [comment]
还有一个问题，新版观战，虽然可以直接拉起观战无需等待，但是进入加载之后必定黑屏或者卡在加载百分之0几分钟然后报错，然后再次拉起观战就可以正常观看，但是这就说明，即使跳过LCU客户端拉起游戏进程观战，游戏服务器还是有2分左右的录像延迟，不到时间是看不了观战的

**Comment by asd2422313947** [comment]
还有一个，新版观战是英文的，不是中文

**Comment by Zzaphkiel** [comment]
看起来可以加一个选项，让用户手动选择拉起方式

**Comment by Ninohana** [comment]
#466 提到过：

这种方式不会经过客户端，直接拉起观战服务，所以不会加载战绩。相对的，使用这种方式可以同时观战不同的人，只要你内存足够大。

至于界面是英文，需要传递额外参数，觉得没必要就没加，都看的明白。

**Comment by Zzaphkiel** [comment]
> 至于界面是英文，需要传递额外参数，觉得没必要就没加，都看的明白。

可能存在的问题是在显示中文召唤师名字的时候，会显示方块

**Comment by Ninohana** [comment]
> > 至于界面是英文，需要传递额外参数，觉得没必要就没加，都看的明白。
> 
> 可能存在的问题是在显示中文召唤师名字的时候，会显示方块

并不会哦，可以正常显示，Win11。

**Comment by asd2422313947** [comment]
其实这种方式没有真正解决观战延迟问题，因为直接拉起观战，会报错，用户体验很差，不如之前的LCU客户端拉起方式

**Comment by Zzaphkiel** [comment]
> > 可能存在的问题是在显示中文召唤师名字的时候，会显示方块
> 
> 并不会哦，可以正常显示，Win11。

明白了，看来保留两种方式，加一个选项让用户手动选择就可以了

**Comment by asd2422313947** [comment]
> > > 可能存在的问题是在显示中文召唤师名字的时候，会显示方块
> > 
> > 
> > 并不会哦，可以正常显示，Win11。
> 
> 明白了，看来保留两种方式，加一个选项让用户手动选择就可以了

赞同

**Comment by Ninohana** [comment]
> 其实这种方式没有真正解决观战延迟问题，因为直接拉起观战，会报错，用户体验很差，不如之前的LCU客户端拉起方式

我以为就我这边这样，看来确实是个问题，可能需要通过对局创建时间去加一个判断。

我赞成保留两种观战方式。

**Comment by asd2422313947** [comment]
> > 其实这种方式没有真正解决观战延迟问题，因为直接拉起观战，会报错，用户体验很差，不如之前的LCU客户端拉起方式
> 
> 我以为就我这边这样，看来确实是个问题，可能需要通过对局创建时间去加一个判断。
> 
> 我赞成保留两种观战方式。

其实LCU客户端UI还能套娃观战，观战正在观战的用户，不知道LCU接口有没有预留

**Comment by Zzaphkiel** [comment]
3148a2a
