### ISSUE TITLE
[Question] （删去左右圆括号，并在此处简要描述问题）查不到自定义的战绩

### ISSUE THREAD

**Issue by Zz-mzz** [Zzaphkiel/Seraphine#474]
### 问题描述

很想查自定义的战绩求求了，研究这个网站都研究了几天，群也满了，终于弄明白怎么提交反馈了，球球了这真的很重要

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
感谢支持。#473
