### ISSUE TITLE
[BUG] 确认对局阶段，自动确认对局失效。英雄选择阶段，自动选择英雄功能失效。

### ISSUE THREAD

**Issue by QiaQia8** [Zzaphkiel/Seraphine#475]
### 问题描述

确认对局阶段，自动确认对局失效。英雄选择阶段，自动选择功能失效。需要重启Seraphine主程序，重启后还是有概率功能失效。

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.0.0

### 客户端状态（若有）

选择英雄中

### 出现率（若有）

每次这么做大部分时候会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
和 #435 重复了
