### ISSUE TITLE
[BUG]  对局开始后不会加载敌方数据

### ISSUE THREAD

**Issue by homerLL** [Zzaphkiel/Seraphine#476]
### 问题描述

现在进入对局后不会加载敌方战绩，只能看到队友的数据，没有敌方的数据。

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.0.0

### 客户端状态（若有）

游戏中

### 复现方法（若有）

开一局单双排排位进入游戏

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
不出意外应该是间歇性的，等会应该就行了
