### ISSUE TITLE
[BUG] （删去左右圆括号，并在此处简要描述问题）

### ISSUE THREAD

**Issue by ImViper** [Zzaphkiel/Seraphine#478]
### 问题描述

OP.GG 无法正确识别游戏模式

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.0.0

### 客户端状态（若有）

选择英雄

### 复现方法（若有）

游玩无限乱斗时，op.gg首选的是极地大乱斗

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
目前还做不到在 BP 阶段判断游戏模式，所以暂时没法解决
