### ISSUE TITLE
[BUG] 参数浮点数错误

### ISSUE THREAD

**Issue by 1nTooDeep** [Zzaphkiel/Seraphine#480]
### 问题描述

/app/viewopgg_window.py中504行调用的QRect方法 和 app/common/style_sheet.py 调用的 QColor.fromRgb方，参数都不可以为浮点数：
app/common/style_sheet.py：
TypeError: arguments did not match any overloaded call:
  fromRgb(rgb: int): argument 1 has unexpected type 'float'
  fromRgb(r: int, g: int, b: int, alpha: int = 255): argument 1 has unexpected type 'float'
  /app/viewopgg_window.py：
  TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(aleft: int, atop: int, awidth: int, aheight: int): argument 1 has unexpected type 'float'
  QRect(atopLeft: QPoint, abottomRight: QPoint): argument 1 has unexpected type 'float'
  QRect(atopLeft: QPoint, asize: QSize): argument 1 has unexpected type 'float'
  QRect(a0: QRect): argument 1 has unexpected type 'float'

强制转换可以解决这个问题。

### 系统信息

Windows 10

### 运行方式

在 Python 环境中直接运行源代码

### 软件版本

1.0.1-beta2

### 复现方法（若有）

启动时

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
#481
