### ISSUE TITLE
lol客户端更新到14.20后报错

### ISSUE THREAD

**Issue by Wongboo** [Zzaphkiel/Seraphine#484]
### 问题描述

“请求 API getSummonerGamesByPuuid 服务器返回了不正常内容，可能其正在维护中”
服务器已维护完毕

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.0.0

### 客户端状态（若有）

排位

### 日志文件

[Seraphine_2024-10-10_ERROR.log](https://github.com/user-attachments/files/17329540/Seraphine_2024-10-10_ERROR.log)

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
和 #483 重复了
