### ISSUE TITLE
[BUG] 无法自动导入符文

### ISSUE THREAD

**Issue by zcat95** [Zzaphkiel/Seraphine#485]
### 问题描述

无法自动导入符文

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.0.1-beta2

### 复现方法（若有）

每次选择英雄时尝试导入符文都没反应

### 日志文件

[Seraphine_2024-10-04_ERROR.log](https://github.com/user-attachments/files/17355137/Seraphine_2024-10-04_ERROR.log)

### 出现率（若有）

未进行具体的重复测试

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
和 #435 重复了，暂时不知道什么原因
