### ISSUE TITLE
[Question] 当查看与自己相同名字的召唤师时，“回到我”失效

### ISSUE THREAD

**Issue by buynonsense** [Zzaphkiel/Seraphine#486]
### 问题描述

![image](https://github.com/user-attachments/assets/6514206d-f631-4154-9b26-cb621b3fee97)
应该要匹配一下名字后面的编号

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
好像还真是，感谢

**Comment by Zzaphkiel** [comment]
86032cc 修复了该问题
