### ISSUE TITLE
[Question] （删去左右圆括号，并在此处简要描述问题）

### ISSUE THREAD

**Issue by Aescn** [Zzaphkiel/Seraphine#487]
### 问题描述

这个人怎么不先放一个文件夹里再压缩啊😭😭😭😭😭😭

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
哪个人？
