### ISSUE TITLE
关于KDA的计算方式

### ISSUE THREAD

**Issue by Ninohana** [Zzaphkiel/Seraphine#488]
现有的KDA计算方式：(k + a) / d (d > 1)略显苍白。

是否可以根据常用位置对各参数进行加权？

抛砖引玉：

对于辅助来说，a应有更高的权重，d应有更低的权重。例如：(k + a * 1.5) / d * 0.9

对于ad来说，k应有更低的权重，d应有更高的权重。例如：(k * 0.95 + a) / d * 1.3

**Comment by Zzaphkiel** [comment]
合理，但感觉有点上不去下不来呢，如果考虑权重一类的指标的话，就有点类似 WeGame 的评分了，但我们想做到合理的评分算法也比较困难，不如就保留最简单的 kda 计算方式，给不喜欢看具体战绩数据的用户一个简单直观的计算结果呢🧐？

**Comment by asd2422313947** [comment]
我觉得在当前KDA基础上可以加一个造成伤害，造成伤害的指标还是很重要的，可以证明一个人能不能C，C的概率有多大，单单看KDA是不够的，一个人的头可能是贪生怕死K下来的，需要看一下造成伤害

**Comment by asd2422313947** [comment]
如果一个人KDA指标很好，场均伤害也是5个人里最高的，或者是这个分段平均最高的，也就能检测出这个人可能不是这个分段的人，或者是个会玩的人

**Comment by Ninohana** [comment]
其实可能不需要去“调众口”，我的意思是，增加一个参考值，可以叫做“萨勒芬妮评分”、“Seraphine Index”巴拉巴拉。这是只在这个程序中有效的值，其他软件也可能会有自己的评判方式，比如Wegame评分、elo评分等等。

我个人是非常需要这么一个参考值，相较于KDA，更有把握来尽可能地规避一些“必输局”，谁不想来一局旗鼓相当、酣畅淋漓的竞技呢？

**Comment by GreenMope** [comment]
> 其实可能不需要去“调众口”，我的意思是，增加一个参考值，可以叫做“萨勒芬妮评分”、“Seraphine Index”巴拉巴拉。这是只在这个程序中有效的值，其他软件也可能会有自己的评判方式，比如Wegame评分、elo评分等等。
> 
> 我个人是非常需要这么一个参考值，相较于KDA，更有把握来尽可能地规避一些“必输局”，谁不想来一局旗鼓相当、酣畅淋漓的竞技呢？

也许用时间久了就习惯这个评分了
这个评分其实相当有效，除了在辅助身上会相对比别的位置高一点。
能体现出参团率和生存能力，这两点往往意味着不会随意送人头、值得信任并且团队

**Comment by Zzaphkiel** [comment]
请移步 #537。
