### ISSUE TITLE
[Enhancement] 强烈建议增加一个功能

### ISSUE THREAD

**Issue by CMEPCBHG** [Zzaphkiel/Seraphine#489]
### 功能描述

客户端经常卡在结算界面，这时用工具里面的重启客户端，是没效的。必须要跳过结算界面才行，同样也是LOL工具的Joi里面，就有这个功能，强烈建议加上这个功能！

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
左边导航栏有个按钮，按一下就行了
