### ISSUE TITLE
[Enhancement] 能否添加伤害转换率显示 方便大乱斗直观看到个人的贡献

### ISSUE THREAD

**Issue by 19990713** [Zzaphkiel/Seraphine#491]
### 功能描述

就是用经济占比÷伤害占比，玩大乱斗可以直观看到每个人的作用，很多时候玩家的伤害转换率都低于100%，我希望能有这个功能，把经济和伤害本地做个数学计算就行

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
战绩对局详情界面没地方放了
