### ISSUE TITLE
[BUG] 自动亮起英雄--按照位置设置--出现过多的英雄图标导致无法修改

### ISSUE THREAD

**Issue by GreenMope** [Zzaphkiel/Seraphine#492]
### 问题描述

![image](https://github.com/user-attachments/assets/f29d70a9-feca-43c4-9faa-57981510e6a5)
我只是设置了一个，但是这个功能好像运行次数多了就会出现很多图标，导致后面的X不显示，没办法更换英雄

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.0.0

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
问题已记录，下版本修复

**Comment by Zzaphkiel** [comment]
1101792 修复了该问题
