### ISSUE TITLE
[Enhancement] 能否查看自定义比赛的战绩

### ISSUE THREAD

**Issue by WSdzy** [Zzaphkiel/Seraphine#493]
### 功能描述

您好，当前的战绩查询不能查看自定义游戏内容（如果有请原谅我没看到），能否添加一个。
用途是高校内组织比赛，基本全部为自定义对局，查询对手的英雄选择情况。

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
#473，接口看不到自定义对局，可以用 WeGame
