### ISSUE TITLE
自动重连无限错误触发

### ISSUE THREAD

**Issue by RickEren** [Zzaphkiel/Seraphine#494]
### 问题描述

如果在水晶爆炸后，按alt+f4关闭LOL，就会自动重连启动一个无效的"League of Legends.exe"

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.0.0

### 客户端状态（若有）

结算界面

### 复现方法（若有）

如果在水晶爆炸后，按alt+f4关闭LOL，就会自动重连启动一个无效的"League of Legends.exe"

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
有通过对比实验确定是自动重新连接功能导致的吗？

**Comment by Zzaphkiel** [comment]
自动重新连接**在代码实现上不会手动拉起进程**，而是调用的 LCU API：
``` python
async def __onReconnect(self):
    if not cfg.get(cfg.enableAutoReconnect):
        return

    async def reconnect():
        while await connector.getGameStatus() == "Reconnect":
            # 掉线立刻重连会无效
            await asyncio.sleep(.3)
            await connector.reconnect()

    asyncio.create_task(reconnect())

@retry()
async def reconnect(self):
    return await self.__post("/lol-gameflow/v1/reconnect")
```

所以可以基本排除是由自动重连所导致的问题，如果关闭该功能问题解决，那就暂时给它关了吧？

**Comment by RichardReal00** [comment]
对，现在关了就不影响使用了。

Noa ***@***.***>于2024年10月25日 周五15:34写道：
