### ISSUE TITLE
成电的大佬 你是我的偶像 我看你的代码的时候嘴巴都合不上~~~~~ 

### ISSUE THREAD

**Issue by MikasaChenJ** [Zzaphkiel/Seraphine#495]
### 问题描述

没什么问题 就是想膜拜一下大佬~~~·

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by MikasaChenJ** [comment]
大佬！

**Comment by Zzaphkiel** [comment]
🥰🥰
