### ISSUE TITLE
[BUG] 窗口太大了

### ISSUE THREAD

**Issue by sttgood** [Zzaphkiel/Seraphine#496]
### 问题描述

打开软件提示窗口太大了，需要自动重启软件。点击确定，仍让提示窗口太大了

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.0.0

### 客户端状态（若有）

主界面，未进行游戏

### 复现方法（若有）

![windowTooBig](https://github.com/user-attachments/assets/3b244b6b-8964-4ea3-a1c6-5040d75d0ad2)

### 出现率（若有）

未进行具体的重复测试

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
仓库代码已经修复该问题

**Comment by sttgood** [comment]
DpiScale设置为1，仍然会窗口太大。尝试过1.25、2等数字，窗口变得更大。会有小于1的选项吗

**Comment by Zzaphkiel** [comment]
> DpiScale设置为1，仍然会窗口太大。尝试过1.25、2等数字，窗口变得更大。会有小于1的选项吗

没有，因为显示器分辨率没有 Seraphine 窗口大所以才会报的错误

仓库代码已经把这个问题修了，你可以暂时使用老版本或者直接把仓库代码拉下来跑

**Comment by sttgood** [comment]
跑了代码，最大化可以用。就到这里了，谢谢大神
