### ISSUE TITLE
[关于kda]在个人界面或查询界面显示最近kda结果 

### ISSUE THREAD

**Issue by HYPJL** [Zzaphkiel/Seraphine#497]
### 功能描述

现在个人界面或者查询界面只有123/88/999这种kda显示，可以增加一个计算结果吗，谢谢

### 在提交之前，请您确认

- [x] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
感谢建议。

002737a 已实现该特性
