### ISSUE TITLE
[BUG] 程序在包含空格目录下运行，会报错

### ISSUE THREAD

**Issue by 6get-xiaofan** [Zzaphkiel/Seraphine#499]
### 问题描述

程序在包含空格目录下运行，会报错，例如：Program Files 目录

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

Latest

### 复现方法（若有）

解压到包含空格目录，双击主程序运行

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
无法复现

![QQ20241024-152303](https://github.com/user-attachments/assets/3fe87a55-48df-4792-92b0-96669addcd50)
