### ISSUE TITLE
lolcha倒了

### ISSUE THREAD

**Issue by l0n9er** [Zzaphkiel/Seraphine#5]
不知道你能不能坚持住

**Comment by Zzaphkiel** [comment]
lolcha 知名度太高了，我们低调一点吧😥

**Comment by l0n9er** [comment]
不拉群，不留联系方式，如果有用域名得注意就是了

**Comment by Zzaphkiel** [comment]
我没想搞那么复杂，准备只在 GitHub 上活跃了~

**Comment by liangzilixueha** [comment]
这用的是别人的api啊...有了api那不是啥都有了？

**Comment by Zzaphkiel** [comment]
是这样没错，虽然 lcu api 应该是长期可以用的（它来自于 Riot），但是我感觉国服对于是否可以随意调用这些 api 的态度就不太明确了（毕竟有隐藏战绩功能）
