### ISSUE TITLE
最新lol版本无法获取选手信息

### ISSUE THREAD

**Issue by Ada0317** [Zzaphkiel/Seraphine#50]
本周更新版本后，无法获取游戏对局的选手信息了

**Comment by Ada0317** [comment]
> 感谢反馈。
> 
> 无法复现 😥 我这里还是能用的
又能获取了  不知道是什么原因

**Comment by Zzaphkiel** [comment]
一般这种突然不能用了都是因为英雄联盟那边的问题哦~
