### ISSUE TITLE
[Question] 游戏操作行为异常

### ISSUE THREAD

**Issue by eenima** [Zzaphkiel/Seraphine#501]
### 问题描述

用了一个月没事，打把大乱斗突然说我游戏行为异常，封了一小时，不知道是操作太好还是跟这个有关，不过近两天更新了14.21版本
![479903dcf33389e8de1940ed7f68b637](https://github.com/user-attachments/assets/7765f3ed-ef8b-4309-969a-c2bb99ed1b87)

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
应该是正常现象

**Comment by zechuanJAY** [comment]
我也是这样，今天也被封了一小时，说游戏数据未上报封我1小时！强行把我游戏T掉了
