### ISSUE TITLE
[BUG] 无法使用OPGG一键符文

### ISSUE THREAD

**Issue by MikeYuan998** [Zzaphkiel/Seraphine#503]
### 问题描述

点击一键符文之后没有反应，且主程序也无法识别后续对局，OPGG也加载不出英雄了，如果不使用一键符文就都还是正常的。

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.0.0

### 客户端状态（若有）

选择英雄界面

### 复现方法（若有）

点击设为当前符文页

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
可能和 #435 重复了，这个 OPGG 符文应用不了暂时修不了，我这怎么搞都没法复现
