### ISSUE TITLE
[Enhancement] 一键举报9个人

### ISSUE THREAD

**Issue by dmarkdmark** [Zzaphkiel/Seraphine#504]
### 功能描述

来个一键举报其他9个人，有时候大乱斗感觉水平都不在一个平面，而且我今年就举报3个大乱斗的号封了3年，严重怀疑现在大乱斗有人开科技在大乱斗

特此恳求：来个一键举报9个人的按钮，给我一键举报他们，防止科技横行
最后希望2025年总决赛在中国主场，LPL能再拿个冠军
今年冠军概率几乎为零，不奢求了
明年还不冠军，这游戏基本要凉了

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
暂无实现计划

**Comment by dmarkdmark** [comment]
收到
