### ISSUE TITLE
战绩页中分路判断存在问题

### ISSUE THREAD

**Issue by Ninohana** [Zzaphkiel/Seraphine#505]
<img width="757" alt="image" src="https://github.com/user-attachments/assets/15c3f798-424e-4cd0-a0db-688e78bd2738">

_Originally posted by @jqyisbest in https://github.com/Zzaphkiel/Seraphine/issues/488#issuecomment-2439801386_

**Comment by Zzaphkiel** [comment]
@jqyisbest @Ninohana 

当时加入这个特性的时候就发现有这个问题了（#120），之前也有人提过（#211），但是不太好修 😭
