### ISSUE TITLE
[BUG] （无法通过Seraphine启动LOL）

### ISSUE THREAD

**Issue by xu4400176** [Zzaphkiel/Seraphine#507]
### 问题描述

![微信截图_20241027214301](https://github.com/user-attachments/assets/9e960fdc-efe8-40e3-a8cf-62e6b6b1dd76)
![微信截图_20241027214322](https://github.com/user-attachments/assets/8350bb2e-57e8-420d-92f0-f6bc1ef887b1)

启动LOL的时候报登录器升级公告，无法启动LOL客户端

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

e.g.v1.0.0

### 复现方法（若有）

重新解压软件、打开软件等操作依然没用

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [ ] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
无法复现，我这里是正常的

点下确定升级下试试吧？

**Comment by xu4400176** [comment]
神奇，我这里是重新下了软件也这样，游戏是用wegame更新到最新了的

**Comment by kjdfklha** [comment]
某讯14.20更新了客户端，禁止client直接启动客户端。可以绕过之后使用该功能登录。绕过方法参考
【不启动wegame下载、打开lol】 https://www.bilibili.com/video/BV18NSVYDETb/?share_source=copy_web&vd_source=f4f6f08226c2afcbae57b017501306f2
