### ISSUE TITLE
使用过程中的bug

### ISSUE THREAD

**Issue by luoysuan** [Zzaphkiel/Seraphine#51]
启动lol之后再运行软件就报错
![image](https://github.com/Zzaphkiel/Seraphine/assets/51365362/3b5d34bd-9b52-4c34-96a2-a8550fc4d23d)
![image](https://github.com/Zzaphkiel/Seraphine/assets/51365362/b9ce76c2-11ac-4633-a189-af071c69e710)
这个是配置文件 其他的代码都没有改过
![image](https://github.com/Zzaphkiel/Seraphine/assets/51365362/58c88fbf-9611-4586-b142-4734c5b747e5)

**Comment by luoysuan** [comment]
追加问题，上面的问题是先启动了lol然后软件启动后报错，之后我先启动了软件，然后添加了LolPath之后再启动软件还是和上面一样的报错。
![image](https://github.com/Zzaphkiel/Seraphine/assets/51365362/4265e3dd-ede8-4b7a-b34d-f3b9977ee088)

**Comment by Hpero4** [comment]
我尝试了一下, 未能复现问题; 这似乎与系统环境有关系, python在使用subprocess调用外部命令时, 得到非0返回就会报这个错;

Debug需要更多信息, 麻烦在https://github.com/Zzaphkiel/Seraphine/blob/9b832c37560881a31ee9b36d62cff54d252ada14/app/lol/listener.py#L8C1-L11

添加以下代码以捕获更多错误时信息:
```python
except subprocess.CalledProcessError as e:
    print("exit code：", e.returncode)
```

**Comment by Hpero4** [comment]
您的电脑系统中似乎缺少 "tasklist.exe", 请执行以下命令确定是否因环境变量原因导致tasklist无法执行;

```
C:\Windows\System32\tasklist.exe
```

若仍报同样错误, 则需要检查是否安装了精简版的系统

**Comment by luoysuan** [comment]
> 您的电脑系统中似乎缺少 "tasklist.exe", 请执行以下命令确定是否因环境变量原因导致tasklist无法执行;
> 
> ```
> C:\Windows\System32\tasklist.exe
> ```
> 
> 若仍报同样错误, 则需要检查是否安装了精简版的系统
这个是缺少了吗？
![image](https://github.com/Zzaphkiel/Seraphine/assets/51365362/5e467703-0de1-487d-bab5-4ddf1dcbb708)

**Comment by luoysuan** [comment]
> 您的电脑系统中似乎缺少 "tasklist.exe", 请执行以下命令确定是否因环境变量原因导致tasklist无法执行;
> 
> ```
> C:\Windows\System32\tasklist.exe
> ```
> 
> 若仍报同样错误, 则需要检查是否安装了精简版的系统

但是我用文件搜索的软件却能查询到这个exe文件
![image](https://github.com/Zzaphkiel/Seraphine/assets/51365362/4bb94d64-9b1c-45ff-9038-636a562dfd09)

**Comment by Hpero4** [comment]
参考此链接

https://www.cnblogs.com/clement-jiao/p/9658806.html

**Comment by luoysuan** [comment]
> 参考此链接
> 
> https://www.cnblogs.com/clement-jiao/p/9658806.html

排查了一下 可能确实是系统有问题

**Comment by ssincxv** [comment]
Windows Management Instrumentation有引发windows cpu占用异常的问题，所以我把Windows Management Instrumentation禁了

**Comment by tanshaobing** [comment]
@Zzaphkiel 服务一直处于“自动 正在运行“的状态，打开软件还是会出现这个弹窗报错

**Comment by Sprite0821** [comment]
同上，wmi正在运行，自动，打开软件报错为 tasklist.exe不可用
