### ISSUE TITLE
[Question] 启动软件打开英雄联盟对局时会使对局无法连接服务器

### ISSUE THREAD

**Issue by 990974314** [Zzaphkiel/Seraphine#510]
### 问题描述

无论是峡谷匹配还是排位，大乱斗，终极魔典，只要我后台开着萨勒芬妮进入对局就会使该对局账户无法无法连接服务器。
只能关闭插件，重启游戏重新加载才能进入对局，我应该怎么办？0-o

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
无法复现，暂时别开了吧🥲
