### ISSUE TITLE
[Enhancement] 希望增加一个自动符文功能

### ISSUE THREAD

**Issue by LiuJinfan** [Zzaphkiel/Seraphine#511]
### 功能描述

选择英雄时可以保存符文，下次选中该英雄自动应用符文

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
感觉意义不太大，因为现在的 OPGG 一键符文基本上够用了，一键一下再根据实际情况微调一下效果是一样的

**Comment by LiuJinfan** [comment]
收到！其实希望的理想效果是自动接受对局（已实现）+自动bp（已实现）+自动应用符文（未实现）+自动应用召唤师技能（未实现），实现全自动化🎉
