### ISSUE TITLE
[Question]  想实现一个实时显示当前玩家伤害的UI

### ISSUE THREAD

**Issue by NiMalaq** [Zzaphkiel/Seraphine#512]
### 问题描述

在游戏对局中实现实时显示当前玩家的输出伤害

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by NiMalaq** [comment]
又或者调用哪些LCU接口可以获取到 实时伤害信息，看了一下文档好像并没有对于伤害的返回

**Comment by amabilee** [comment]
根据您的描述，一种潜在的解决方案是利用可用的 LCU API 来收集所有可能的游戏统计数据并过滤掉与损坏相关的数据。
您还可以探索外部数据聚合服务或集成的 API，看看它们是否提供所需的见解。

如果您还没有，请务必查看： [https://hextechdocs.dev/tag/lcu/](https://hextechdocs.dev/tag/lcu/)
