### ISSUE TITLE
[Enhancement] 建议一把游戏结束后依然能看到上把队友的游戏记录

### ISSUE THREAD

**Issue by xiaomingzzzzz** [Zzaphkiel/Seraphine#514]
### 功能描述

RT 这里空白也是空白，有时候赢了输了回想复盘的时候需要看下队友到底是不是玩这个英雄/位置的就无从考证了 再进去搜索就很麻烦 继续放着直到下一次排进去感觉更好

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by xiaomingzzzzz** [comment]
![image](https://github.com/user-attachments/assets/8b863021-2b03-4e24-937d-843c15d923c8)

**Comment by xiaomingzzzzz** [comment]
另外还是想再次提一下给OPGG的页面加一个刷新按钮，有的时候真的加载不出来 还有一次玩的盲僧给推荐的妖姬 ，然后这里搜索建议在下面多做一个UI来放不是这个位置的英雄，比如我之前选的中，但是我补位了 或者我需要看别的位置的 就也能有个入口
，目前切换位置还是有点麻烦![Uploading image.png…]()

**Comment by Zzaphkiel** [comment]
1. b19ab48 实现了一个选项，用户可以自己决定是否清空：
![QQ20241106-165243](https://github.com/user-attachments/assets/601e8a57-3154-4c3a-92ea-dd9f56345e4f)

2. > 还是想再次提一下给OPGG的页面加一个刷新按钮，有的时候真的加载不出来 还有一次玩的盲僧给推荐的妖姬 

    我的强迫症不允许我给 OPGG 界面加刷新按钮，如果有刷新需要就手动上面改一下条件（如区服）再改回来吧
3. > 搜索建议在下面多做一个UI来放不是这个位置的英雄，比如我之前选的中，但是我补位了 或者我需要看别的位置的 就也能有个入口
   
    没太听懂，梯队和 build 界面上面不是有地方可以选择位置嘛，而且因为 cache 所以加载的应该挺快的吧？

**Comment by xiaomingzzzzz** [comment]
2可以接受的 起码有个办法了233   3的话感觉是一个nicetohave吧 因为有时候确实很紧张 还有临时和你换位置的人啥的  至少上单搜xia 肯定是没有或者是很少的数量了，如果还是能给我找到霞就方便了  比如各平台搜索上也会有联想搜索 这个作者可以评估下是否优雅 总之已经解决我的问题感谢回复

**Comment by Zzaphkiel** [comment]
如果让它 “非常智能”，那么它在某些场景也可能会变得 “非常不智能”；搜索的联想可以是 “合理联想”，但也可能会是 “过度联想”。目前并不打算改变 OPGG 界面的搜索功能：让它提供对下方展示的英雄的**准确搜索结果**虽然保守，但这也是不会出错的选择。

> 因为有时候确实很紧张 还有临时和你换位置的人啥的

锁定英雄之后会自动跳转到 build 的吧（而且会自动选择对应的位置），搜索也不用搜了😆，应该挺快的

**Comment by xiaomingzzzzz** [comment]
嗯嗯 其实需求在于锁定前和锁定后，锁定前就是我刚才说的 锁定后的话希望排位模式能尽快支持上~

**Comment by Zzaphkiel** [comment]
> 锁定后的话希望排位模式能尽快支持上~

这个目前应该是个 BUG，我很久没有打排位了，修的有点慢

**Comment by Zzaphkiel** [comment]
>  锁定后的话希望排位模式能尽快支持上

63e4b2a 修复了该问题
