### ISSUE TITLE
[Enhancement] （删去左右圆括号，并在此处简要描述功能）优化显示战绩显示UI

### ISSUE THREAD

**Issue by LiuVFX001** [Zzaphkiel/Seraphine#517]
### 功能描述

比如把日期排在人头比后面，并且高亮显示。KDA可以通过分区显示排位的，排除大乱斗的战绩导致的KDA过高

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
1. ac3c039 对可读性做了简单的优化
2. 设置里有 “排位过滤” 选项，开一下就行了
