### ISSUE TITLE
[BUG] 自动亮起英雄/自动Ban英雄会添加到自动ban/选列表里

### ISSUE THREAD

**Issue by Gesch777** [Zzaphkiel/Seraphine#518]
### 问题描述

如图，每次自动ban/选英雄会添加到英雄列表里
![image](https://github.com/user-attachments/assets/fe6063d5-0bb9-43de-b561-7a81d64b2de7)
![image](https://github.com/user-attachments/assets/52660e12-e3a7-43b4-8c3b-c40010638e6a)

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

v1.0.0

### 复现方法（若有）

每次自动ban/选英雄会添加到英雄列表里

### 日志文件

[Seraphine_2024-10-27_ERROR.log](https://github.com/user-attachments/files/17710667/Seraphine_2024-10-27_ERROR.log)
[Seraphine_2024-10-28_ERROR.log](https://github.com/user-attachments/files/17710668/Seraphine_2024-10-28_ERROR.log)
[Seraphine_2024-10-29_ERROR.log](https://github.com/user-attachments/files/17710669/Seraphine_2024-10-29_ERROR.log)
[Seraphine_2024-10-30_ERROR.log](https://github.com/user-attachments/files/17710670/Seraphine_2024-10-30_ERROR.log)
[Seraphine_2024-10-31_ERROR.log](https://github.com/user-attachments/files/17710671/Seraphine_2024-10-31_ERROR.log)
[Seraphine_2024-11-01_ERROR.log](https://github.com/user-attachments/files/17710672/Seraphine_2024-11-01_ERROR.log)
[Seraphine_2024-11-02_ERROR.log](https://github.com/user-attachments/files/17710673/Seraphine_2024-11-02_ERROR.log)
[Seraphine_2024-11-03_ERROR.log](https://github.com/user-attachments/files/17710674/Seraphine_2024-11-03_ERROR.log)
[Seraphine_2024-11-04_ERROR.log](https://github.com/user-attachments/files/17710675/Seraphine_2024-11-04_ERROR.log)
[Seraphine_2024-11-06_ERROR.log](https://github.com/user-attachments/files/17710676/Seraphine_2024-11-06_ERROR.log)
[Seraphine_2024-11-07_ERROR.log](https://github.com/user-attachments/files/17710677/Seraphine_2024-11-07_ERROR.log)
[Seraphine_2024-11-08_ERROR.log](https://github.com/user-attachments/files/17710679/Seraphine_2024-11-08_ERROR.log)
[Seraphine_2024-11-09_ERROR.log](https://github.com/user-attachments/files/17710681/Seraphine_2024-11-09_ERROR.log)
[Seraphine_2024-11-10_ERROR.log](https://github.com/user-attachments/files/17710682/Seraphine_2024-11-10_ERROR.log)
[Seraphine_2024-11-11_ERROR.log](https://github.com/user-attachments/files/17710683/Seraphine_2024-11-11_ERROR.log)
[Seraphine_2024-11-12_ERROR.log](https://github.com/user-attachments/files/17710684/Seraphine_2024-11-12_ERROR.log)

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
#492
