### ISSUE TITLE
[Question] 什么时候会更新版本呢？

### ISSUE THREAD

**Issue by Lunaov0** [Zzaphkiel/Seraphine#519]
### 问题描述

喵喵

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
这不是天天在更新吗？

![QQ20241114-160300](https://github.com/user-attachments/assets/95061c10-6b5e-4e1e-8dc4-1b1afc1e4613)

~点击 Star 加快更新速度😊~

**Comment by Lunaov0** [comment]
> 这不是天天在更新吗？
> 
> ![QQ20241114-160300](https://private-user-images.githubusercontent.com/60383222/386098142-95061c10-6b5e-4e1e-8dc4-1b1afc1e4613.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NzE5MTUsIm5iZiI6MTczMTU3MTYxNSwicGF0aCI6Ii82MDM4MzIyMi8zODYwOTgxNDItOTUwNjFjMTAtNmI1ZS00ZTFlLThkYzQtMWIxYWZjMWU0NjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA4MDY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhYzZmZDU3NDJlYjYwMTIyY2U0NzAxZWJlNjJhMzBlYzYyMmQ2NWU1NzhiNjhiNjJlMGY0YmUxNWI3NjBjZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-2y6Pjod4SX1aWq9NOfuW_orm35bF0s_-9GZJHIvPYI)
> 
> ~点击 Star 加快更新速度😊~

我的意思是打包好的...
现在版本不还在8月3号的v1.0.0 正式版吗？

**Comment by Zzaphkiel** [comment]
手头上的问题还没修完，急的话可以把代码拉下来直接跑，或者自己打包
