### ISSUE TITLE
[Question] 选中窗口显示选中

### ISSUE THREAD

**Issue by homerLL** [Zzaphkiel/Seraphine#522]
### 问题描述

![PixPin_2024-11-17_13-22-35](https://github.com/user-attachments/assets/95030f2b-7e81-4857-ad89-75b7e8702e0d)
如图所示，win11 选中窗口的时候，左上方的横条显示不太对劲....可以调整到在一条水平线上吗？或则把左上部分往下移一点，不要和这个选中的背景色在一个区域内

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
#247

**Comment by homerLL** [comment]
感谢大佬
