### ISSUE TITLE
[Question] 国际服不能查到除了组队的队友以外所有其他人的信息

### ISSUE THREAD

**Issue by snowly233** [Zzaphkiel/Seraphine#523]
### 问题描述

具体在台服，使用萨勒芬妮可以正常启动游戏，但是启动游戏后只能查到自己组队的队友战绩，其他匹配到的队友和地方均无法查到战绩

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
正常的，因为客户端本身就看不到队友是谁，在我们这如果能看到反而影响公平性
