### ISSUE TITLE
[Enhancement] （可以增加一些其他数据源吗 列如lol.ps 或者 101.qq ）

### ISSUE THREAD

**Issue by miss17year** [Zzaphkiel/Seraphine#524]
### 功能描述

![Uploading QQ_1731859197466.png…]()

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
#443
