### ISSUE TITLE
[Question] 用户名后面有个🔐是什么意思？

### ISSUE THREAD

**Issue by yunscan** [Zzaphkiel/Seraphine#525]
### 问题描述

![image](https://github.com/user-attachments/assets/9c2fd3d1-9f9f-4390-b6af-32a6a92969e9)

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
#143 #301

**Comment by miss17year** [comment]
隐藏战绩的 就是有锁
