### ISSUE TITLE
[Enhancement] 新版KDA可读性相比较老版本KAD可读性更差

### ISSUE THREAD

**Issue by asd2422313947** [Zzaphkiel/Seraphine#526]
### 功能描述

字体太粗，颜色过于红，导致缩成一团了，得细看才能看清数字是多少，不如之前的细体一眼就能看清具体数字
建议：使用浅红色文字，取消加粗

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
https://github.com/Zzaphkiel/Seraphine/blob/5c8829d2cb344b1e9c823d3330b98fbf40481bca/app/resource/qss/light/game_info_interface.qss#L84C1-L86C2

之前不也是加粗的？

**Comment by asd2422313947** [comment]
> https://github.com/Zzaphkiel/Seraphine/blob/5c8829d2cb344b1e9c823d3330b98fbf40481bca/app/resource/qss/light/game_info_interface.qss#L84C1-L86C2
> 
> 之前不也是加粗的？
不是，我说的是对局信息面板的战绩，之前都是正常的字体，没有加粗，没有红色死亡数字，现在加粗+红色之后，看起来不知道是字体问题还是什么问题，相比较以前，很难阅读，因为感觉加粗+加红的字体变得缩成一团了，得细看，粗略看不清了

**Comment by asd2422313947** [comment]
> https://github.com/Zzaphkiel/Seraphine/blob/5c8829d2cb344b1e9c823d3330b98fbf40481bca/app/resource/qss/light/game_info_interface.qss#L84C1-L86C2
> 
> 之前不也是加粗的？

我突然懂了，在浅色主题下加粗+加红战绩数字是能看清的，但是一旦切换了深色主题，加粗+加红战绩数字就看不太清了

**Comment by asd2422313947** [comment]
> https://github.com/Zzaphkiel/Seraphine/blob/5c8829d2cb344b1e9c823d3330b98fbf40481bca/app/resource/qss/light/game_info_interface.qss#L84C1-L86C2
> 
> 之前不也是加粗的？

也可能是系统字体问题，不同的系统使用的字体不同，加粗变色之后的显示效果也不相同

**Comment by asd2422313947** [comment]
> https://github.com/Zzaphkiel/Seraphine/blob/5c8829d2cb344b1e9c823d3330b98fbf40481bca/app/resource/qss/light/game_info_interface.qss#L84C1-L86C2
> 
> 之前不也是加粗的？

经过测试是红色死亡颜色的问题，红色在深色主题下的适配性不好，会导致颜色混淆，看不太清具体数字，但是在浅色模式下没有颜色混淆问题所以就能看得清。

**Comment by asd2422313947** [comment]
> https://github.com/Zzaphkiel/Seraphine/blob/5c8829d2cb344b1e9c823d3330b98fbf40481bca/app/resource/qss/light/game_info_interface.qss#L84C1-L86C2
> 
> 之前不也是加粗的？

还有就是 新版战绩KDA格式有点怪会有空位打破了整体美观
显示双数战绩还好：11/19  20/30/60  整齐划一
显示单数战绩就有点怪：11/19  6 /20/11  有空位，打破协调
如果单数与双数一起显示，单数就有空位

旧版本KDA格式无论单数还是双数都是整齐划一的：
11/19  20-3-6
11/9    6-3-9

**Comment by Zzaphkiel** [comment]
颜色可能确实有点问题，在 d7b7b4d 已经修了。

排版时 KDA 数据标签之间的空间是**故意为之**，为了使得**一列上所有的 KDA 数据对齐**，这样更加美观且更加具有可读性（参考 LoL 客户端提供的对局战绩界面）。所以我们新的战绩搜索界面、生涯界面以及对局详情界面也是这样做的。

![QQ20241119-165425](https://github.com/user-attachments/assets/923295b5-f873-4368-b6cf-8ccedf7c68e9)

关于排版审美差异问题，你可以附上你希望实现的效果图并提出 PR：这比提出 issue 与我 argue 更加简单，且更容易实现你想要的效果。除非合理建议，否则我个人不会主动修改。
