### ISSUE TITLE
[Question] 用了撒了芬妮辅助这个项目，我玩LOL经常会掉线，然后电脑会自动关机、。请问有朋友遇到和我一样的情况吗？

### ISSUE THREAD

**Issue by a69694510** [Zzaphkiel/Seraphine#527]
### 问题描述

RT

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
👀

**Comment by zipg** [comment]
不用就没有这些问题吗？看描述感觉没什么关系

**Comment by a69694510** [comment]
> 不用就没有这些问题吗？看描述感觉没什么关系

是的，从来没有过自动关机，用了这个项目打排位，老是自动关机

**Comment by moshehx** [comment]
有的，频率不算高，可能几天会出现一次。确实是用了软件以后才遇见的

**Comment by Zzaphkiel** [comment]
挺邪门，但应该不是我们的问题😆
