### ISSUE TITLE
[Enhancement] 能否做一个数据统计功能，像lpl赛后的结算

### ISSUE THREAD

**Issue by FogHunterL** [Zzaphkiel/Seraphine#530]
### 功能描述

比如像参团率，伤害占比，伤害转化率，对位经济差，伤害差这种

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
太麻烦了，现在的战绩界面已经塞满了，想加新数据进去还得重新再做一层界面放上去，况且这些功能掌盟或者 WeGame 都实现的挺好的了
