### ISSUE TITLE
[Enhancement] 能否把【对局信息】中死亡次数的红字恢复成白色？

### ISSUE THREAD

**Issue by moshehx** [Zzaphkiel/Seraphine#531]
### 功能描述

红字实际非常晃眼，一眼过去视觉上混乱不堪，严重降低了体验感，明显起了反效果。之前默认的简洁高效，很快就能获取完信息

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
fc07a644174e9e6f0d97e2633822b3d3a367bfb8 提供了选项卡片，用户可以随喜好自定义这一颜色
