### ISSUE TITLE
[BUG] 搭配 op.gg 應用程式使用會導致藍屏問題

### ISSUE THREAD

**Issue by hugh921020** [Zzaphkiel/Seraphine#532]
### 问题描述

搭配op.gg應用程式使用會導致藍屏問題

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.1.0

### 出现率（若有）

未进行具体的重复测试

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
之前有这个问题吗？

**Comment by hugh921020** [comment]
之前就有

**Comment by Zzaphkiel** [comment]
抱歉，我对此可能无能为力 🥲
