### ISSUE TITLE
[Question] （删去左右圆括号，并在此处简要描述问题）

### ISSUE THREAD

**Issue by allen151821** [Zzaphkiel/Seraphine#533]
### 问题描述

我反馈一下，这个死亡是红色的  你们感觉不显眼吗
![微信截图_20241121180656](https://github.com/user-attachments/assets/edd55113-8790-49e3-b272-e8544ea5ccb2)
![微信截图_20241121180733](https://github.com/user-attachments/assets/85c64a1a-bd1c-44a9-b518-7a5ffab212a2)

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
#531
