### ISSUE TITLE
打开就报错ValueError: None is not allowed as password value

### ISSUE THREAD

**Issue by 572095948** [Zzaphkiel/Seraphine#535]
### 问题描述

![image](https://github.com/user-attachments/assets/5916d6d0-14c8-4fe4-a946-73181fcd686a)
打开就报错

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
服务器问题，等会就行了
