### ISSUE TITLE
[Question] 韩服使用助手玩一整天以后封禁30天，国服没有封过一次用了好几个月问一下属于什么情况，使用功能和国服一致

### ISSUE THREAD

**Issue by sszs7777** [Zzaphkiel/Seraphine#539]
### 问题描述

韩服使用助手玩一整天以后封禁30天，国服没有封过一次用了好几个月问一下属于什么情况，使用功能和国服一致

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by xiaomingzzzzz** [comment]
我的情况是日服选英雄的时候会弹vanguard提示，然后点确定客户端就关了 也是国服正常

**Comment by Zzaphkiel** [comment]
情况应该是韩服被封号了但是国服没被封号，所以可以考虑酌情使用
