### ISSUE TITLE
[Enhancement]增加更多类型的JSON功能

### ISSUE THREAD

**Issue by awdlxj** [Zzaphkiel/Seraphine#540]
### 功能描述

Riot官方有很多的GET POST等方法，希望能够增加一些功能，甚至能够自定义JSON数据的发送。

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
没太听懂什么意思，可以细说一下吗？

**Comment by awdlxj** [comment]
我没有表述清楚是我的问题。拳头官方开放了很多api的，有些网站可以查到，我想可以增加更多的功能，甚至自己能够自定义调用一些api

**Comment by Zzaphkiel** [comment]
1. riot api 没有 key 调不了的
2. 在软件内开放自定义调用 lcu api 的用户界面接口感觉局限性也有点大？只能 post 或者 get 一些简单的东西

**Comment by awdlxj** [comment]
我不清楚现在lcuapi的情况，但在两三年前的lcu api有特别多的调用方法，比如delete 等等 ，有些能实现一些特殊用途，比如修改游戏设置，游戏昵称(本地)，等等

**Comment by Zzaphkiel** [comment]
明白你的意思了。所以你想要（或者希望我们）实现的是在软件内提供一个自定义 api 调用的用户界面接口吗 🤔？

**Comment by awdlxj** [comment]
对的，最好能再有一些常用的api列表附上。比如有些api能够返回一些游戏资源数据，这样就不必去解包游戏了，程序功能性也扩展了

**Comment by awdlxj** [comment]
这是我曾经开发过的软件，你可以参考一下部分功能。
![b92191d6b3d9552730a7b26d860f0901](https://github.com/user-attachments/assets/3c7ada9d-78df-43e2-8aad-2edf3fac941e)
![47edf560b24130e4215bbe603b6492c4](https://github.com/user-attachments/assets/46f971b9-9f19-43ff-b226-48da5c04df0b)

**Comment by Zzaphkiel** [comment]
我个人认为这个功能是冗余的，因为使用软件的用户大部分（或者说至少 95% 以上）都用不到自定义 lcu api 调用的功能。如果有开发 / 调试需求，可以使用更加全面好用的开发工具，而不是使用 Seraphine：毕竟我们是一个已经将 lcu api 封装良好的，给普通游戏玩家使用的查战绩软件 👀

**Comment by awdlxj** [comment]
好的，我只是提个建议
