### ISSUE TITLE
[Enhancement] 是否考虑在优劣势对抗英雄处做超链接跳转至对应英雄

### ISSUE THREAD

**Issue by xiaomingzzzzz** [Zzaphkiel/Seraphine#541]
### 功能描述

RT 我看英雄数据的目的就是选一个好打的，目前无跳转功能需要返回再重新搜索，可以先放在这看看有没有同样需求的UU~

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
锁定了不就自动跳转了吗 🤔？

**Comment by xiaomingzzzzz** [comment]
对 但从工具角度来说想看看各个英雄的详细情况再决定 不知道是不是只有我这样哈哈

**Comment by Zzaphkiel** [comment]
感觉可以考虑一下，因为如果 build 界面里提到的其他英雄可以点击跳转确实比较符合直觉一点

p.s. 但我已经忘了几个月之前的代码怎么写的了，需要看一下改起来复杂不复杂😑

**Comment by xiaomingzzzzz** [comment]
嗯嗯 辛苦大佬~那里摆着不让点有点小蛋疼2333

**Comment by Zzaphkiel** [comment]
545fb3b 已实现该特性

**Comment by xiaomingzzzzz** [comment]
Cool





------------------ 原始邮件 ------------------
发件人: Noa ***@***.***&gt;
发送时间: 2024年12月2日 18:21
收件人: Zzaphkiel/Seraphine ***@***.***&gt;
抄送: x1aoM丶 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Zzaphkiel/Seraphine] [Enhancement] 是否考虑在优劣势对抗英雄处做超链接跳转至对应英雄 (Issue #541)





 
545fb3b 已实现该特性

**Comment by H4o2cc** [comment]
可以支持自动设置符文么
