### ISSUE TITLE
[Enhancement] 建议增加对局和选择聊天频道的发信API

### ISSUE THREAD

**Issue by ZzzYanSong** [Zzaphkiel/Seraphine#546]
### 功能描述

建议增加对局和选择聊天频道的发信API，一键发送全部人kd 或队友kd 近3场战绩等数据

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
1. 如果是想在 BP 阶段发送队友 KDA，那么我个人认为没有必要压力队友
2. 如果是想在进入游戏之后发送对面 KDA，那么 LCU API 做不到这一点

**Comment by asd2422313947** [comment]
这个功能增加不了，发多了铁被封号，因为我用别的项目软件就是因为发送战绩导致封号1天
