### ISSUE TITLE
[BUG] 客户端信息请求失败

### ISSUE THREAD

**Issue by gankumangcao** [Zzaphkiel/Seraphine#547]
### 问题描述

艾欧尼亚区
![Snipaste_2024-12-03_22-52-21](https://github.com/user-attachments/assets/86bfc2bd-7739-463e-935c-dfd775bf6b91)
![Snipaste_2024-12-03_23-00-37](https://github.com/user-attachments/assets/97fad866-c7a1-4355-9500-13b3a7f6597f)

### 系统信息

Windows 10

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.1.1

### 客户端状态（若有）

打开就出错

### 您进行游戏的服务器（若有）

艾欧尼亚

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
#203
