### ISSUE TITLE
[Enhancement] op.gg的窗口晚上会变成夜间模式

### ISSUE THREAD

**Issue by joshuachenn** [Zzaphkiel/Seraphine#548]
### 功能描述

能不能关闭op.gg的夜间模式，因为字体也是黑色的，然后背景是暗色的，看起来特别费劲

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
> 字体也是黑色的

样式表坏了，重新下载一个 Seraphine 就正常了

![QQ截图20241204154404](https://github.com/user-attachments/assets/3713229d-3a36-4c79-94dd-debbabe6ec2a)
