### ISSUE TITLE
[Enhancement] 提议直接复刻wegame ui

### ISSUE THREAD

**Issue by rdcentermrzhi** [Zzaphkiel/Seraphine#550]
### 功能描述

感觉用惯了wegame 就很不习惯， 要不就ui就按照wegame设计好了， 每次点回到自己都找半天

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
暂无计划
