### ISSUE TITLE
[Question] 我一直不知道OP.GG 里面的百分比是啥，能添加说明啥的吗  或者哪有讲解释

### ISSUE THREAD

**Issue by allen151821** [Zzaphkiel/Seraphine#551]
### 问题描述

[](url)
![微信截图_20241206014610](https://github.com/user-attachments/assets/fe73132f-8bc1-4cc9-bf8c-6405457e40de)
![微信截图_20241206014548](https://github.com/user-attachments/assets/6ed3fd26-3115-41c4-ae85-3f33c40e8bae)

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by CNReporter** [comment]
局数上面的应该是使用率 后面的估计是使用率内的胜率吧

**Comment by Zzaphkiel** [comment]
**局数上面是胜率，右边颜色不一样的是使用率，英雄 counter 组件里颜色不一样的是胜率**

之前做的时候以为是很显然的事情，看来还是加个提示比较好。
