### ISSUE TITLE
希望在查看个人战绩的时候，旁边显示之前的历史ID

### ISSUE THREAD

**Issue by liang807878754** [Zzaphkiel/Seraphine#552]
### 功能描述

1123

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by liang807878754** [comment]
在Lcu API中好像有提供这个接口吧

**Comment by Zzaphkiel** [comment]
看看接口 👀

**Comment by liang807878754** [comment]
看了一下好像没有，可是别的软件可以查到历史ID

**Comment by Zzaphkiel** [comment]
我目前没找到有开源的软件实现了这个的，所以目前我不知道怎么实现它 😵‍💫
