### ISSUE TITLE
[BUG] 在不同显示器中拖动窗口会导致 UI 的缩放不符合预期

### ISSUE THREAD

**Issue by jclx2023** [Zzaphkiel/Seraphine#553]
### 问题描述

在以前版本中我可以自由在多屏环境拖动seraphine，但是当前版本拖动到另一个屏幕时软件UI会直接暴毙，包括opgg的小组件

### 系统信息

Windows 11

### 运行方式

直接双击打开 exe 程序

### 软件版本

1.1.1

### 客户端状态（若有）

所有状态

### 出现率（若有）

每次这么做都必定会出现

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
无法复现。我在可以在不同分辨率不同 dpi 缩放和不同方向的显示器之间随意拖动窗口，都没有触发任何问题。

下载之前的版本对比实验试试呢？

**Comment by Zzaphkiel** [comment]
明白了，试了一下好像确实有这么个问题，目前还不确定是哪里的 BUG，也不确定好不好修

~之前理解成拖动一下窗口会让程序直接挂了~

**Comment by jclx2023** [comment]
望修复，之前版本没有这个问题的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月6日(星期五) 晚上7:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zzaphkiel/Seraphine] [BUG] 在不同显示器中拖动窗口会导致 UI 的缩放不符合预期 (Issue #553)














 
明白了，试了一下好像确实有这么个问题，目前还不确定是哪里的 BUG，也不确定好不好修
 
之前理解成拖动一下窗口会让程序直接挂了

**Comment by Zzaphkiel** [comment]
d4e257a 修复了该问题
