### ISSUE TITLE
[Enhancement]  增加奖励补领

### ISSUE THREAD

**Issue by qq846511277** [Zzaphkiel/Seraphine#554]
### 功能描述

增加奖励补领

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
可以试试 [LeaguePrank](https://mitay.net/LeaguePrank.html#%E2%98%91%EF%B8%8F-%E4%B8%80%E9%94%AE%E9%A2%86%E5%8F%96%E5%A5%96%E5%8A%B1)，我们暂无实现计划
