### ISSUE TITLE
[BUG] 关闭OPGG窗口时会连同整个软件被关闭

### ISSUE THREAD

**Issue by Pizzdd** [Zzaphkiel/Seraphine#555]
### 问题描述

玩大乱斗和云顶，会弹出OPGG窗口，但是随手关闭窗口，连同主程序也会彻底关闭

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
无法复现。

可以选择手动关闭 “自动弹出 OPGG 窗口” 选项

**Comment by Pizzdd** [comment]
> 可以选择手动关闭 “自动弹出 OPGG 窗口” 选项

https://github.com/user-attachments/assets/74835706-7b24-4b79-adb6-61de3d870dc4

这个是复现视频，可以确认下

**Comment by Pizzdd** [comment]
https://wwft.lanzoul.com/imHmq2huv2ha
复现视频下载链接

**Comment by Zzaphkiel** [comment]
回复的有点慢，忙忘记了，抱歉

经过测试发现**只有当 Seraphine 隐藏在任务栏托盘中**（非最小化）时，关闭 OP.GG 窗口会将 Seraphine 一起关闭，这应该是 BUG，问题原因还待定位。

**Comment by Zzaphkiel** [comment]
c10c38c 修复了该问题。
