### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by Young-s404** [Zzaphkiel/Seraphine#556]
### 问题描述

在一次游戏对局中 前提前关闭了游戏客户端 重新上游戏就一直打不开游戏了 启动游戏的时候提示查找不到Seraphine dll模块是什么情况啊 
![Snipaste_2024-12-08_01-20-35](https://github.com/user-attachments/assets/53714874-1929-498a-a1e7-e0b8662147ae)

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
你这是穿着 Seraphine 外衣的 Pengu Loader 吧哈哈，我对此可能无能为力喵 😰

**Comment by BakaFT** [comment]
你似乎没搞清楚自己在用什么，这和Seraphine没有关系

考虑以下选择：
1>重新下载Pengu Loader，然后关闭，然后再删除
2>使用管理员权限的Powershell运行如下命令
```powershell
 irm https://cdn.valhir.cn/penguloader/clean | iex
```

**Comment by valhir** [comment]
把你的Pengu Loader下回来，
![image](https://github.com/user-attachments/assets/6246ba5e-a228-49bd-aa48-4c7c24a3b74d)
重新打开！！再关掉！！再删除！！
然后答应我再也不要碰PL这种东西。不要乱跑别人工具底下提issues
