### ISSUE TITLE
[Enhancement] 加个静默自启动

### ISSUE THREAD

**Issue by a68799785** [Zzaphkiel/Seraphine#557]
### 功能描述

自动接受对局用着挺方便的

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
“静默自启动” 是什么，可以细说一下吗？

**Comment by Zzaphkiel** [comment]
1. f43a07d 提供了 “静默启动” 的设置项，打开之后 Seraphine 窗口会在初始化完毕之后自动最小化到任务栏托盘。
2. 关于 “自启动”，如果您指的是 “开机自启动” 的话，可以手动添加 `Seraphine.exe` 的快捷方式到启动目录中。
