### ISSUE TITLE
[Enhancement] LOL登录界面自动化

### ISSUE THREAD

**Issue by myesn** [Zzaphkiel/Seraphine#558]
### 功能描述

**现状**：
启动 Seraphine，它再启动 LOL 客户端（会先弹出安全警告弹窗，需要手动点击确定），然后需要我手动在 LOL 登录界面输入账号、密码，并点击登录，再选择和确认大区。

**自动化改进**：
预设 QQ 登录的账号、密码、大区 信息，再通过自动化技术实现上述手动操作步骤，从而实现 "真 · 一键启动"。

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
有点麻烦，感觉得上 Windows API 了，而且安全性也有点难保证，还是用 WeGame 吧🥲？
