### ISSUE TITLE
[Enhancement] 大乱斗骰子显示

### ISSUE THREAD

**Issue by znwhyoo** [Zzaphkiel/Seraphine#559]
### 功能描述

不知道有没有关于队友骰子相关的接口  在大乱斗选英雄阶段显示队友是否有骰子或者已经骰了骰子 真的很讨厌那些玩大乱斗藏骰子的人  最后还是感谢作者 很好用的工具

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
我目前还不知道有哪个 API 可以实现这一特性，而且我个人认为关注队友有没有藏骰子这一动机没有很大的必要~
