### ISSUE TITLE
[BUG] 调整窗口大小后，拖动窗口会导致窗口大小复原

### ISSUE THREAD

**Issue by wqdraf2** [Zzaphkiel/Seraphine#560]
### 功能描述

你好，自从更新过后 每次调整好软件的大小都会自动变回预设 因为我是大屏幕所以使用上非常困扰
我希望可以像以前一样可以透过拉伸去自定义它的大小
我明白新功能可以适合有些用户，或者是否可以在设置里增加一个开关的选项？
如果该开关已经存在，麻烦告诉我位置 (我找了一遍 目前没找到)

软件版本为1.1.2

希望你能接纳我的建议 谢谢

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
感谢反馈，其实这是我的问题，修 #553 没修明白产生了新 BUG，下次更新会修复它。

**Comment by Zzaphkiel** [comment]
21bf329 修复了该问题
