### ISSUE TITLE
【无法启动】from app.common.qfluentwidgets import FluentTranslator 找不到对应组件

### ISSUE THREAD

**Issue by LR1093141031** [Zzaphkiel/Seraphine#561]
### 问题描述

【无法启动】from app.common.qfluentwidgets import FluentTranslator 找不到对应组件

【python3.13】主环境 
依赖包与request完全一致
![image](https://github.com/user-attachments/assets/ff03f84b-3c9f-4921-8e5a-4b3beb51d8b4)

from app.common.qfluentwidgets import FluentTranslator 报错
![image](https://github.com/user-attachments/assets/cc07706f-f57b-4259-b082-fdb9b4ffdf9a)
![image](https://github.com/user-attachments/assets/2fcc8666-e1de-4ee0-a4e1-75c62814049d)

### 在提交之前，请您确认

- [X] 我已经查看了 [常见问题 FAQ](https://github.com/Zzaphkiel/Seraphine?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-faq-)，但并不能解决我的问题
- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，但并不能解决我的问题

**Comment by Zzaphkiel** [comment]
因为我不太使用 PyCharm，所以我只能推荐你尝试一下看看怎么把你使用的环境切换到 seraphine 虚拟环境下。

**Comment by LR1093141031** [comment]
跟pycharm没关系吧，直接python命令行也不行
用conda 降级python到3.8.20 解决问题
