### ISSUE TITLE
[Enhancement] （希望可以增加一个自动配置出装文件的功能，opgg增加置顶功能）

### ISSUE THREAD

**Issue by ggbondgen** [Zzaphkiel/Seraphine#562]
### 功能描述

参考 https://github.com/cangzhang/champ-r 把几个网站的高胜率出装文件直接导入进游戏里
给opgg界面增加置顶功能 最好是只在bp阶段的界面置顶

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
1. 关于导入出装文件，由于 [champ-r](https://github.com/cangzhang/champ-r) 会获取多种来源、多种英雄的出装信息，所以将它们统一导入到文件里会显得比较有意义；而我们只获取 OP.GG 的出装信息，且是只针对某一英雄的信息，这些信息是看一眼就可以记住的，所以将它们导入文件相较于实现起来的麻烦程度，显得意义不是很大。故暂无实现计划。
2. 3401e33 实现了置顶 OP.GG 窗口功能以及设置项。
