### ISSUE TITLE
对局详情页没有巢虫数

### ISSUE THREAD

**Issue by zhengkw** [Zzaphkiel/Seraphine#563]
### 功能描述

中立资源结算页里面没有涵盖巢虫，目前巢虫对对局影响比较高，能加一个吗？

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
当然可以！

2daec34 已实现该特性
