### ISSUE TITLE
玩家标记

### ISSUE THREAD

**Issue by xuyangyuzhuo** [Zzaphkiel/Seraphine#565]
### 功能描述

希望能增加玩家标记功能，下次再匹配到就可以知道是否是自己讨厌或者点赞的玩家

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
暂无相关计划。
![QQ20241225-161156](https://github.com/user-attachments/assets/ffdedcab-7afa-4cfb-ae60-cb46a397b65c)
