### ISSUE TITLE
[Enhancement] 更新版本后，界面缩放问题

### ISSUE THREAD

**Issue by Jinzedev** [Zzaphkiel/Seraphine#566]
### 功能描述

新版本后，字体太小了，看不清，为了让字体变大我点击更改界面缩放，新的界面以屏幕中间生成，出现窗口太大，需要重启，无法解决字体太小问题，应该让用户选择字体
![image](https://github.com/user-attachments/assets/6166bc60-8df9-4fb2-88f1-379bfbcd0940)

### 在提交之前，请您确认

- [X] 我已经查看了之前（包括已经关闭）的 [issues](https://github.com/Zzaphkiel/Seraphine/issues?q=is%3Aissue)，其中并没有与我相同的想法

**Comment by Zzaphkiel** [comment]
可以尝试：
1. 将 Seraphine DPI 缩放改为 100%
2. 重启 Seraphine，并将窗口手动拖到最小
3. 将 Seraphine DPI 缩放改为你想要的数字
4. 重启 Seraphine，并手动调整窗口大小到你喜欢的大小

**Comment by Zzaphkiel** [comment]
计划下版本把窗口分辨率检测功能删掉，当初实现的时候想的有点简单了，它导致的问题太多了
