### ISSUE TITLE
战绩查询页为空的状态下, 将鼠标悬浮到控件位置仍能看到ToolTips

### ISSUE THREAD

**Issue by Hpero4** [Zzaphkiel/Seraphine#59]
![image](https://github.com/Zzaphkiel/Seraphine/assets/40506420/80b78f38-3f6d-4fcd-a0c5-a729bf75e7e3)

**Comment by Zzaphkiel** [comment]
感谢反馈，目前已定位该问题

**Comment by Zzaphkiel** [comment]
已修复该问题
