### ISSUE TITLE
客户端路径

### ISSUE THREAD

**Issue by Dudoer** [Zzaphkiel/Seraphine#6]
客户端路径怎么设置呀

**Comment by Zzaphkiel** [comment]
第一种方法：使用其他方式进入游戏（如直接打开客户端登录或通过 WeGame），然后启动 Seraphine （或提前启动好）后会自动设置客户端路径。
第二种方法：程序左下角有一个设置按钮，点进去到设置页面里，在 “通用 - 客户端路径” 选项卡中选择客户端路径，选择到 `TCLS` 文件夹即可。比如 `D:\LOL\英雄联盟\TCLS`
