### ISSUE TITLE
关于大乱斗骰子以及抢英雄相关功能的建议

### ISSUE THREAD

**Issue by liu1999888** [Zzaphkiel/Seraphine#63]
感受：
漂亮，没用过这么干净的软件
个性签名可能会掉，我掉过一次，可能是我中间切换了一次大区
卡片设置非常惊喜，加上锁战绩使用（狗头），赞👍
想法：
1战绩查询能不能做到不启动客户端查询和跨区查询
2如果可以跨区能不能直接看到在线状态
3能不能给其他玩家设置id标记或者收藏之类的功能，比如标记一个演员，一个绝活哥，一个疑似小代，且改名后依然在标记列表里，人少的区非常有用
4能不能做到具体符文查询
5出装查询，每次商店购买循序能不能查询，或者按照几分钟一次把装备图做出来，比如某个玩家游戏2分钟是什么装备出门的，第8分钟是什么装备，第15分钟是什么装备，第20分钟等等，方便学某些英雄的绝活哥出装
6一键乱斗建房，匹配建房，能一键邀请固定好友更好
7乱斗秒用骰子，用骰子秒切换回原来的英雄，设置喜好英雄，备选区出现喜欢英雄秒锁，可以拆分开，秒锁归秒锁，秒用骰子归秒用骰子
8胜率号，胜率车队提示，比如某个账号前10把或者前20把80%以上胜率，或者直接标注已经多少连胜
再次感谢作者

**Comment by liu1999888** [comment]
漂亮，没用过干净这么个软件
签名个性可能会掉，我掉过一次，可能是我中间切换了一次大区
卡片设置非常惊喜，加上锁战绩使用（狗头），赞👍

**Comment by Zzaphkiel** [comment]
感谢反馈

> 7. 乱斗秒用骰子，用骰子秒切换回原来的英雄，设置喜好英雄，备选区出现喜欢英雄秒锁，可以拆分开，秒锁归秒锁，秒用骰子归秒用骰子

这个根据实现难度会酌情考虑一下，而且感觉这个功能是不是有些“太”破坏其他玩家的游戏体验了？要不要真的做需要再斟酌一下~

> 8. 胜率号，胜率车队提示，比如某个账号前10把或者前20把80%以上胜率，或者直接标注已经多少连胜

这个在对局信息界面中不是一目了然嘛？

其他的我跟 @Hpero4 的想法基本一致😘

**Comment by LQ645218172** [comment]
我想补充一个点子，排位BP阶段往往非常关键，一个良好的阵容和对线克制关系很大程度决定了这局对战的走向。是否可以根据以下三个因素来实时推荐自己的英雄选择：1.玩家自身熟练度（取成就点数或玩家自行设定每个位置英雄池） 2.当前位置版本强势英雄（数据来自OPGG或101数据站，如无API可以爬虫） 3.对方所选英雄的counter关系 （数据来自OPGG，英雄克制关系-线杀率、全局胜率）；根据以上三项因素设置不同权重（基于规则判断或者用神经网络算法来实现）从而进行实时推荐英雄选择。

**Comment by Zzaphkiel** [comment]
@LQ645218172 感谢反馈

新建议建议新开 issue 哦。您提的这几点目前只有做 OPGG 梯队排行显示的打算，至于其他方面感觉实现功能的性价比较低，暂时就不考虑了~

**Comment by liu1999888** [comment]
id标记做云端不行能不能就做个搜索记录出来，比如点一下搜索框，下面自动弹出来最近搜索的人 @Hpero4

**Comment by liu1999888** [comment]
这个根据实现难度会酌情考虑一下，而且感觉这个功能是不是有些“太”破坏其他玩家的游戏体验了？要不要真的做需要再斟酌一下~

这个我的想法是乱斗模式本就没用绝对的公平，抛开玩家不谈的话，本就是随机5v5，这个胜率是随机的，看作x，这个x加上任何数，比如1，就是x+1，x还是那个x，我也不知道这个例子能不能解释出我的想法
或者更简单的说，乱斗玩家基本不会就揪着几个英雄玩的，玩多了自己也受不了不想玩，而且乱斗的英雄强度平衡性做好多年了，里面的英雄强度和峡谷强度完全不一样的，这个功能更像是当前特别想玩某个英雄，而自己手速过慢，对我自己来说，如果别人原来是剑圣，用一次骰子，变剑姬了，我把剑圣拿了，而那个玩家和我交换，我也依然会换，如果是开黑就不一样了，我抢到了就是我的，想玩就得叫霸霸

胜率号，胜率车队提示，比如某个账号前10把或者前20把80%以上胜率，或者直接标注已经多少连胜


我的想法是，直接加个标记，这个标记可以是3连胜4连胜5连胜等等，也可以加连败标记，这个想法来源是一个叫做奕狐的云顶插件，按住~就会一键显示当前玩家的最近10信息，其中就会显示此玩家多少连胜或者连败。我觉得这个快捷键也有搞头，更加方便

以上是我的个人想法

还有就是不知道你们是怎么看待软件推广的，我应该是自己偷偷用还是小圈子用还是支持大范围推广，我目前也只敢分享给几个好友使用，怕散播开了腾讯给你们ban了，我用的上一个战绩查询就是个叫做中韩排行的微信公众号，后来公众号被封了他们又搞了个app，在后来他们的app都是限时随缘开放查询了

 @Hpero4 @Zzaphkiel 感谢作者



又想到了个问题，我和好友开黑，都打开秒选英雄，都选亚索，会出现什么情况，谁网速好亚索归谁吗?


又又想到了个问题，主题色能不能加个灰色（狗头）

**Comment by Hpero4** [comment]
感谢反馈! 

以下是回复:
> 乱斗抢英雄
酌情考虑实现, 不一定会做

> 连胜（败）、车队提示
与目前UI设计所表达出的信息有重合，不打算另行实现了

> 搜索记录
考虑实现, 可能会在未来1~2个版本

> 软件推广
我认为低调使用吧, 但是如果面临封禁, 往往是所有同类软件都遭殃, 因为目前都是基于LCU的API进行实现的. 可以听听 @Zzaphkiel 的意见

> 抢亚索
如你所提到的, 是谁网速好谁抢到, 最终能够锁定的只有一个人

> 灰色主题
目前暗色主题已经能满足绝大部分场景, 考虑到控件兼容性以及风格统一, 应该不会考虑另做灰色

**Comment by liu1999888** [comment]
@Hpero4 赞，期待未来更完美的软件

**Comment by BariFL** [comment]
> 感谢反馈
> 
> > 7. 乱斗秒用骰子，用骰子秒切换回原来的英雄，设置喜好英雄，备选区出现喜欢英雄秒锁，可以拆分开，秒锁归秒锁，秒用骰子归秒用骰子
> 
> 这个根据实现难度会酌情考虑一下，而且感觉这个功能是不是有些“太”破坏其他玩家的游戏体验了？要不要真的做需要再斟酌一下~
> 
> > 8. 胜率号，胜率车队提示，比如某个账号前10把或者前20把80%以上胜率，或者直接标注已经多少连胜
> 
> 这个在对局信息界面中不是一目了然嘛？
> 
> 其他的我跟 @Hpero4 的想法基本一致😘


感谢几位开发者对软件的持续维护
大乱斗抢备战席英雄这个功能其他项目有    不知道有没有参考性   
https://github.com/BruceQiu1996/NPhoenix

**Comment by liu1999888** [comment]
最新版云顶bug，原来用的是别人分享的旧版本，昨天换了最新版，云顶也会自动查询其他玩家战绩，而且会有一段大概10多秒的卡顿，就像300帧减到30帧那样，不是游戏一开始，是游戏中途这样，旧版本没有这个问题
旧版0.6.1现在是0.8.1

**Comment by Hpero4** [comment]
> 最新版云顶bug，原来用的是别人分享的旧版本，昨天换了最新版，云顶也会自动查询其他玩家战绩，而且会有一段大概10多秒的卡顿，就像300帧减到30帧那样，不是游戏一开始，是游戏中途这样，旧版本没有这个问题 旧版0.6.1现在是0.8.1

感谢反馈, 建议另开Issues

**Comment by civiliann** [comment]
花里胡哨的建议哈哈，能查战绩就很不错了。

**Comment by Swaynani** [comment]
我也很希望增加乱斗秒抢设置英雄或者根据opgg乱斗英雄排行抢预备英雄 我目前在使用一款叫NP的助手 有这个功能

**Comment by Zzaphkiel** [comment]
> 我也很希望增加乱斗秒抢设置英雄或者根据opgg乱斗英雄排行抢预备英雄 我目前在使用一款叫NP的助手 有这个功能

@Swaynani 感谢您的建议。

Seraphine 的初心是为在不影响到其他玩家游戏的前提下为使用者提供便利。对于 issue 上文中以及您提到的大乱斗秒抢英雄的功能。作为开发者，我们并不能约束所有用户使用该功能的场景，上线该功能不可避免地可能会对其他人的游戏体验造成不好的影响，所以很抱歉，Seraphine 目前并没有实现该功能的计划 🥲

关于查看 OPGG 排行的功能，已经有相关计划了，还请期待一下~
