### ISSUE TITLE
观战导致封号

### ISSUE THREAD

**Issue by Apheli0s9z** [Zzaphkiel/Seraphine#64]
您好，我使用0.7.2版本观战导致封号，请问是观战会导致封号还是因为我没更新到最新版本而导致观战封号呢？如果是后者希望您能加入一个新版本的提示，万分感谢！！！

**Comment by garyvalue** [comment]
这应该不是观战引起的封号，建议自己查询原因
https://lol.qq.com/act/a20151118fh/

**Comment by Zzaphkiel** [comment]
同上，如果真的是由于观战导致的，会在相关功能除以及 `readme.md` 做出警告的~
