### ISSUE TITLE
无法启动客户端

### ISSUE THREAD

**Issue by cynide00** [Zzaphkiel/Seraphine#66]
![屏幕截图 2023-09-20 213527](https://github.com/Zzaphkiel/Seraphine/assets/112885731/0a3b85e0-2f4b-41f0-80ec-031f297e7907)
无法启动客户端

**Comment by Zzaphkiel** [comment]
感谢反馈。先打开客户端再开软件试试？

**Comment by cynide00** [comment]
能正常使用，只是无法在软件内打开客户端

**Comment by Zzaphkiel** [comment]
大概率和软件无关， WeGame 修复 / 重装游戏试试吧😥
