### ISSUE TITLE
新版本中云顶模式卡顿, 疑似因拉取战绩导致

### ISSUE THREAD

**Issue by Hpero4** [Zzaphkiel/Seraphine#69]
最新版云顶bug，原来用的是别人分享的旧版本，昨天换了最新版，云顶也会自动查询其他玩家战绩，而且会有一段大概10多秒的卡顿，就像300帧减到30帧那样，不是游戏一开始，是游戏中途这样，旧版本没有这个问题
旧版0.6.1现在是0.8.1

_Originally posted by @liu1999888 in https://github.com/Zzaphkiel/Seraphine/issues/63#issuecomment-1728918179_

**Comment by liu1999888** [comment]
不好描述，因为老版本玩云顶不拉其他玩家战绩的，新版会拉，而且拉出来的还有排版bug，这个我没截图，请作者辛苦自己开把云顶试一下，我觉得既然不准备做云顶查询的话，不如直接把云顶屏蔽掉，检测出开的游戏是云顶就直接默认不查询就好了，加个狗头

**Comment by liu1999888** [comment]
描述不好，因为老版本玩云顶不拉其他玩家战绩的，新版会拉，而且拉出来的还有排版bug，这个我没截图，请作者辛苦自己把云顶试了一下，我觉得既然不准备做云顶查询的话，检测出开的游戏是云顶就直接默认不查询就好了，加个狗头

**Comment by Hpero4** [comment]
@liu1999888 您好, 我review了一下6.0tags和当前代码, 暂时没有发现可能会触发卡死的差异, 想跟您确认一下:

1. 问题稳定复现吗? 每一局云顶之弈都会出现?
2. 问题出现时, 软件在哪个界面? 有没有显示加载中页面?
3. 问题出现在哪个阶段? 是读条后? 还是游戏进行到一定时间出现?

**Comment by liu1999888** [comment]
作者你好，我也回忆了一下，前天玩云顶下线后下载的0.8.1，当时只是下载并没有使用
第一次使用0.8.1是昨天下午，可能是第一把也可能是第二把，出现一次卡顿，时间大概10秒左右，具体就同上所诉，截图没有，当时想截图的但是没挂微信，不知道电脑有没有自带的截图工具，就放弃截图了，手机拍照是完全没想到，没这个觉悟。至于后来卡不卡，抱歉我没感觉出来，因为我用的带鱼屏，左边看视频，右边玩云顶，到底卡没卡我没注意，我只是当时发现了就来反馈了
今天看到作者回复观察了测试了三把，均无卡顿，很认真测的，b站都没开就看看动态，而且我发现0.6.1也是会自动在云顶对局中查询其他玩家战绩的，我原来认为的0.6.1不会自动查询战绩可能是因为我玩云顶就算开了软件也没打开软件页面所误导的，这是错误信息，抱歉！不过我发现了一旦对局中关闭软件在重新打开就会出现空白页面，两个版本都是这样的，这个我测试了好几次。

1我确认的情况只在昨天发现一次
2问题出现时点开软件时直接显示在战绩查询的界面，当时的界面是八个友方，敌方空白，右方第一个或者第四个战绩不显示，会在显示详细战绩的地方显示该玩家id
3出现在对局中，前期，二阶段还是三阶段来着，游戏开始后5-15分钟左右把

因为原来从来没有出现过这种卡顿，所以我当时估计是这个0.8.1的新版软件出现的bug，且打开后出现了云顶的战绩查询显示bug，这个显示bug昨天后来每一把都存在，今天没了，虽然还是自动查询云顶对局，但是不卡了，显示bug也没了

使用环境怎么说呢，反正当时左边视频没卡，可能视频有缓存没感觉出来，但是如果是网络原因的话可能和昨天的卡顿关系不大，因为几年了还没卡过这么久的，不对是还没玩云顶卡过
梯子当时挂没挂也不清楚，可能挂了也可能没挂，但是英雄联盟客户端好像除了挂路由器梯子才会生效，梯子软件应该影响不到客户端，因为以前没卡过
其他插件的话有可能，但是我还是不确定昨天开了其他插件没有，今天我也测试了一把同时打开其他插件的对局，会在云顶开局选城邦的时候小卡一下大概2-3秒，游戏中无异常，这个插件是云顶专用的，叫云顶奕狐，这个插件还有个前置软件叫cube，但是这个插件有点小卡是开局选城邦的时候小卡一下下，不确定和昨天的10秒卡顿有没有关联

希望这堆我很尽力表达清楚的废话对你有用，作者辛苦了 @Hpero4

**Comment by liu1999888** [comment]
作者你好，我也回忆一下，前天玩云顶下线后下载的0.8.1，当时只是下载并没有使用
第一次使用0.8.1是昨天下午，可能是第一把也可能是第二把，出现一次卡顿，时间大概10秒左右，具体就同上所诉，截图没有，想截图的但是没挂微信，不知道电脑有没有自带的截图工具，就放弃截图了，手机拍照完全是到了后来，没这个觉悟。至于后来卡不卡，抱歉我没感觉出来，因为我用的带鱼屏，左边看视频，右边玩云顶，到底卡没卡我没注意，我只是当时发现了就来反馈了
今天看到作者回复观察了测试了三把，均无卡顿，很认真测的，都没开b站就看看动态，而且我发现0.6.1也会自动在云顶对局中查询其他玩家战绩的，我原来以为0.6.1不会自动查询战绩可能是因为我玩云顶就算开了软件也没软件打开页面所以不正确的，这是错误信息，抱歉！不过我发现一旦对局中关闭软件在重新打开就会出现空白页面，两个版本都是这样的，这个我测试了好几次。

1我确认的情况只是在昨天发现一次
2问题出现时点开软件时直接显示在战绩查询的界面，当时的界面是八个友方，敌方空白，右方第一个或者第四个战绩不显示，会在显示详细战绩的位置显示该玩家id
3出现在对局中，前期，第二阶段或第三阶段来着，游戏开始后5-15分钟左右把

因为以前从来没有出现过这种卡顿，所以我估计是这个0.8.1的新版软件出现的bug，且前提是打开后出现了云顶的战绩查询显示bug，这个显示bug昨天后来每个都存在，今天没了，虽然还是自动查询云顶对局，但是不卡了，显示bug也没了

使用环境也一样呢，不过当时左边视频没卡，可能视频有缓存没感觉出来，如果是网络原因的话可能和昨天的卡顿关系不大，因为几年了还没卡过这么久的，么还没玩云顶卡过
梯子当时挂没挂也运动员，可能挂了也可能没挂，但是英雄联盟客户端希望除了挂路由器梯子才会生效，梯子软件应该影响不到客户端因为，以前没过
其他插件的话有可能，但是我还是不确定昨天开了其他卡插件没有，今天我也测试了一把同时打开其他插件的对局，会在云顶开局选城邦的时候小卡一下大概2-3秒，游戏中无异常，这个插件是云顶专用的，叫云顶奕狐，这个插件还有个前置软件叫cube，但是这个插件有点小卡是开局选城邦的时候小卡一下下，不确定和不确定昨天的10秒卡顿有没有关联

希望这个堆我很尽力表达清楚的废话对你有用，作者辛苦了@Hpero4

**Comment by Hpero4** [comment]
您好! 感谢反馈!

根据描述, Seraphine存在引起卡顿的可能性, 但不直接相关;

关于云顶之弈模式下仍会自动拉取"对局信息"的回复: 
-> **由于截至目前软件设计暂未考虑云顶之弈的相关支持, 所以我认为这属于BUG, 我们会在后续版本中修复(因为我没有下棋 所以可能进展缓慢 _(:з」∠) _**

**Comment by liu1999888** [comment]
_(:з」∠) _
