### ISSUE TITLE
依赖找不到

### ISSUE THREAD

**Issue by luoysuan** [Zzaphkiel/Seraphine#70]
新手刚学python，使用阿里云和清华以及conda-forge的镜像下载PyQt5==5.15.9
![image](https://github.com/Zzaphkiel/Seraphine/assets/51365362/6456c6df-f68e-4904-8c74-1b41af1b24a4)
![image](https://github.com/Zzaphkiel/Seraphine/assets/51365362/29e6769d-3cfd-4fd8-855c-155427ffc363)

去conda官网找也只找到5.15.6的
![image](https://github.com/Zzaphkiel/Seraphine/assets/51365362/63a80600-af1b-4ded-89ed-7f8f4ecdf058)

**Comment by Zzaphkiel** [comment]
`pip` 有 → [点我看看](https://pypi.org/project/PyQt5/) ←，使用
``` shell
pip install PyQt5
```
试试
