### ISSUE TITLE
太棒了 希望可以增加更多功能！

### ISSUE THREAD

**Issue by Swaynani** [Zzaphkiel/Seraphine#78]
太感谢作者了 差外服战绩非常快 希望可以增加符文装备配置  和 大乱斗秒抢备选英雄的功能

**Comment by Zzaphkiel** [comment]
感谢支持和反馈，相关建议在之前已经收到，目前已经在准备中了~

**Comment by Swaynani** [comment]
> 感谢支持和反馈，相关建议在之前已经收到，目前已经在准备中了~

大乱斗抢预备英雄 这个功能太牛皮了 真希望大佬给安排上
