### ISSUE TITLE
遇到的一点点小问题.

### ISSUE THREAD

**Issue by AnsonYjs** [Zzaphkiel/Seraphine#82]
-对局数据消失；
 就是有遇到一场对局结束后，软件刷新是看不到那场比赛的成绩的；在Wegame上是有显示的，不知道是不是bug，前后的对局都有，唯独丢失了那局；

-天赋符文；
 不知道是否有机会考虑追加opgg的英雄天赋符文&出装推荐之类的设置？
 或者可以考虑沿用国服官网的英雄天赋符文出装推荐也可以的，看到前面也有大佬提到过；

额外提问，请问反馈问题是只能在Github上进行吗？

**Comment by Zzaphkiel** [comment]
感谢反馈~

1. 我们也注意到这个问题了，不过对它的出现目前还没有一个很好的解释与修复方法 😥
2. 之前已经讨论过了，已经在规划中了。
3. 目前 GitHub 还是唯一且最有效的方式~

**Comment by AnsonYjs** [comment]
@Zzaphkiel 
-战绩显示，在游戏加载界面里面，关于敌方信息没显示，就是空了某一位敌对玩家信息的现象；
尝试进行复现问题，但是没能复现出来，就遇到过一次；

**Comment by Hpero4** [comment]
@AnsonYjs 您好, 感谢反馈!

想确认下您提到的"空了一位"是指"对局信息"中某位召唤师一盘战绩都没有吗? 还是指压根就只有4位召唤师?

**Comment by AnsonYjs** [comment]
@Hpero4 
不是 就是选完英雄界面进入到加载游戏的画面 可以显示敌对玩家的战绩信息 然后其中一位敌对玩家的全部战绩成绩没显示。

**Comment by Hpero4** [comment]
也就是指 "对局信息"中某位敌方召唤师一盘历史战绩都没有, 对吗? 

这可能是加载失败导致的, 后续考虑更新retry机制, 并添加更显眼的提示

**Comment by AnsonYjs** [comment]
> 也就是指 "对局信息"中某位敌方召唤师一盘历史战绩都没有, 对吗?
> 
> 这可能是加载失败导致的, 后续考虑更新retry机制, 并添加更显眼的提示

对
