### ISSUE TITLE
希望增加搜索历史记录的功能

### ISSUE THREAD

**Issue by LeopoldChou** [Zzaphkiel/Seraphine#88]
目前软件的使用体验很好，UI 布局也很舒服，有两个小小的建议：

1. 能否记录查询战绩和观战的召唤师 ID 历史记录？例如我朋友的召唤师 ID 有繁体字而且比较难输，如果有历史记录的话就不用每次观战都来回切输入法输一遍了（历史记录如果做进去的话，麻烦也做上有删除或清空的功能）；

2. runtime 和各种运行库现在都在软件的根目录，看着有点乱，能否把引用的外部库都装到例如 libs 文件夹里？

感恩

**Comment by Zzaphkiel** [comment]
感谢反馈

1. 仓库版本已经实现搜索历史记录功能了，预计会随下个 release 版本上线
2. 目前的目录结构是 `pyinstaller` 打包时自动做的，我也不知道该咋弄了 😥
