### ISSUE TITLE
遇到问题

### ISSUE THREAD

**Issue by AnsonYjs** [Zzaphkiel/Seraphine#89]
-自动接受对局，存在小概率直接导致游戏闪退；
-想尝试复现的，就是出现的有点猝不及防；
-另外这个接受对局如果是在大乱斗模式下进行的话，会直接出现很有意思的现象，你已经进入游戏里面的话，可以重新连接进游戏，如果你是还在选择英雄界面的话，你重新进入游戏只是在游戏大厅，点击其他模式就会导致你原本在选角界面的等候区自动取消退出，然后进入5分钟秒退，而如果是在游戏大厅情况下你直接再次关闭游戏的话，就变成15分钟秒退惩罚

**Comment by Hpero4** [comment]
请问这种情况只出现在自动接受时吗？
出现了多少次？概率大概多少？
出现问题时, 您使用的软件版本是多少？

**Comment by AnsonYjs** [comment]
> 请问这种情况只出现在自动接受时吗？ 出现了多少次？概率大概多少？ 出现问题时, 您使用的软件版本是多少？

-0.8.1，出现了2次，昨天打了蛮多场对局了，概率应该是属于还好的，只有自动接受对局有概率发生这个情况；

**Comment by Hpero4** [comment]
感谢反馈！因复现概率不高, 会在后续版本中尝试修复；

您可以尝试一下使用最新的代码进行构建, 代码中对相关逻辑有一定优化

**Comment by AnsonYjs** [comment]
请问现在有更新版本或者说自动云端更新的吗？ 之前反应有概率出现在选角英雄界面突然客户端消失不见，或者由于开启了自动接受对局而导致客户端界面消失不见的情况；

**Comment by Zzaphkiel** [comment]
目前已发布新的打包版本，若遇到问题新开 issue 反馈哦～
