### ISSUE TITLE
能否添加新的功能

### ISSUE THREAD

**Issue by ynccsc** [Zzaphkiel/Seraphine#9]
查询该玩家近期与谁组队游玩以及胜率
查询该玩家近期英雄选择率及胜率
锁定游戏ESC设置

**Comment by Zzaphkiel** [comment]
感谢建议。

> 查询该玩家近期与谁组队游玩以及胜率
查询该玩家近期英雄选择率及胜率

感觉可以，应该会做到个人信息的界面里。不过这个功能要多请求若干次 api，可能会影响一些性能，大概要再加一个开关放在设置里面自己选择打开与否。

> 锁定游戏ESC设置

这个没太看懂啥意思 😢

**Comment by ynccsc** [comment]
就是锁定游戏内的设置  按键画面啥的
方便切换不同的账户还是自己的设置

**Comment by Zzaphkiel** [comment]
明白了，最近有些忙，等忙完再研究一下～

**Comment by ynccsc** [comment]
好的麻烦了

**Comment by Zzaphkiel** [comment]
> 加上云顶之弈战绩?

@kensh1nn 见 #16 和 #4，暂不会添加云顶之弈相关功能

**Comment by Zzaphkiel** [comment]
已实现
