### ISSUE TITLE
换号不改设置这个能不能单独打包一个软件出来

### ISSUE THREAD

**Issue by MniShark** [Zzaphkiel/Seraphine#90]

**Comment by Hpero4** [comment]
可以, 但Seraphine不打算这么做.

这并不会带来什么好处, 如果您对这块感兴趣, 可以自行参考仓库中的代码实现.

**Comment by Zzaphkiel** [comment]
可以参考[这个视频](https://www.bilibili.com/video/BV1s84y1x7ub)手动实现哦~
