### ISSUE TITLE
能否添加战绩中伤害，承伤等数据明细

### ISSUE THREAD

**Issue by beicdjp** [Zzaphkiel/Seraphine#92]

**Comment by beicdjp** [comment]
战绩查询能否添加页面跳转或指定日期查询

**Comment by Zzaphkiel** [comment]
感谢反馈~

对英雄伤害已经有显示了。因为当前的界面已经比较紧凑了，目前不会考虑在这个界面里添加更多的数据显示了~

> 战绩查询能否添加页面跳转

没太看懂什么意思？

> 指定日期查询

这个感觉意义不是特别的大？有什么比较显著的使用场景嘛？
