### ISSUE TITLE
刚使用软件有点不太会使用

### ISSUE THREAD

**Issue by shutiaokuangmo** [Zzaphkiel/Seraphine#93]
今天刚刚下载了软件，不知道为什么连不上客户端，路径设置不知道设置到哪个文件夹。如果可以的话建议写个简明操作手册，像我这样的小白就能直接上手使用了。作者辛苦啦！

**Comment by Zzaphkiel** [comment]
感谢反馈。

正常情况下是打开客户端的时候，Seraphine 会自动连接并设置客户端路径的，它为 `TCLS` 文件夹 （即 `client.exe` 所在文件夹）。

关于使用手册，目前没有要完成它的计划，可能将来会在自述文件里稍微提示一下~
