### ISSUE TITLE
建议，队列中添加对线建议选择的英雄好打，胜率高。

### ISSUE THREAD

**Issue by q847633684** [Zzaphkiel/Seraphine#95]
比如下路辅助和射手，中单和打野。
如同wegame一样，对面adc选择好英雄后，推荐选择哪个英雄克制。
选择那些英雄配合胜利高。或者强势。

**Comment by Hpero4** [comment]
感谢反馈！

该功能属于数据网站接入的一部分, 类似提议在 #10 中已有讨论, 后续有计划逐步实现, 目前阶段因人力原因暂时搁置了

**Comment by Zzaphkiel** [comment]
相关进展的讨论请移步 #10
