### ISSUE TITLE
新版本用不了辣大佬

### ISSUE THREAD

**Issue by weluck** [Zzaphkiel/Seraphine#99]

**Comment by Hpero4** [comment]
感谢反馈！

请详细描述一下您遇到的问题以及所使用的软件版本

**Comment by YGGRZZ** [comment]
13.20版本什么都用不了了

**Comment by YGGRZZ** [comment]
> 感谢反馈！
> 
> 请详细描述一下您遇到的问题以及所使用的软件版本

13.20版本什么都用不了了，登陆都连不上

**Comment by bhjfugib** [comment]
是的 用不了大佬

**Comment by bhjfugib** [comment]
最新版本的软件和13.20一直在转圈

**Comment by q1ngy1ng** [comment]
我也是，一直转圈圈😭辛苦大佬了

**Comment by q1ngy1ng** [comment]
哦对了，不管是用软件里面的启动客户端还是wegame登陆客户端都不行，重启或者以管理员身份打开都不行🥹

**Comment by Hpero4** [comment]
@weluck @YGGRZZ @q1ngy1ng @bhjfugib 请问各位使用的都是v0.8.1版本吗？

**Comment by YGGRZZ** [comment]
> @weluck @YGGRZZ @q1ngy1ng @bhjfugib请问各位使用的都是v0.8.1版本吗？

对的大佬

**Comment by weluck** [comment]
> @weluck @YGGRZZ @q1ngy1ng @bhjfugib请问各位使用的都是v0.8.1版本吗？

是的

**Comment by Hpero4** [comment]
@weluck @YGGRZZ @q1ngy1ng @bhjfugib

很抱歉, 经测试, 在LOL最近更新的版本(13.20)中, 
获取生涯页信息时有较高的概率会得到空数据(在不常登陆的账号或特定大区"艾欧尼亚"尤为明显), 
此时v0.8.1版本的软件未进行任何处理, 导致后续逻辑不再执行;

该问题在当前代码中已通过显示默认数据的方式规避, 保证后续逻辑执行正常.

非常遗憾, v0.8.1版本中没有更好的规避手段, 多次重启软件重试, 并避免进入其他召唤师的生涯页是唯一途径. 

需要等 @Zzaphkiel 发布新版本后, 更新解决.

**Comment by YGGRZZ** [comment]
> @weluck @YGGRZZ @q1ngy1ng @bhjfugib
> 
> 很抱歉, 经测试, 在LOL最近更新的版本(13.20)中, 获取生涯页信息时有较高的概率会得到空数据(在不常登陆的账号或特定大区"艾欧尼亚"尤为明显), 此时v0.8.1版本的软件未进行任何处理, 导致后续逻辑不再执行;
> 
> 该问题在当前代码中已通过显示默认数据的方式规避, 保证后续逻辑执行正常.
> 
> 非常遗憾, v0.8.1版本中没有更好的规避手段, 多次重启软件重试, 并避免进入其他召唤师的生涯页是唯一途径.
> 
> 需要等 @Zzaphkiel 发布新版本后, 更新解决.

🫡

**Comment by q1ngy1ng** [comment]
@YGGRZZ @Hpero4 好的 谢谢大佬们 大佬们辛苦了

**Comment by q1ngy1ng** [comment]
> @weluck @YGGRZZ @q1ngy1ng @bhjfugib 请问各位使用的都是v0.8.1版本吗？

是的

**Comment by Hpero4** [comment]
目前"艾欧尼亚"服务器存在问题, 获取生涯页时数据返回异常, 
v0.8.1版本软件未对此异常进行处理, 导致生涯页面一直转圈, 无法进行其他操作. 

该问题已在 #76 修复, 新版本发布后解决

![image](https://github.com/Zzaphkiel/Seraphine/assets/40506420/ee703f6f-660a-4727-a15a-4a4fe1e06237)

**Comment by YGGRZZ** [comment]
> 目前“艾欧尼亚”服务器存在问题，获取生涯页面时数据返回异常， v0.8.1版本软件未对此异常进行处理，导致生涯页面一直转圈，无法进行其他操作。
> 
> 该问题已在#76修复，新版本发布后解决
> 
> ![图像](https://user-images.githubusercontent.com/40506420/274948184-ee703f6f-660a-4727-a15a-4a4fe1e06237.png)

辛苦
